XPU-DSAM7S: src/rtos/ISR.cpp File Reference
ISR.cpp File Reference
#include "FreeRTOS.h"
Functions
void ISR_USB (void)
void ISR_Timer0 (void)
void ISR_FPGA (void)
void ISR_VBus (void)
void ISR_Wrapper_USB (void) __attribute__((naked))
void ISR_Wrapper_Timer0 (void) __attribute__((naked))
void ISR_Wrapper_FPGA (void) __attribute__((naked))
void ISR_Wrapper_VBus (void) __attribute__((naked))
Function Documentation
void ISR_FPGA (void)
Definition at line 23 of file fpga.cpp.
References xSEMA::ReleaseFromISR().
Referenced by ISR_Wrapper_FPGA().
{
    // Disable interrupt until interrupt is handled and enabled again (in some task).
    //
    AT91F_AIC_DisableIt( AT91C_BASE_AIC, AT91C_ID_IRQ0 );
    portBASE_TYPE isTaskWokenByPost = pdFALSE;
    if ( fpgaEvent.ReleaseFromISR( 1, isTaskWokenByPost ) )
    {
        isTaskWokenByPost = pdTRUE;
        }
    // Acknowledge the interrupt
    //
    AT91F_AIC_AcknowledgeIt( AT91C_BASE_AIC );
    // If an event caused a task to unblock then we call "Yield from ISR" to ensure
    // that the unblocked task is the task that executes when the interrupt completes
    // if the unblocked task has a priority higher than the interrupted task.
    //
    if( isTaskWokenByPost )
        portYIELD_FROM_ISR ();
    }
void ISR_Timer0 (void)
Definition at line 55 of file timerTasks.cpp.
References dTimerTick.
Referenced by ISR_Wrapper_Timer0().
{
    ++dTimerTick;
    (void) AT91C_BASE_TC0->TC_SR; // Clear interrupt
    AT91F_AIC_AcknowledgeIt( AT91C_BASE_AIC );
    }
void ISR_USB (void)
Definition at line 18 of file usbTasks.cpp.
References USB::CSTD::EventHandler(), isTaskWokenByPostInUsbIrq, and sSer.
Referenced by ISR_Wrapper_USB().
{
    isTaskWokenByPostInUsbIrq = pdFALSE;
    // USB_Handler may also call callbacks established by SER_Read()/SER_Write()
    //
    sSer.EventHandler ();
    AT91F_AIC_AcknowledgeIt( AT91C_BASE_AIC );
    // If an event caused a task to unblock then we call "Yield from ISR" to ensure
    // that the unblocked task is the task that executes when the interrupt completes
    // if the unblocked task has a priority higher than the interrupted task.
    //
    if( isTaskWokenByPostInUsbIrq )
        portYIELD_FROM_ISR();
    }
void ISR_VBus (void)
Definition at line 36 of file usbCallbacks.cpp.
References AT91C_PIO_VBUS, and USB::CSTD::Attach().
Referenced by ISR_Wrapper_VBus().
{
    sSer.Attach ();
    // Acknowledge the interrupt
    //
    AT91F_PIO_GetInterruptStatus( AT91C_PIO_VBUS );
    AT91F_AIC_AcknowledgeIt( AT91C_BASE_AIC );
    }
void ISR_Wrapper_FPGA (void)
void ISR_Wrapper_Timer0 (void)
Definition at line 49 of file ISR.cpp.
References ISR_Timer0().
Referenced by portTASK_FUNCTION().
{
    portSAVE_CONTEXT ();
    ISR_Timer0 ();
    portRESTORE_CONTEXT ();
    }
void ISR_Wrapper_USB (void)
Definition at line 40 of file ISR.cpp.
References ISR_USB().
Referenced by anonymous_namespace{usbCallbacks.cpp}::CCallbacks::OnInit().
{
    portSAVE_CONTEXT ();
    ISR_USB ();
    portRESTORE_CONTEXT ();
    }
void ISR_Wrapper_VBus (void)
Definition at line 67 of file ISR.cpp.
References ISR_VBus().
Referenced by anonymous_namespace{usbCallbacks.cpp}::CCallbacks::OnInit().
{
    portSAVE_CONTEXT ();
    ISR_VBus ();
    portRESTORE_CONTEXT ();
    }