XPU-DSAM7S: anonymous_namespace{usbCallbacks.cpp}::CCallbacks Class Reference
anonymous_namespace{usbCallbacks.cpp}::CCallbacks Class Reference
Public Member Functions
CCallbacks (CUsbDriver *pArgDriver)
Private Member Functions
void OnInit (void)
Callback API (usb_api_callbacks).
void OnReset (void)
Reset callback function.
void OnSuspend (void)
Suspend callback function.
void OnResume (void)
Resume callback function.
void OnNewRequest (void)
New Request callback function.
void OnStartOfFrame (void)
Interrupt SOF callback function Invoked when a SOF interrupt is received.
Private Attributes
CUsbDriver * pDriver
Detailed Description
Definition at line 53 of file usbCallbacks.cpp.
Constructor & Destructor Documentation
anonymous_namespace{usbCallbacks.cpp}::CCallbacks::CCallbacks (CUsbDriver * pArgDriver) [inline]
Definition at line 119 of file usbCallbacks.cpp.
References TRACE_INFO.
    {
        pDriver = pArgDriver;
        TRACE_INFO( "CCallback %08x, Driver=%08x\n", uint( this ), pDriver );
    }
Member Function Documentation
void anonymous_namespace{usbCallbacks.cpp}::CCallbacks::OnInit (void) [private, virtual]
Callback API (usb_api_callbacks).
These callback functions are used by the USB API to notify the user application of incoming events or actions to perform. Initialization callback function This callback is invoked whenever the USB API is initialized using the CUsbDriver::Init function. It should perform the following operations:
If an OS is being used, install the USB driver
Configure the USB controller interrupt
Configure the VBus monitoring interrupt Attention: Implementation of this callback is mandatory
See also:
CUsbDriver::Init
Implements USB::CEventSink.
Definition at line 131 of file usbCallbacks.cpp.
References AT91C_ID_VBUS, AT91C_PIO_VBUS, AT91C_VBUS, USB::CUsbDriver::Attach(), USB::CUsbDriver::GetDriverID(), ISR_Wrapper_USB(), ISR_Wrapper_VBus(), pDriver, and TRACE_DEBUG_M.
{
    TRACE_DEBUG_M( "OnInit\n" );
    // Configure and enable the USB controller interrupt
    //
    AT91F_AIC_ConfigureIt
    (
        AT91C_BASE_AIC,
        pDriver->GetDriverID (),
        AT91C_AIC_PRIOR_LOWEST,
        0, //AT91C_AIC_SRCTYPE_INT_HIGH_LEVEL,
        ISR_Wrapper_USB
        );
    AT91F_AIC_EnableIt( AT91C_BASE_AIC, pDriver->GetDriverID () );
#ifdef USB_SELF_POWERED
    // Configure and enable the Vbus detection interrupt
    AT91F_AIC_ConfigureIt
    (
        AT91C_BASE_AIC,
        AT91C_ID_VBUS,
        AT91C_AIC_PRIOR_LOWEST,
        0, //AT91C_AIC_SRCTYPE_INT_HIGH_LEVEL,
        ISR_Wrapper_VBus
        );
    AT91F_PIO_InterruptEnable( AT91C_PIO_VBUS, AT91C_VBUS );
    AT91F_AIC_EnableIt( AT91C_BASE_AIC, AT91C_ID_VBUS );
#else
    // Power up the USB controller
    pDriver->Attach ();
#endif
    }
void anonymous_namespace{usbCallbacks.cpp}::CCallbacks::OnReset (void) [private, virtual]
Reset callback function.
Invoked whenever the device is reset by the host. This function should perform initialization or re-initialization of the user application. Attention: Implementation of this callback is optional
See also:
CUsbDriver::EventHandler
Implements USB::CEventSink.
Definition at line 207 of file usbCallbacks.cpp.
References TRACE_DEBUG_M.
{
    TRACE_DEBUG_M( "OnReset\n" );
}
void anonymous_namespace{usbCallbacks.cpp}::CCallbacks::OnSuspend (void) [private, virtual]
Suspend callback function.
Invoked when the device is suspended by the host or detached from the bus. If the device must enter low-power mode when suspended, then the necessary code must be implemented here.
See also:
CUsbDriver::Attach
CUsbDriver::EventHandler
Implements USB::CEventSink.
Definition at line 174 of file usbCallbacks.cpp.
References TRACE_DEBUG_M.
{
    TRACE_DEBUG_M( "OnSuspend\n" );
    // DEV_Suspend ();
    }
void anonymous_namespace{usbCallbacks.cpp}::CCallbacks::OnResume (void) [private, virtual]
Resume callback function.
Invoked when the device is resumed by the host or attached to the bus. If the suspend callback has put the device into low-power mode, then this function must perform the necessary actions to return it to a normal mode of operation.
See also:
CEventSink::OnSuspend
CUsbDriver::Attach
CUsbDriver::EventHandler
Implements USB::CEventSink.
Definition at line 187 of file usbCallbacks.cpp.
References TRACE_DEBUG_M.
{
    TRACE_DEBUG_M( "OnResume\n" );
    // DEV_Resume ();
    }
void anonymous_namespace{usbCallbacks.cpp}::CCallbacks::OnNewRequest (void) [private, virtual]
New Request callback function.
Invoked when a new SETUP request is received. The request can then be retrieved by using the GetSetup function on the CUsbDriver instance.
See also:
CUsbDriver::EventHandler
Implements USB::CEventSink.
Definition at line 199 of file usbCallbacks.cpp.
References USB::CCDC::RequestHandler().
{
    sSer.RequestHandler ();
    }
void anonymous_namespace{usbCallbacks.cpp}::CCallbacks::OnStartOfFrame (void) [private, virtual]
Interrupt SOF callback function Invoked when a SOF interrupt is received.
See also:
CUsbDriver::EventHandler
Implements USB::CEventSink.
Definition at line 215 of file usbCallbacks.cpp.
{
    }
Member Data Documentation
CUsbDriver* anonymous_namespace{usbCallbacks.cpp}::CCallbacks::pDriver [private]
Definition at line 55 of file usbCallbacks.cpp.
Referenced by OnInit().
The documentation for this class was generated from the following file:
src/usb/usbCallbacks.cpp