XPU-DSAM7S: USB::CUsbDriver Class Reference
USB::CUsbDriver Class Reference
Low-level USB device driver abstract class.
#include <usbFramework.hpp>
Public Member Functions
virtual void * GetInterface (void)=0
USB API Methods.
virtual uint GetDriverID (void)=0
Returns the USB controller peripheral ID of a CUsbDriver instance.
virtual void Init (void)=0
Initializes the USB API and the USB controller.
virtual EnumStandardReturnValue Write (int bEndpoint, const void *pData, uint dLength, Callback_f fCallback=0, void *pArgument=0, const void *pDataLowerBound=0, const void *pDataUpperBound=0)=0
Sends data through an USB endpoint.
virtual EnumStandardReturnValue Read (int bEndpoint, void *pData, uint dLength, Callback_f fCallback=0, void *pArgument=0)=0
Receives data on the specified USB endpoint.
virtual EnumStandardReturnValue Stall (int bEndpoint=0)=0
Sends a STALL handshake for the next received packet.
virtual bool Halt (int bEndpoint, int bRequest)=0
Clears, sets or retrieves the halt state of the specified endpoint.
virtual void RemoteWakeUp (void)=0
Starts a remote wakeup procedure.
virtual bool ConfigureEndpoint (const S_usb_endpoint_descriptor *pEpDesc)=0
Configures the specified endpoint using the provided endpoint descriptor.
virtual bool Attach (void)=0
Handles the attachment or detachment of the device to or from the USB.
virtual void SetAddress (void)=0
Sets the device address using the last received SETUP packet.
virtual void SetConfiguration (void)=0
Sets the device configuration using the last received SETUP packet.
virtual void EventHandler (void)=0
Event handler for the USB controller peripheral.
virtual void Connect (void)=0
Connects the device to the USB.
virtual void Disconnect (void)=0
Disconnects the device from the USB. This method disables the pull-up resistor on the D+ line, notifying the host that the device wishes to disconnect from the bus.
void LinkTo (CEventSink *pArgEventSink, CBoard *pArgBoard)
Link device driver to CEventSink instance so CUsbDriver methods could send callbacks properly.
S_usb_request * GetSetup (void)
Returns a pointer to the last received SETUP request.
bool IsStateSet (uint flags) const
Poll the status of flags in dStatus register.
bool IsStateCleared (uint flags) const
Poll the status of flag(s) in dStatus register.
int GetNumEndpoints (void) const
Returns a number of configured endpoints.
void SetEndpointList (CEndpoint *list, int count)
Establish the list of configured endpoints.
EnumStandardReturnValue SendZLP0 (Callback_f fCallback=0, void *pArgument=0)
Sends a Zero-Length Packet (ZLP) through the Control endpoint 0.
Protected Member Functions
CUsbDriver (void)
Constructor. Just nullify/disable everything.
void SetState (uint flags)
Set flag(s) in dStatus register.
void ClearState (uint flags=0xFFFF)
Clear flag(s) in dStatus register. If the method is called without arguments, it will set dState to 0.
Protected Attributes
CEventSink * pEventSink
Pointer to associated CEventSink instance.
CBoard * pBoard
Pointer to associated CBoard instance.
CEndpoint * pEndpoints
Endpoints list.
int dNumEndpoints
Number of endpoints in list.
S_usb_request sSetup
Pointer to the last received SETUP packet.
volatile uint dState
Current state of the device.
bool useSOFCallback
Indicates wether to forward StartOfFrame events.
Detailed Description
Low-level USB device driver abstract class.
This class is used to provide an abstraction over which USB controller is used by the chip. This means the USB framework is fully portable between AT91 chips and supports chips with more than one controller. The structure holds information about the USB controller used, such as a pointer to the physical address of the peripheral, to the endpoints FIFO, etc. In most case, it is not necessary to declare a CUsbDriver instance: the defaultDriver global variable can be used. This is not possible for chips which have more than one USB controller in them, where each controller must have separate CUsbDriver instance.
See also:
CEventSink
Definition at line 762 of file usbFramework.hpp.
Constructor & Destructor Documentation
USB::CUsbDriver::CUsbDriver (void) [inline, protected]
Constructor. Just nullify/disable everything.
Definition at line 777 of file usbFramework.hpp.
References dNumEndpoints, dState, pBoard, pEndpoints, pEventSink, TRACE_INFO, and useSOFCallback.
    {
        TRACE_INFO( "CUsbDriver %08x\n", uint( this ) );
        pEventSink     = 0;
        pBoard         = 0;
        pEndpoints     = 0;
        dNumEndpoints  = 0;
        dState         = 0;
        useSOFCallback = false;
    }
Member Function Documentation
void USB::CUsbDriver::SetState (uint flags) [inline, protected]
Set flag(s) in dStatus register.
Definition at line 792 of file usbFramework.hpp.
References dState.
Referenced by CUdpDriver::Attach(), CUdpDriver::EventHandler(), CUdpDriver::Init(), CUdpDriver::SetAddress(), and CUdpDriver::SetConfiguration().
    {
        dState |= flags;
    }
void USB::CUsbDriver::ClearState (uint flags = 0xFFFF) [inline, protected]
Clear flag(s) in dStatus register. If the method is called without arguments, it will set dState to 0.
Definition at line 800 of file usbFramework.hpp.
References dState.
Referenced by CUdpDriver::Attach(), CUdpDriver::Disconnect(), CUdpDriver::EventHandler(), CUdpDriver::Init(), CUdpDriver::SetAddress(), and CUdpDriver::SetConfiguration().
    {
        dState &= ~flags;
    }
virtual void* USB::CUsbDriver::GetInterface (void) [pure virtual]
USB API Methods.
Methods provided by the USB API to manipulate a USB driver. Returns a pointer to the UDP controller interface used by an USB driver. The pointer is cast to the correct type (AT91PS_UDP).
Implemented in CUdpDriver.
virtual uint USB::CUsbDriver::GetDriverID (void) [pure virtual]
Returns the USB controller peripheral ID of a CUsbDriver instance.
Returns:
USB controller peripheral ID
Implemented in CUdpDriver.
Referenced by anonymous_namespace{usbCallbacks.cpp}::CCallbacks::OnInit().
virtual void USB::CUsbDriver::Init (void) [pure virtual]
Initializes the USB API and the USB controller.
This method must be called prior to using an other USB method. Before finishing, it invokes the CEventSink::OnInit callback.
See also:
CEventSink::OnInit
Implemented in CUdpDriver.
Referenced by USB::CSTD::Init().
virtual EnumStandardReturnValue USB::CUsbDriver::Write (int bEndpoint, const void * pData, uint dLength, Callback_f fCallback = 0, void * pArgument = 0, const void * pDataLowerBound = 0, const void * pDataUpperBound = 0) [pure virtual]
Sends data through an USB endpoint.
This method sends the specified amount of data through a particular endpoint. The transfer finishes either when the data has been completely sent, or an abnormal condition causes the API to abort this operation. An optional user-provided callback can be invoked once the transfer is complete. On control endpoints, this function automatically send a Zero-Length Packet (ZLP) if the data payload size is a multiple of the endpoint maximum packet size. This is not the case for bulk, interrupt or isochronous endpoints.
Parameters:
bEndpoint Number of the endpoint through which to send the data
pData Pointer to a buffer containing the data to send
dLength Size of the data buffer
fCallback Callback function to invoke when the transfer finishes
pArgument Optional parameter to pass to the callback function
pDataLowerBound Lower bound of the circular buffer
pDataUpperBound Upper bound of the circular buffer
Returns:
Result of operation
See also:
EnumStandardReturnValue
Implemented in CUdpDriver.
Referenced by USB::CSTD::GetConfiguration(), USB::CSTD::GetConfigurationDescriptor(), USB::CSTD::GetDeviceDescriptor(), USB::CSTD::GetDeviceStatus(), USB::CSTD::GetEndpointStatus(), USB::CSTD::GetStringDescriptor(), USB::CCDC::RequestHandler(), SendZLP0(), and USB::CCDC::Write().
virtual EnumStandardReturnValue USB::CUsbDriver::Read (int bEndpoint, void * pData, uint dLength, Callback_f fCallback = 0, void * pArgument = 0) [pure virtual]
Receives data on the specified USB endpoint.
This functions receives data on a particular endpoint. It finishes either when the provided buffer is full, when a short packet (payload size inferior to the endpoint maximum packet size) is received, or if an abnormal condition causes a transfer abort. An optional user-provided callback can be invoked upon the transfer completion
Parameters:
bEndpoint Number of the endpoint on which to receive the data
pData Pointer to the buffer in which to store the received data
dLength Size of the receive buffer
fCallback Optional user-provided callback function invoked upon the transfer completion
pArgument Optional parameter to pass to the callback function
Returns:
Result of operation
See also:
EnumStandardReturnValue
Implemented in CUdpDriver.
Referenced by USB::CCDC::Read(), and USB::CCDC::RequestHandler().
virtual EnumStandardReturnValue USB::CUsbDriver::Stall (int bEndpoint = 0) [pure virtual]
Sends a STALL handshake for the next received packet.
This function only send one STALL handshake, and only if the next packet is not a SETUP packet (when using this function on a control endpoint).
Parameters:
bEndpoint Number of endpoint on which to send the STALL
Returns:
Result of operation
See also:
EnumStandardReturnValue
CUsbDriver::Halt
Implemented in CUdpDriver.
Referenced by USB::CSTD::RequestHandler().
virtual bool USB::CUsbDriver::Halt (int bEndpoint, int bRequest) [pure virtual]
Clears, sets or retrieves the halt state of the specified endpoint.
While an endpoint is in Halt state, it acknowledges every received packet with a STALL handshake.
Parameters:
bEndpoint Number of the endpoint to alter
bRequest The operation to perform (set, clear or get)
Returns:
true if the endpoint is halted, false otherwise
Implemented in CUdpDriver.
Referenced by USB::CSTD::GetEndpointStatus(), and USB::CSTD::RequestHandler().
virtual void USB::CUsbDriver::RemoteWakeUp (void) [pure virtual]
Starts a remote wakeup procedure.
Implemented in CUdpDriver.
virtual bool USB::CUsbDriver::ConfigureEndpoint (const S_usb_endpoint_descriptor * pEpDesc) [pure virtual]
Configures the specified endpoint using the provided endpoint descriptor.
An endpoint must be configured prior to being used. This is not necessary for control endpoint 0, as this operation is automatically performed during initialization.
Parameters:
pEpDesc Pointer to an endpoint descriptor
Returns:
true if the endpoint has been configured, false otherwise
See also:
S_usb_endpoint_descriptor
Implemented in CUdpDriver.
Referenced by USB::CSTD::ConfigureEndpoints().
virtual bool USB::CUsbDriver::Attach (void) [pure virtual]
Handles the attachment or detachment of the device to or from the USB.
This method should be called whenever the VBus power line changes state, i.e. the device becomes powered/unpowered. Alternatively, it can also be called to poll the status of the device. When the device is detached from the bus, the CEventSink::OnSuspend callback is invoked. Conversely, when the device is attached, the CEventSink::OnResume callback is triggered.
Returns:
true if the device is currently attached, false otherwise
See also:
CEventSink::OnSuspend
CEventSink::OnResume
usb_api_callbacks
Implemented in CUdpDriver.
Referenced by USB::CSTD::Attach(), and anonymous_namespace{usbCallbacks.cpp}::CCallbacks::OnInit().
virtual void USB::CUsbDriver::SetAddress (void) [pure virtual]
Sets the device address using the last received SETUP packet.
This method must only be called after a SET_ADDRESS standard request has been received. This is because it uses the last received SETUP packet stored in the sSetup structure to determine which address the device should use.
See also:
EnumStandardDeviceRequests
Implemented in CUdpDriver.
Referenced by USB::CSTD::OnSetAddress().
virtual void USB::CUsbDriver::SetConfiguration (void) [pure virtual]
Sets the device configuration using the last received SETUP packet.
This method must only be called after a SET_CONFIGURATION standard request has been received. This is necessary because it uses the last received SETUP packet (stored in the sSetup structure) to determine which configuration it should adopt.
See also:
EnumStandardDeviceRequests
Implemented in CUdpDriver.
Referenced by USB::CSTD::ConfigureEndpoints().
virtual void USB::CUsbDriver::EventHandler (void) [pure virtual]
Event handler for the USB controller peripheral.
This function handles low-level events comming from the USB controller peripheral. It then dispatches those events through the user-provided callbacks. The following callbacks can be triggered:
CEventSink::OnReset
CEventSink::OnSuspend
CEventSink::OnResume
CEventSink::OnNewRequest
See also:
usb_api_callbacks
Implemented in CUdpDriver.
Referenced by USB::CSTD::EventHandler().
virtual void USB::CUsbDriver::Connect (void) [pure virtual]
Connects the device to the USB.
This method enables the pull-up resistor on the D+ line, notifying the host that the device wishes to connect to the bus.
See also:
CUsbDriver::Disconnect
Implemented in CUdpDriver.
Referenced by USB::CSTD::Connect().
virtual void USB::CUsbDriver::Disconnect (void) [pure virtual]
Disconnects the device from the USB. This method disables the pull-up resistor on the D+ line, notifying the host that the device wishes to disconnect from the bus.
See also:
CUsbDriver::Connect
Implemented in CUdpDriver.
void USB::CUsbDriver::LinkTo (CEventSink * pArgEventSink, CBoard * pArgBoard) [inline]
Link device driver to CEventSink instance so CUsbDriver methods could send callbacks properly.
Returns:
Pointer to the CEventSink instance
Definition at line 998 of file usbFramework.hpp.
References pBoard, and pEventSink.
Referenced by USB::CSTD::CSTD().
    {
        pEventSink = pArgEventSink;
        pBoard = pArgBoard;
    }
S_usb_request* USB::CUsbDriver::GetSetup (void) [inline]
Returns a pointer to the last received SETUP request.
Returns:
Pointer to the last received SETUP request
Definition at line 1008 of file usbFramework.hpp.
References sSetup.
Referenced by USB::CSTD::RequestHandler(), and USB::CCDC::RequestHandler().
    {
        return &sSetup;
    }
bool USB::CUsbDriver::IsStateSet (uint flags) const [inline]
Poll the status of flags in dStatus register.
Returns:
bool true if flag(s) is/are set
Definition at line 1017 of file usbFramework.hpp.
References dState.
Referenced by CUdpDriver::Attach(), CUdpDriver::EventHandler(), USB::CSTD::GetConfiguration(), and USB::CSTD::IsPowered().
    {
        return ( dState & flags ) == flags;
    }
bool USB::CUsbDriver::IsStateCleared (uint flags) const [inline]
Poll the status of flag(s) in dStatus register.
Returns:
bool true if flag(s) is/are cleared
Definition at line 1026 of file usbFramework.hpp.
References dState.
    {
        return ( dState & flags ) == 0;
    }
int USB::CUsbDriver::GetNumEndpoints (void) const [inline]
Returns a number of configured endpoints.
Returns:
uint number of configured endpoints
Definition at line 1035 of file usbFramework.hpp.
References dNumEndpoints.
Referenced by USB::CSTD::ConfigureEndpoints().
    {
        return dNumEndpoints;
    }
void USB::CUsbDriver::SetEndpointList (CEndpoint * list, int count) [inline]
Establish the list of configured endpoints.
Definition at line 1043 of file usbFramework.hpp.
References dNumEndpoints, and pEndpoints.
Referenced by USB::CCDC::CCDC().
    {
        pEndpoints     = list;
        dNumEndpoints  = count;
    }
EnumStandardReturnValue USB::CUsbDriver::SendZLP0 (Callback_f fCallback = 0, void * pArgument = 0) [inline]
Sends a Zero-Length Packet (ZLP) through the Control endpoint 0.
Since sending a ZLP on endpoint 0 is quite common, this function is provided as an overload to the CUsbDriver::Write function.
Parameters:
fCallback Optional callback function to invoke when the transfer finishes
pArgument Optional parameter to pass to the callback function
Returns:
Result of operation
See also:
EnumStandardReturnValue
Definition at line 1059 of file usbFramework.hpp.
References Write().
Referenced by USB::CCDC::OnSetLineCoding(), USB::CSTD::RequestHandler(), USB::CCDC::RequestHandler(), and USB::CSTD::SetConfiguration().
    {
        return Write( 0, 0, 0, fCallback, pArgument );
    }
Member Data Documentation
CEventSink* USB::CUsbDriver::pEventSink [protected]
Pointer to associated CEventSink instance.
Definition at line 766 of file usbFramework.hpp.
Referenced by CUdpDriver::Attach(), CUsbDriver(), CUdpDriver::EndpointHandler(), CUdpDriver::EventHandler(), CUdpDriver::Init(), and LinkTo().
CBoard* USB::CUsbDriver::pBoard [protected]
Pointer to associated CBoard instance.
Definition at line 767 of file usbFramework.hpp.
Referenced by CUdpDriver::Attach(), CUdpDriver::Connect(), CUsbDriver(), CUdpDriver::Disconnect(), CUdpDriver::Init(), and LinkTo().
CEndpoint* USB::CUsbDriver::pEndpoints [protected]
Endpoints list.
Definition at line 768 of file usbFramework.hpp.
Referenced by CUdpDriver::ClearRXFlag(), CUdpDriver::ConfigureEndpoint(), CUsbDriver(), CUdpDriver::DisableEndpoints(), CUdpDriver::EndpointHandler(), CUdpDriver::GetPayload(), CUdpDriver::Halt(), CUdpDriver::Init(), CUdpDriver::Read(), CUdpDriver::ResetEndpoints(), SetEndpointList(), CUdpDriver::Stall(), CUdpDriver::Write(), and CUdpDriver::WritePayload().
int USB::CUsbDriver::dNumEndpoints [protected]
Number of endpoints in list.
Definition at line 769 of file usbFramework.hpp.
Referenced by CUdpDriver::ConfigureEndpoint(), CUsbDriver(), CUdpDriver::DisableEndpoints(), GetNumEndpoints(), CUdpDriver::Init(), CUdpDriver::ResetEndpoints(), and SetEndpointList().
S_usb_request USB::CUsbDriver::sSetup [protected]
Pointer to the last received SETUP packet.
Definition at line 770 of file usbFramework.hpp.
Referenced by CUdpDriver::EndpointHandler(), GetSetup(), CUdpDriver::SetAddress(), and CUdpDriver::SetConfiguration().
volatile uint USB::CUsbDriver::dState [protected]
Current state of the device.
Definition at line 771 of file usbFramework.hpp.
Referenced by ClearState(), CUsbDriver(), IsStateCleared(), IsStateSet(), and SetState().
bool USB::CUsbDriver::useSOFCallback [protected]
Indicates wether to forward StartOfFrame events.
Definition at line 772 of file usbFramework.hpp.
Referenced by CUsbDriver(), and CUdpDriver::EventHandler().
The documentation for this class was generated from the following file:
src/inc/usbFramework.hpp