XPU-DSAM7S: USBXMTR Class Reference
USBXMTR Class Reference
#include <sam7xpud.hpp>
Public Member Functions
USBXMTR (void)
void Initialize (void)
void LockWrite (void)
void UnlockWrite (void)
bool Put (void *data, uint len, portTickType xTicksToWait)
void Transmitter (void)
Static Public Member Functions
static portTASK_FUNCTION (MainTask, pvParameters)
Static Private Member Functions
static void OnSendCompleted (USBXMTR *pThis, uchar bStatus, uint dBytesTransferred, uint dBytesRemaining)
Private Attributes
xMUTEX semaMutex
xSEMA semaFull
xSEMA semaEmpty
xSEMA semaSent
uchar buf [USB_XMTR_BUF_SIZE]
uint bufSize
uchar * pRead
uchar * pWrite
uchar * pMax
volatile int bStatus
volatile uint dBytesTransferred
volatile uint dBytesRemaining
Detailed Description
Definition at line 70 of file sam7xpud.hpp.
Constructor & Destructor Documentation
USBXMTR::USBXMTR (void) [inline]
Definition at line 118 of file sam7xpud.hpp.
References buf, bufSize, pMax, pRead, pWrite, and USB_XMTR_BUF_SIZE.
        : semaFull( USB_XMTR_BUF_SIZE )
        , semaEmpty( 0 )
        , semaSent( 0 )
    {
        bufSize = USB_XMTR_BUF_SIZE;
        pRead   = buf;
        pWrite  = buf;
        pMax    = buf + bufSize;
        }
Member Function Documentation
static void USBXMTR::OnSendCompleted (USBXMTR * pThis, uchar bStatus, uint dBytesTransferred, uint dBytesRemaining) [inline, static, private]
Definition at line 99 of file sam7xpud.hpp.
References bStatus, dBytesRemaining, dBytesTransferred, isTaskWokenByPostInUsbIrq, xSEMA::ReleaseFromISR(), and semaSent.
Referenced by Transmitter().
    {
        pThis->bStatus = bStatus;
        pThis->dBytesTransferred = dBytesTransferred;
        pThis->dBytesRemaining = dBytesRemaining;
        if ( pThis->semaSent.ReleaseFromISR( 1, isTaskWokenByPostInUsbIrq ) )
        {
            isTaskWokenByPostInUsbIrq = pdTRUE;
            }
        }
void USBXMTR::Initialize (void) [inline]
Definition at line 129 of file sam7xpud.hpp.
References bufSize, and TRACE_INFO.
Referenced by portTASK_FUNCTION().
    {
#ifdef TR_INFO
        taskENTER_CRITICAL ();
        TRACE_INFO( "USBXMTR: Initialize(): Size=%u\n", bufSize );
        taskEXIT_CRITICAL ();
#endif
        }
void USBXMTR::LockWrite (void) [inline]
Definition at line 138 of file sam7xpud.hpp.
References xMUTEX::Lock(), and semaMutex.
Referenced by Put().
    {
        // Lock pWrite mutex
        //
        do ; while( ! semaMutex.Lock( 100 ) );
        }
void USBXMTR::UnlockWrite (void) [inline]
Definition at line 145 of file sam7xpud.hpp.
References semaMutex, and xMUTEX::Unlock().
Referenced by Put().
    {
        // Unlock pWrite mutex
        //
        semaMutex.Unlock ();
        }
bool USBXMTR::Put (void * data, uint len, portTickType xTicksToWait)
Definition at line 58 of file usbTasks.cpp.
References buf, LockWrite(), pMax, pWrite, xSEMA::Release(), semaEmpty, semaFull, UnlockWrite(), and xSEMA::Wait().
Referenced by XSVF_Player::Enable(), XPI::InitializeFPGA(), XSVF_Player::MainLoop(), XPI::On_CRX(), XPI::On_CTX(), XPI::On_EIRQ(), XPI::On_FC(), XPI::Put(), USBRCVR::Receiver(), XPI::ResetFPGA(), XPI::Transmitter(), and usb_putc().
{
    // Wait enough space to fit 2-byte length + data
    //
    if ( ! semaFull.Wait( len + 2, xTicksToWait ) )
        return false;
    // Lock pWrite mutex
    //
    LockWrite ();
    // Put 2-byte length into circular buffer: MSB first
    //
    *pWrite++ = ( len >> 8 ) & 0xFF;
    if ( pWrite >= pMax )
        pWrite = buf;
    *pWrite++ = len & 0xFF;
    if ( pWrite >= pMax )
        pWrite = buf;
    // Put data into circular buffer
    //
    uchar* pSrc = (uchar*) data;
    if ( pWrite + len < pMax )
    {
        // Put flat data (not crossing upper boundary)
        //
        for( uint i = 0; i < len; i++ )
            *pWrite++ = *pSrc++;
        }
    else
    {
        // Put circular data (crossing upper boundary)
        //
        uint len2 = pWrite + len - pMax;
        uint len1 = len - len2;
        for( uint i = 0; i < len1; i++ )
            *pWrite++ = *pSrc++;
        pWrite = buf;
        for( uint i = 0; i < len2; i++ )
            *pWrite++ = *pSrc++;
        }
    // Notify Transmitter()
    //
    semaEmpty.Release( len + 2 );
    // Unlock pWrite mutex
    //
    UnlockWrite ();
    return true;
    }
void USBXMTR::Transmitter (void)
Definition at line 116 of file usbTasks.cpp.
References bStatus, buf, bufSize, dBytesRemaining, dBytesTransferred, OnSendCompleted(), pMax, pRead, xSEMA::Release(), semaEmpty, semaFull, semaSent, sSer, TRACE_DEBUG_M, TRACE_ERROR, USB::USB_STATUS_SUCCESS, xSEMA::Wait(), and USB::CCDC::Write().
Referenced by portTASK_FUNCTION().
{
    // Wait 2-byte header
    //
    do ; while( ! semaEmpty.Wait( 2, 1000 ) );
    // Retrieve data length from packet header
    //
    uint len = *pRead++;
    if ( pRead >= pMax )
        pRead = buf;
    len = ( len << 8 ) + *pRead++;
    if ( pRead >= pMax )
        pRead = buf;
    // Wait the rest of data
    //
    do ; while( ! semaEmpty.Wait( len, 1000 ) );
    // Send data over USB
    //
    bool isSent = false;
    for ( int i = 0; i < 100; i++ )
    {
        taskENTER_CRITICAL ();
        int rc = sSer.Write( pRead, len, Callback_f( OnSendCompleted ), this, buf, pMax );
        taskEXIT_CRITICAL ();
        if ( rc == USB::USB_STATUS_SUCCESS )
        {
            isSent = true;
            break;
            }
        // USB endopoint is not ready; wait and retry
        //
        vTaskDelay( 1 );
        if ( i == 0 )
        {
#ifdef TR_ERROR
            taskENTER_CRITICAL ();
            TRACE_ERROR( "USBXMTR: Write failed\n" );
            taskEXIT_CRITICAL ();
#endif
            }
        }
    // Wait for transmission to end
    //
    if ( isSent )
    {
        do ; while( ! semaSent.Wait( 1, 1000 ) );
        if ( bStatus != USB::USB_STATUS_SUCCESS )
        {
#ifdef TR_ERROR
            taskENTER_CRITICAL ();
            TRACE_ERROR( "USBXMTR: Transfer error\n" );
            taskEXIT_CRITICAL ();
#endif
            }
        else
        {
#ifdef TR_DEBUG_M
            taskENTER_CRITICAL ();
            TRACE_DEBUG_M( "USBXMTR: Sent %5u, %5u; RC = %d\n",
                    dBytesTransferred, dBytesRemaining, bStatus );
            taskEXIT_CRITICAL ();
#endif
            }
        }
    // Advance pRead
    //
    pRead += len;
    if ( pRead >= pMax )
        pRead -= bufSize;
    // Release space back to circular buffer and unblock some USBXMTR::Put
    // waiting for more space.
    //
    semaFull.Release( len + 2 );
    }
static USBXMTR::portTASK_FUNCTION (MainTask , pvParameters) [static]
Member Data Documentation
xMUTEX USBXMTR::semaMutex [private]
Definition at line 72 of file sam7xpud.hpp.
Referenced by LockWrite(), and UnlockWrite().
xSEMA USBXMTR::semaFull [private]
Definition at line 73 of file sam7xpud.hpp.
Referenced by Put(), and Transmitter().
xSEMA USBXMTR::semaEmpty [private]
Definition at line 74 of file sam7xpud.hpp.
Referenced by Put(), and Transmitter().
xSEMA USBXMTR::semaSent [private]
Definition at line 75 of file sam7xpud.hpp.
Referenced by OnSendCompleted(), and Transmitter().
uchar USBXMTR::buf[USB_XMTR_BUF_SIZE] [private]
Definition at line 86 of file sam7xpud.hpp.
Referenced by Put(), Transmitter(), and USBXMTR().
uint USBXMTR::bufSize [private]
Definition at line 87 of file sam7xpud.hpp.
Referenced by Initialize(), Transmitter(), and USBXMTR().
uchar* USBXMTR::pRead [private]
Definition at line 89 of file sam7xpud.hpp.
Referenced by Transmitter(), and USBXMTR().
uchar* USBXMTR::pWrite [private]
Definition at line 90 of file sam7xpud.hpp.
Referenced by Put(), and USBXMTR().
uchar* USBXMTR::pMax [private]
Definition at line 91 of file sam7xpud.hpp.
Referenced by Put(), Transmitter(), and USBXMTR().
volatile int USBXMTR::bStatus [private]
Definition at line 94 of file sam7xpud.hpp.
Referenced by OnSendCompleted(), and Transmitter().
volatile uint USBXMTR::dBytesTransferred [private]
Definition at line 95 of file sam7xpud.hpp.
Referenced by OnSendCompleted(), and Transmitter().
volatile uint USBXMTR::dBytesRemaining [private]
Definition at line 96 of file sam7xpud.hpp.
Referenced by OnSendCompleted(), and Transmitter().
The documentation for this class was generated from the following files:
src/inc/sam7xpud.hpp
src/usbTasks.cpp