XPU-DSAM7S: xMUTEX Class Reference
xMUTEX Class Reference
#include <sema.hpp>
Public Member Functions
xMUTEX (void)
bool Lock (const portTickType waitTicks)
void Unlock (void)
Detailed Description
Definition at line 151 of file sema.hpp.
Constructor & Destructor Documentation
xMUTEX::xMUTEX (void) [inline]
Definition at line 155 of file sema.hpp.
References xSEMA::isMutex.
        : xSEMA( 1 )
    {
        isMutex = true;
    }
Member Function Documentation
bool xMUTEX::Lock (const portTickType waitTicks) [inline]
Definition at line 161 of file sema.hpp.
References xSEMA::Wait().
Referenced by XPI::LockWrite(), and USBXMTR::LockWrite().
    {
        return Wait( 1, waitTicks );
    }
void xMUTEX::Unlock (void) [inline]
Reimplemented from xSEMA.
Definition at line 166 of file sema.hpp.
References xSEMA::Release().
Referenced by XPI::UnlockWrite(), and USBXMTR::UnlockWrite().
    {
        Release( 1 );
    }
The documentation for this class was generated from the following file:
src/inc/sema.hpp