XPU-DSAM7S: XSVF_Player Class Reference
XSVF_Player Class Reference
#include <sam7xpud.hpp>
Public Member Functions
XSVF_Player (void)
void Enable (int trace_level, bool parse_only)
int GetLastRC (void) const
int getc (void)
void LockBuffer (uchar *buf, uint len)
Static Public Member Functions
static portTASK_FUNCTION (MainTask, pvParameters)
Private Member Functions
void CRC16 (uchar ser_data)
void MainLoop (void)
Private Attributes
bool enabled
xSEMA semaFull
xSEMA semaEmpty
volatile uchar * datap
volatile uint datac
volatile int firstByte
int traceLevel
bool parseOnly
uint crc
uint byteCount
int xsvfRC
XPI_LONG_MSG sMsg
Detailed Description
Definition at line 280 of file sam7xpud.hpp.
Constructor & Destructor Documentation
XSVF_Player::XSVF_Player (void) [inline]
Definition at line 315 of file sam7xpud.hpp.
References datac, datap, enabled, firstByte, parseOnly, traceLevel, and xsvfRC.
        : semaFull( 0 )
        , semaEmpty( 0 )
    {
        enabled    = false;
        xsvfRC     = -1; // undefined error
        datap      = NULL;
        datac      = 0;
        firstByte  = -1;
        traceLevel = 0;
        parseOnly  = false;
        }
Member Function Documentation
void XSVF_Player::CRC16 (uchar ser_data) [inline, private]
Definition at line 300 of file sam7xpud.hpp.
References byteCount, and crc.
Referenced by getc().
    {
        crc  = uchar( crc >> 8 ) | ( crc << 8 );
        crc ^= ser_data;
        crc ^= uchar( crc & 0xff ) >> 4;
        crc ^= ( crc << 8 ) << 4;
        crc ^= ( ( crc & 0xFF ) << 4 ) << 1;
        ++byteCount;
        }
void XSVF_Player::MainLoop (void) [private]
Definition at line 35 of file xsvfTask.cpp.
References byteCount, crc, XPI_LONG_MSG::data, datac, datap, dTimerTick, enabled, firstByte, getc(), XPI_IMSG_HEADER::magicLSB, XPI_IMSG_HEADER::magicMSB, parseOnly, USBXMTR::Put(), xSEMA::Release(), semaEmpty, sMsg, XPI_IMSG_HEADER::subtype, XPI_IMSG_HEADER::timeStamp, TRACE_INFO, traceLevel, XPI_IMSG_HEADER::type, usbOut, XPI_IMSG_XSVF_END, XPI_MSG_MAGIC_LSB, XPI_MSG_MAGIC_MSB, xsvfExecute(), and xsvfRC.
Referenced by portTASK_FUNCTION().
{
#ifdef TR_INFO
    taskENTER_CRITICAL ();
    TRACE_INFO( "XSVF_Player Task\n" );
    taskEXIT_CRITICAL ();
#endif
    // Peek first XSVF byte and loop while it is EOF.
    // Note that xXsvfFirstByte byte will be later reused by the ReadXSVF()
    // when ReadXSVF() is called by xsvfExecute().
    //
    do firstByte = getc ();
        while( firstByte < 0 );
#ifdef TR_INFO
    taskENTER_CRITICAL ();
    TRACE_INFO( "Starting XSVF player (XSVF data peek 0x%02X)\n", firstByte );
    // TRACE_INFO( "Datap = %08X, Datac = %u\n", uint( datap ), datac );
    taskEXIT_CRITICAL ();
#endif
    // Reset CRC and byte count
    //
    crc = 0;
    byteCount = 0;
    // Elapsed time
    ulong dTimerStart = dTimerTick;
    // Start XSVF player
    //
    xsvfRC = xsvfExecute( traceLevel, parseOnly );
    long dElapsed = dTimerTick - dTimerStart;
    // Normalize CRC
    //
    crc &= 0xFFFF;
    // Signal that we have ended
    //
    sMsg.timeStamp = dTimerTick;
    sMsg.magicMSB  = XPI_MSG_MAGIC_MSB;
    sMsg.magicLSB  = XPI_MSG_MAGIC_LSB;
    sMsg.type      = XPI_IMSG_XSVF_END;
    sMsg.subtype   = 0;
    sMsg.data[0]   = xsvfRC;
    sMsg.data[1]   = ( crc >> 8 ) & 0xFF;
    sMsg.data[2]   = crc & 0xFF;
    sMsg.data[3]   = ( byteCount >>  24 ) & 0xFF;
    sMsg.data[4]   = ( byteCount >>  16 ) & 0xFF;
    sMsg.data[5]   = ( byteCount >>   8 ) & 0xFF;
    sMsg.data[6]   = ( byteCount >>   0 ) & 0xFF;
    sMsg.data[7]   = ( dElapsed >>  24 ) & 0xFF;
    sMsg.data[8]   = ( dElapsed >>  16 ) & 0xFF;
    sMsg.data[9]   = ( dElapsed >>   8 ) & 0xFF;
    sMsg.data[10]  = ( dElapsed >>   0 ) & 0xFF;
    usbOut.Put( NULL, 0, 1000 ); // Terminate previous message
    usbOut.Put( &sMsg, sizeof( XPI_IMSG_HEADER ) + 11, 1000 ); // Send this message
#ifdef TR_INFO
    taskENTER_CRITICAL ();
    TRACE_INFO( "XSVF completed; Bytes = %u, CRC16 = 0x%04X, Elapsed = %ld\n",
                byteCount, crc, dElapsed );
    taskEXIT_CRITICAL ();
#endif
    // CLEANUP:
    // Make xXsvfQueue empty
    //
    if ( datac != 0 )
    {
        datac = 0;
        semaEmpty.Release( 1 );
        }
    datap = NULL;
    firstByte = -1;
    // Mark player disabled
    //
    enabled = false;
    }
void XSVF_Player::Enable (int trace_level, bool parse_only)
Definition at line 125 of file xsvfTask.cpp.
References enabled, parseOnly, USBXMTR::Put(), XPI::ResetFPGA(), traceLevel, usbOut, and xpi.
Referenced by USBRCVR::Receiver().
{
    if ( enabled )
        return; // TODO: restart?
    // Reset FPGA
    //
    xpi.ResetFPGA ();
    // Configure parameters
    //
    traceLevel = trace_level;
    parseOnly  = parse_only;
    // Send end-of-transfer packet (flush usbOut)
    //
    usbOut.Put( NULL, 0, 1000 );
    // Start player
    //
    enabled = true;
    }
int XSVF_Player::GetLastRC (void) const [inline]
Definition at line 330 of file sam7xpud.hpp.
References enabled, and xsvfRC.
Referenced by XPI::DumpStatus(), XPI::InitializeFPGA(), and XPI::ResetFPGA().
    {
        return enabled ? -1 : xsvfRC;
        }
int XSVF_Player::getc (void) [inline]
Definition at line 335 of file sam7xpud.hpp.
References CRC16(), datac, datap, firstByte, xSEMA::Release(), semaEmpty, semaFull, and xSEMA::Wait().
Referenced by MainLoop(), and ReadXSVF().
    {
        uchar data;
        // Emit first byte that was previously peek by the player
        //
        if ( firstByte >= 0 )
        {
            data = firstByte;
            firstByte = -1;
            CRC16( data );
            return data;
            }
        // Get next XSVF data. Consider end of XSVF stream on timeout.
        //
        if ( datac == 0 )
        {
            if ( ! semaFull.Wait( 1, 2000 ) )
                return -1;
            if ( datac == 0 )
                return -1;
            }
        data = *datap++;
        --datac;
        if ( datac == 0 )
        {
            datap = NULL;
            semaEmpty.Release( 1 );
            }
        CRC16( data );
        return data;
        }
void XSVF_Player::LockBuffer (uchar * buf, uint len) [inline]
Definition at line 373 of file sam7xpud.hpp.
References datac, datap, enabled, xSEMA::Release(), semaEmpty, semaFull, and xSEMA::Wait().
Referenced by USBRCVR::Receiver().
    {
        if ( ! enabled )
            return; // ignore if not enabled
        datap = buf;
        datac = len;
        semaFull.Release( 1 );
        do ; while( ! semaEmpty.Wait( 1, 100 ) );
        }
static XSVF_Player::portTASK_FUNCTION (MainTask , pvParameters) [static]
Member Data Documentation
bool XSVF_Player::enabled [private]
Definition at line 282 of file sam7xpud.hpp.
Referenced by Enable(), GetLastRC(), LockBuffer(), MainLoop(), and XSVF_Player().
xSEMA XSVF_Player::semaFull [private]
Definition at line 284 of file sam7xpud.hpp.
Referenced by getc(), and LockBuffer().
xSEMA XSVF_Player::semaEmpty [private]
Definition at line 285 of file sam7xpud.hpp.
Referenced by getc(), LockBuffer(), and MainLoop().
volatile uchar* XSVF_Player::datap [private]
Definition at line 286 of file sam7xpud.hpp.
Referenced by getc(), LockBuffer(), MainLoop(), and XSVF_Player().
volatile uint XSVF_Player::datac [private]
Definition at line 287 of file sam7xpud.hpp.
Referenced by getc(), LockBuffer(), MainLoop(), and XSVF_Player().
volatile int XSVF_Player::firstByte [private]
Definition at line 288 of file sam7xpud.hpp.
Referenced by getc(), MainLoop(), and XSVF_Player().
int XSVF_Player::traceLevel [private]
Definition at line 289 of file sam7xpud.hpp.
Referenced by Enable(), MainLoop(), and XSVF_Player().
bool XSVF_Player::parseOnly [private]
Definition at line 290 of file sam7xpud.hpp.
Referenced by Enable(), MainLoop(), and XSVF_Player().
uint XSVF_Player::crc [private]
Definition at line 291 of file sam7xpud.hpp.
Referenced by CRC16(), and MainLoop().
uint XSVF_Player::byteCount [private]
Definition at line 292 of file sam7xpud.hpp.
Referenced by CRC16(), and MainLoop().
int XSVF_Player::xsvfRC [private]
Definition at line 293 of file sam7xpud.hpp.
Referenced by GetLastRC(), MainLoop(), and XSVF_Player().
XPI_LONG_MSG XSVF_Player::sMsg [private]
Definition at line 295 of file sam7xpud.hpp.
Referenced by MainLoop().
The documentation for this class was generated from the following files:
src/inc/sam7xpud.hpp
src/fpga/xsvfTask.cpp