XPU-DSAM7S: USB::CSTD Class Reference
USB::CSTD Class Reference
USB standard class driver structure.
#include <usbFramework.hpp>
Public Member Functions
void EventHandler (void)
Low-level usb driver interrupt handler.
void Init (void)
Initializes the USB API and the USB controller.
bool IsPowered (void) const
Return true if device is powered.
void Connect (void)
Connect to device.
void Attach (void)
Attach device to USB bus.
Protected Member Functions
virtual void RequestHandler (void)
Handles standard SETUP requests.
CSTD (CUsbDriver *usbDriver, CBoard *board, CEventSink *eventSink)
Constructor. Connects object to CUsbDriver instance.
Protected Attributes
CUsbDriver * pDriver
Pointer to usb driver instance.
const S_std_descriptors * pDescriptors
ushort wDeviceStatus
ushort wData
Private Types
enum { SELF_POWERED = (1 << 0), REMOTE_WAKEUP = (1 << 1) }
Private Member Functions
void ConfigureEndpoints (void)
Configures the device and the endpoints.
void SetConfiguration (int bConfiguration)
Sends a zero-length packet and starts the configuration procedure.
void GetConfiguration (void)
Sends the currently selected configuration to the host.
void GetDeviceStatus (void)
Sends the current device status to the host.
void GetEndpointStatus (int bEndpoint)
Sends the current status of specified endpoint to the host.
void GetDeviceDescriptor (ushort wLength)
Sends the device descriptor to the host.
void GetConfigurationDescriptor (ushort wLength)
Sends the configuration descriptor to the host.
void GetStringDescriptor (ushort wLength, int bIndex)
Sends the specified string descriptor to the host.
Static Private Member Functions
static void OnSetAddress (CSTD *pThis)
Callback for the SetAddress usb request.
static void OnConfigureEndpoints (CSTD *pThis)
Callback for the SetConfiguration usb request. Configures the device and the endpoints.
Detailed Description
USB standard class driver structure.
Used to provide standard driver information so external modules can still access an internal driver.
Definition at line 1096 of file usbFramework.hpp.
Member Enumeration Documentation
anonymous enum [private]
wDeviceStatus flags: Information Returned by a GetStatus() Request to a Device.
See also:
USB Specification 2.0 - Section 9.4.5 - Figure 9-4
Enumerator:
SELF_POWERED
REMOTE_WAKEUP
Definition at line 1102 of file usbFramework.hpp.
    {
        SELF_POWERED          = (1 << 0),
        REMOTE_WAKEUP         = (1 << 1)
    };
Constructor & Destructor Documentation
USB::CSTD::CSTD (CUsbDriver * usbDriver, CBoard * board, CEventSink * eventSink) [inline, protected]
Constructor. Connects object to CUsbDriver instance.
Note that this constructor is not public, which means that CSTD objects can not be instantiated. However, derived class objects could be instantiated normally.
Definition at line 1309 of file usbFramework.hpp.
References USB::CUsbDriver::LinkTo(), and pDriver.
    {
        pDriver = usbDriver;
        pDriver->LinkTo( eventSink, board );
    }
Member Function Documentation
static void USB::CSTD::OnSetAddress (CSTD * pThis) [inline, static, private]
Callback for the SetAddress usb request.
See also:
CSTD::RequestHandler
Definition at line 1125 of file usbFramework.hpp.
References pDriver, and USB::CUsbDriver::SetAddress().
Referenced by RequestHandler().
    {
        pThis->pDriver->SetAddress ();
    }
void USB::CSTD::ConfigureEndpoints (void) [inline, private]
Configures the device and the endpoints.
Definition at line 1133 of file usbFramework.hpp.
References USB::CUsbDriver::ConfigureEndpoint(), USB::CUsbDriver::GetNumEndpoints(), pDescriptors, pDriver, USB::S_std_descriptors::pEndpoints, and USB::CUsbDriver::SetConfiguration().
Referenced by OnConfigureEndpoints().
    {
        // Enter the Configured state
        //
        pDriver->SetConfiguration ();
        // Configure endpoints
        // TODO: Why this works for GetNumEndpoints()-1 and not
        // for GetNumEndpoints() when windows is getting out stand-by mode?
        //
        for ( int i = 0; i < pDriver->GetNumEndpoints () - 1; i++ )
        {
            pDriver->ConfigureEndpoint( pDescriptors->pEndpoints[ i ] );
        }
    }
static void USB::CSTD::OnConfigureEndpoints (CSTD * pThis) [inline, static, private]
Callback for the SetConfiguration usb request. Configures the device and the endpoints.
See also:
CSTD::SetConfiguration, CSTD::ConfigureEndpoints
Definition at line 1154 of file usbFramework.hpp.
References ConfigureEndpoints().
Referenced by SetConfiguration().
    {
        pThis->ConfigureEndpoints ();
    }
void USB::CSTD::SetConfiguration (int bConfiguration) [inline, private]
Sends a zero-length packet and starts the configuration procedure.
Parameters:
bConfiguration Newly selected configuration
Definition at line 1163 of file usbFramework.hpp.
References OnConfigureEndpoints(), pDriver, and USB::CUsbDriver::SendZLP0().
Referenced by RequestHandler().
    {
        pDriver->SendZLP0( Callback_f( OnConfigureEndpoints ), this );
    }
void USB::CSTD::GetConfiguration (void) [inline, private]
Sends the currently selected configuration to the host.
Definition at line 1171 of file usbFramework.hpp.
References USB::CUsbDriver::IsStateSet(), pDriver, USB::USB_STATE_CONFIGURED, wData, and USB::CUsbDriver::Write().
Referenced by RequestHandler().
    {
        wData = pDriver->IsStateSet( USB_STATE_CONFIGURED ) ? 1 : 0;
        pDriver->Write( 0, &wData, 1 );
    }
void USB::CSTD::GetDeviceStatus (void) [inline, private]
Sends the current device status to the host.
Definition at line 1180 of file usbFramework.hpp.
References USB::S_usb_configuration_descriptor::bmAttibutes, ISSET, USB::S_std_descriptors::pConfiguration, pDescriptors, pDriver, SELF_POWERED, USB::USB_CONFIG_SELF_POWERED, wDeviceStatus, and USB::CUsbDriver::Write().
Referenced by RequestHandler().
    {
        // Bus or self-powered ?
        //
        if ( ISSET( pDescriptors->pConfiguration->bmAttibutes, USB_CONFIG_SELF_POWERED ) )
        {
            wDeviceStatus |= SELF_POWERED;   // Self powered device
        }
        else
        {
            wDeviceStatus &= ~SELF_POWERED;  // Bus powered device
        }
        // Return the device status
        //
        pDriver->Write( 0, &wDeviceStatus, 2 );
    }
void USB::CSTD::GetEndpointStatus (int bEndpoint) [inline, private]
Sends the current status of specified endpoint to the host.
Parameters:
bEndpoint Endpoint number
Definition at line 1202 of file usbFramework.hpp.
References USB::CUsbDriver::Halt(), pDriver, USB::USB_GET_STATUS, wData, and USB::CUsbDriver::Write().
Referenced by RequestHandler().
    {
        // Retrieve the endpoint current status
        //
        wData = ushort( pDriver->Halt( bEndpoint, USB_GET_STATUS ) );
        // Return the endpoint status
        //
        pDriver->Write( 0, &wData, 2 );
    }
void USB::CSTD::GetDeviceDescriptor (ushort wLength) [inline, private]
Sends the device descriptor to the host.
The number of bytes actually sent depends on both the length requested by the host and the actual length of the descriptor.
Parameters:
wLength Number of bytes requested by the host
Definition at line 1219 of file usbFramework.hpp.
References min(), pDescriptors, USB::S_std_descriptors::pDevice, pDriver, and USB::CUsbDriver::Write().
Referenced by RequestHandler().
    {
        pDriver->Write
        (
            0, // endpoint
            pDescriptors->pDevice, // ptr to data
            min( sizeof(S_usb_device_descriptor), wLength ) // data length
            );
    }
void USB::CSTD::GetConfigurationDescriptor (ushort wLength) [inline, private]
Sends the configuration descriptor to the host.
The number of bytes actually sent depends on both the length requested by the host and the actual length of the descriptor.
Parameters:
wLength Number of bytes requested by the host
Definition at line 1235 of file usbFramework.hpp.
References min(), USB::S_std_descriptors::pConfiguration, pDescriptors, pDriver, USB::CUsbDriver::Write(), and USB::S_usb_configuration_descriptor::wTotalLength.
Referenced by RequestHandler().
    {
        pDriver->Write
        (
             0, // endpoint
             pDescriptors->pConfiguration, // ptr to data
             min( pDescriptors->pConfiguration->wTotalLength, wLength ) // data length
             );
    }
void USB::CSTD::GetStringDescriptor (ushort wLength, int bIndex) [inline, private]
Sends the specified string descriptor to the host.
The number of bytes actually sent depends on both the length requested by the host and the actual length of the descriptor.
Parameters:
wLength Number of bytes requested by the host
bIndex Index of requested string descriptor
Definition at line 1286 of file usbFramework.hpp.
References min(), pDescriptors, pDriver, USB::S_std_descriptors::pStrings, and USB::CUsbDriver::Write().
Referenced by RequestHandler().
    {
        pDriver->Write
        (
            0, // endpoint
            pDescriptors->pStrings[ bIndex ], // ptr to data
            min( *pDescriptors->pStrings[ bIndex ], wLength ) // data length
            );
    }
void CSTD::RequestHandler (void) [protected, virtual]
Handles standard SETUP requests.
Reimplemented in USB::CCDC.
Definition at line 19 of file usbSTD.cpp.
References USB::S_usb_request::bmRequestType, USB::S_usb_request::bRequest, GetConfiguration(), GetConfigurationDescriptor(), GetDeviceDescriptor(), GetDeviceStatus(), GetEndpointStatus(), USB::CUsbDriver::GetSetup(), GetStringDescriptor(), USB::CUsbDriver::Halt(), HBYTE, LBYTE, OnSetAddress(), pDriver, REMOTE_WAKEUP, USB::CUsbDriver::SendZLP0(), SetConfiguration(), USB::CUsbDriver::Stall(), TRACE_DEBUG_M, TRACE_WARNING, USB::USB_CLEAR_FEATURE, USB::USB_CONFIGURATION_DESCRIPTOR, USB::USB_DEVICE_DESCRIPTOR, USB::USB_DEVICE_QUALIFIER_DESCRIPTOR, USB::USB_DEVICE_REMOTE_WAKEUP, USB::USB_ENDPOINT_HALT, USB::USB_GET_CONFIGURATION, USB::USB_GET_DESCRIPTOR, USB::USB_GET_INTERFACE, USB::USB_GET_STATUS, USB::USB_OTHER_SPEED_CONFIGURATION_DESCRIPTOR, USB::USB_RECIPIENT_DEVICE, USB::USB_RECIPIENT_ENDPOINT, USB_REQUEST_RECIPIENT, USB::USB_SET_ADDRESS, USB::USB_SET_CONFIGURATION, USB::USB_SET_FEATURE, USB::USB_SET_INTERFACE, USB::USB_STRING_DESCRIPTOR, wDeviceStatus, USB::S_usb_request::wIndex, USB::S_usb_request::wLength, and USB::S_usb_request::wValue.
Referenced by USB::CCDC::RequestHandler().
{
    S_usb_request* pSetup = pDriver->GetSetup ();
    TRACE_DEBUG_M( "Std " );
    // Handle incoming request
    //
    switch( pSetup->bRequest )
    {
        //-------------------------------------------------------------------------------
        case USB_GET_DESCRIPTOR: // bRequest
        //-------------------------------------------------------------------------------
            TRACE_DEBUG_M( "gDesc " );
            // The HBYTE macro returns the upper byte of a word
            //
            switch( HBYTE( pSetup->wValue ) )
            {
                //-------------------------
                case USB_DEVICE_DESCRIPTOR:
                //-------------------------
                    TRACE_DEBUG_M( "Dev " );
                    GetDeviceDescriptor( pSetup->wLength );
                    break;
                //--------------------------------
                case USB_CONFIGURATION_DESCRIPTOR:
                //--------------------------------
                    TRACE_DEBUG_M( "Cfg " );
                    GetConfigurationDescriptor( pSetup->wLength );
                    break;
                //-----------------------------------
                case USB_DEVICE_QUALIFIER_DESCRIPTOR:
                //-----------------------------------
                    TRACE_DEBUG_M( "Qua " );
#if defined(HIGHSPEED)
                    GetQualifierDescriptor( pSetup->wLength );
#else
                    TRACE_DEBUG_M( "[not supported] " );
                    pDriver->Stall ();
#endif
                    break;
#if defined(HIGHSPEED)
                //--------------------------------------------
                case USB_OTHER_SPEED_CONFIGURATION_DESCRIPTOR:
                //--------------------------------------------
                    TRACE_DEBUG_M( "OSC " );
                    GetOSCDescriptor( pSetup->wLength );
                    break;
#endif
                //-------------------------
                case USB_STRING_DESCRIPTOR:
                //-------------------------
                    TRACE_DEBUG_M( "Str%d ", LBYTE( pSetup->wValue ) );
                    GetStringDescriptor( pSetup->wLength, LBYTE( pSetup->wValue ) );
                    break;
                //------
                default:
                //------
                    TRACE_WARNING(
                        "W: STD::RequestHandler: Unknown GetDescriptor 0x%02X\n",
                        HBYTE( pSetup->wValue )
                    );
                    pDriver->Stall ();
                    break;
                }
                break;
        //-------------------------------------------------------------------------------
        case USB_SET_ADDRESS: // bRequest
        //-------------------------------------------------------------------------------
            TRACE_DEBUG_M( "sAddr " );
            pDriver->SendZLP0( Callback_f( OnSetAddress ), this );
            break;
        //-------------------------------------------------------------------------------
        case USB_SET_CONFIGURATION: // bRequest
        //-------------------------------------------------------------------------------
            TRACE_DEBUG_M( "sCfg " );
            SetConfiguration( (char) pSetup->wValue );
            break;
        //-------------------------------------------------------------------------------
        case USB_GET_CONFIGURATION: // bRequest
        //-------------------------------------------------------------------------------
            TRACE_DEBUG_M( "gCfg " );
            GetConfiguration ();
            break;
        //-------------------------------------------------------------------------------
        case USB_CLEAR_FEATURE: // bRequest
        //-------------------------------------------------------------------------------
            TRACE_DEBUG_M( "cFeat " );
            switch( pSetup->wValue )
            {
                //---------------------
                case USB_ENDPOINT_HALT:
                //---------------------
                    TRACE_DEBUG_M( "Hlt " );
                    pDriver->Halt( LBYTE( pSetup->wIndex ), USB_CLEAR_FEATURE );
                    pDriver->SendZLP0 ();
                    break;
                //----------------------------
                case USB_DEVICE_REMOTE_WAKEUP:
                //----------------------------
                    TRACE_DEBUG_M( "RmWak " );
                    wDeviceStatus &= ~REMOTE_WAKEUP; // Remote wakeup disabled
                    pDriver->SendZLP0 ();
                    break;
                //------
                default:
                //------
                    TRACE_DEBUG_M( "Sta " );
                    pDriver->Stall ();
            }
            break;
        //-------------------------------------------------------------------------------
        case USB_GET_STATUS: // bRequest
        //-------------------------------------------------------------------------------
            TRACE_DEBUG_M( "gSta " );
            switch ( USB_REQUEST_RECIPIENT( pSetup->bmRequestType ) )
            {
                //-------------------------
                case USB_RECIPIENT_DEVICE:
                //-------------------------
                    TRACE_DEBUG_M( "Dev " );
                    GetDeviceStatus ();
                    break;
                //---------------------------
                case USB_RECIPIENT_ENDPOINT:
                //---------------------------
                    TRACE_DEBUG_M( "Ept " );
                    GetEndpointStatus( LBYTE(pSetup->wIndex) );
                    break;
                //------
                default:
                //------
                    TRACE_WARNING(
                        "W: STD::RequestHandler: Unsupported GetStatus 0x%02X\n",
                        pSetup->bmRequestType
                    );
                    pDriver->Stall ();
                    break;
            }
            break;
        //-------------------------------------------------------------------------------
        case USB_SET_FEATURE: // bRequest
        //-------------------------------------------------------------------------------
            TRACE_DEBUG_M( "sFeat " );
            switch( pSetup->wValue )
            {
                //---------------------
                case USB_ENDPOINT_HALT:
                //---------------------
                    pDriver->Halt( LBYTE(pSetup->wIndex), USB_SET_FEATURE );
                    pDriver->SendZLP0 ();
                    break;
                //----------------------------
                case USB_DEVICE_REMOTE_WAKEUP:
                //----------------------------
                    wDeviceStatus |= REMOTE_WAKEUP; // Remote wakeup enabled
                    pDriver->SendZLP0 ();
                    break;
                //------
                default:
                //------
                    TRACE_WARNING(
                        "W: STD::RequestHandler: Unsupported SetFeature 0x%04X\n",
                        pSetup->wValue
                    );
                    pDriver->Stall ();
                    break;
                }
            break;
        //-------------------------------------------------------------------------------
        case USB_GET_INTERFACE: // bRequest
        //-------------------------------------------------------------------------------
            TRACE_DEBUG_M( "gIface %d ", pSetup->wIndex );
            TRACE_DEBUG_M( "[not supported] " );
            pDriver->Stall ();
            break;
        //-------------------------------------------------------------------------------
        case USB_SET_INTERFACE: // bRequest
        //-------------------------------------------------------------------------------
            TRACE_DEBUG_M( "sIface %d / %d ", pSetup->wIndex, pSetup->wValue );
            TRACE_DEBUG_M( "[not supported] " );
            pDriver->Stall ();
            break;
        //-------------------------------------------------------------------------------
        default: // bRequest
        //-------------------------------------------------------------------------------
            TRACE_WARNING(
                "W: STD::RequestHandler: Unsupported Request 0x%02X\n",
                pSetup->bRequest
            );
            pDriver->Stall ();
            break;
    }
}
void USB::CSTD::EventHandler (void) [inline]
Low-level usb driver interrupt handler.
Definition at line 1320 of file usbFramework.hpp.
References USB::CUsbDriver::EventHandler(), and pDriver.
Referenced by ISR_USB().
    {
        pDriver->EventHandler ();
    }
void USB::CSTD::Init (void) [inline]
Initializes the USB API and the USB controller.
Definition at line 1328 of file usbFramework.hpp.
References USB::CUsbDriver::Init(), and pDriver.
Referenced by portTASK_FUNCTION().
    {
        pDriver->Init ();
    }
bool USB::CSTD::IsPowered (void) const [inline]
Return true if device is powered.
Definition at line 1336 of file usbFramework.hpp.
References USB::CUsbDriver::IsStateSet(), pDriver, and USB::USB_STATE_POWERED.
Referenced by portTASK_FUNCTION().
    {
        return pDriver->IsStateSet( USB_STATE_POWERED );
    }
void USB::CSTD::Connect (void) [inline]
Connect to device.
Definition at line 1344 of file usbFramework.hpp.
References USB::CUsbDriver::Connect(), and pDriver.
Referenced by portTASK_FUNCTION().
    {
        pDriver->Connect ();
    }
void USB::CSTD::Attach (void) [inline]
Attach device to USB bus.
Definition at line 1352 of file usbFramework.hpp.
References USB::CUsbDriver::Attach(), and pDriver.
Referenced by anonymous_namespace{usbCallbacks.cpp}::ISR_VBus().
    {
        pDriver->Attach ();
    }
Member Data Documentation
CUsbDriver* USB::CSTD::pDriver [protected]
Pointer to usb driver instance.
Definition at line 1110 of file usbFramework.hpp.
Referenced by Attach(), USB::CCDC::CCDC(), ConfigureEndpoints(), Connect(), CSTD(), EventHandler(), GetConfiguration(), GetConfigurationDescriptor(), GetDeviceDescriptor(), GetDeviceStatus(), GetEndpointStatus(), GetStringDescriptor(), Init(), IsPowered(), OnSetAddress(), USB::CCDC::OnSetLineCoding(), USB::CCDC::Read(), RequestHandler(), USB::CCDC::RequestHandler(), SetConfiguration(), and USB::CCDC::Write().
const S_std_descriptors* USB::CSTD::pDescriptors [protected]
Pointer to the list of descriptors used by the device
Definition at line 1111 of file usbFramework.hpp.
Referenced by USB::CCDC::CCDC(), ConfigureEndpoints(), GetConfigurationDescriptor(), GetDeviceDescriptor(), GetDeviceStatus(), and GetStringDescriptor().
ushort USB::CSTD::wDeviceStatus [protected]
Data buffer used for information returned by a GetStatus() request to a Device
See also:
USB Specification 2.0 Figure 9-4
Definition at line 1113 of file usbFramework.hpp.
Referenced by GetDeviceStatus(), and RequestHandler().
ushort USB::CSTD::wData [protected]
Temporary data buffer used by pDriver->Write()
Definition at line 1116 of file usbFramework.hpp.
Referenced by GetConfiguration(), and GetEndpointStatus().
The documentation for this class was generated from the following files:
src/inc/usbFramework.hpp
src/usb/usbSTD.cpp