XPU-DSAM7S: USB::CEventSink Class Reference
USB::CEventSink Class Reference
Abstract class that declares various event sinks (callbacks) called by the USB low-level driver. These callback functions are used by the USB API to notify the user application of incoming events or actions to perform.
#include <usbFramework.hpp>
Public Member Functions
virtual void OnInit (void)=0
Callback API (usb_api_callbacks).
virtual void OnReset (void)=0
Reset callback function.
virtual void OnSuspend (void)=0
Suspend callback function.
virtual void OnResume (void)=0
Resume callback function.
virtual void OnNewRequest (void)=0
New Request callback function.
virtual void OnStartOfFrame (void)=0
Interrupt SOF callback function Invoked when a SOF interrupt is received.
Detailed Description
Abstract class that declares various event sinks (callbacks) called by the USB low-level driver. These callback functions are used by the USB API to notify the user application of incoming events or actions to perform.
Definition at line 510 of file usbFramework.hpp.
Member Function Documentation
virtual void USB::CEventSink::OnInit (void) [pure virtual]
Callback API (usb_api_callbacks).
These callback functions are used by the USB API to notify the user application of incoming events or actions to perform. Initialization callback function This callback is invoked whenever the USB API is initialized using the CUsbDriver::Init function. It should perform the following operations:
If an OS is being used, install the USB driver
Configure the USB controller interrupt
Configure the VBus monitoring interrupt Attention: Implementation of this callback is mandatory
See also:
CUsbDriver::Init
Implemented in anonymous_namespace{usbCallbacks.cpp}::CCallbacks.
Referenced by CUdpDriver::Init().
virtual void USB::CEventSink::OnReset (void) [pure virtual]
Reset callback function.
Invoked whenever the device is reset by the host. This function should perform initialization or re-initialization of the user application. Attention: Implementation of this callback is optional
See also:
CUsbDriver::EventHandler
Implemented in anonymous_namespace{usbCallbacks.cpp}::CCallbacks.
Referenced by CUdpDriver::EventHandler().
virtual void USB::CEventSink::OnSuspend (void) [pure virtual]
Suspend callback function.
Invoked when the device is suspended by the host or detached from the bus. If the device must enter low-power mode when suspended, then the necessary code must be implemented here.
See also:
CUsbDriver::Attach
CUsbDriver::EventHandler
Implemented in anonymous_namespace{usbCallbacks.cpp}::CCallbacks.
Referenced by CUdpDriver::Attach(), and CUdpDriver::EventHandler().
virtual void USB::CEventSink::OnResume (void) [pure virtual]
Resume callback function.
Invoked when the device is resumed by the host or attached to the bus. If the suspend callback has put the device into low-power mode, then this function must perform the necessary actions to return it to a normal mode of operation.
See also:
CEventSink::OnSuspend
CUsbDriver::Attach
CUsbDriver::EventHandler
Implemented in anonymous_namespace{usbCallbacks.cpp}::CCallbacks.
Referenced by CUdpDriver::Attach(), and CUdpDriver::EventHandler().
virtual void USB::CEventSink::OnNewRequest (void) [pure virtual]
New Request callback function.
Invoked when a new SETUP request is received. The request can then be retrieved by using the GetSetup function on the CUsbDriver instance.
See also:
CUsbDriver::EventHandler
Implemented in anonymous_namespace{usbCallbacks.cpp}::CCallbacks.
Referenced by CUdpDriver::EndpointHandler().
virtual void USB::CEventSink::OnStartOfFrame (void) [pure virtual]
Interrupt SOF callback function Invoked when a SOF interrupt is received.
See also:
CUsbDriver::EventHandler
Implemented in anonymous_namespace{usbCallbacks.cpp}::CCallbacks.
Referenced by CUdpDriver::EventHandler().
The documentation for this class was generated from the following file:
src/inc/usbFramework.hpp