XPU-DSAM7S: USB::CBoard Class Reference
USB::CBoard Class Reference
Abstract class that declares board specific control of D+ pull up and VBUS detection.
#include <usbFramework.hpp>
Public Member Functions
virtual bool IsVBusConnected (void)=0
Indicates the state of the VBus power line associated with the specified interface.
virtual void ConnectPullUp (void)=0
Enables the external pull-up on D+ associated with the specified USB controller.
virtual void DisconnectPullUp (void)=0
Disables the external pull-up on D+ associated with the specified USB controller.
virtual bool IsPullUpConnected (void)=0
Indicates the state of the external pull-up associated with the specified interface.
virtual void ConfigurePullUp (void)=0
Configures the external pull-up on the D+ line associated with the specified USB controller.
virtual void ConfigureVBus (void)=0
Configures the VBus monitoring PIO associated with the specified USB controller.
Detailed Description
Abstract class that declares board specific control of D+ pull up and VBUS detection.
Definition at line 592 of file usbFramework.hpp.
Member Function Documentation
virtual bool USB::CBoard::IsVBusConnected (void) [pure virtual]
Indicates the state of the VBus power line associated with the specified interface.
Returns:
true if VBus is detected, false otherwise
Implemented in anonymous_namespace{usbCallbacks.cpp}::CXpuBoard.
Referenced by CUdpDriver::Attach().
virtual void USB::CBoard::ConnectPullUp (void) [pure virtual]
Enables the external pull-up on D+ associated with the specified USB controller.
Implemented in anonymous_namespace{usbCallbacks.cpp}::CXpuBoard.
Referenced by CUdpDriver::Connect().
virtual void USB::CBoard::DisconnectPullUp (void) [pure virtual]
Disables the external pull-up on D+ associated with the specified USB controller.
Implemented in anonymous_namespace{usbCallbacks.cpp}::CXpuBoard.
Referenced by CUdpDriver::Disconnect().
virtual bool USB::CBoard::IsPullUpConnected (void) [pure virtual]
Indicates the state of the external pull-up associated with the specified interface.
Returns:
true if the pull-up is currently connected, false otherwise.
Implemented in anonymous_namespace{usbCallbacks.cpp}::CXpuBoard.
virtual void USB::CBoard::ConfigurePullUp (void) [pure virtual]
Configures the external pull-up on the D+ line associated with the specified USB controller.
Implemented in anonymous_namespace{usbCallbacks.cpp}::CXpuBoard.
Referenced by CUdpDriver::Init().
virtual void USB::CBoard::ConfigureVBus (void) [pure virtual]
Configures the VBus monitoring PIO associated with the specified USB controller.
Implemented in anonymous_namespace{usbCallbacks.cpp}::CXpuBoard.
Referenced by CUdpDriver::Init().
The documentation for this class was generated from the following file:
src/inc/usbFramework.hpp