XPU-DSAM7S: USBRCVR Class Reference
USBRCVR Class Reference
#include <sam7xpud.hpp>
Public Member Functions
USBRCVR (void)
void Initialize (void)
void ReadMoreData (void)
void Receiver (void)
Static Public Member Functions
static portTASK_FUNCTION (MainTask, pvParameters)
Static Private Member Functions
static void OnReceiveUSB (USBRCVR *pThis, uchar bStatus, uint dBytesTransferred, uint dBytesRemaining)
Private Attributes
uint bufSize
union {
uchar buf [USB_RCVR_BUF_SIZE]
struct XPI_OMSG_HEADER {
uchar data [0]
} sMsg
};
volatile int bStatus
volatile uint dBytesTransferred
volatile uint dBytesRemaining
xSEMA semaReceived
Detailed Description
Definition at line 162 of file sam7xpud.hpp.
Constructor & Destructor Documentation
USBRCVR::USBRCVR (void) [inline]
Definition at line 214 of file sam7xpud.hpp.
References bufSize, and USB_RCVR_BUF_SIZE.
        : semaReceived( 0 )
    {
        bufSize = USB_RCVR_BUF_SIZE;
        }
Member Function Documentation
static void USBRCVR::OnReceiveUSB (USBRCVR * pThis, uchar bStatus, uint dBytesTransferred, uint dBytesRemaining) [inline, static, private]
Definition at line 192 of file sam7xpud.hpp.
References bStatus, dBytesRemaining, dBytesTransferred, isTaskWokenByPostInUsbIrq, xSEMA::ReleaseFromISR(), semaReceived, and USB::USB_STATUS_IMMEDREAD.
Referenced by Initialize(), and ReadMoreData().
    {
        pThis->bStatus = bStatus;
        pThis->dBytesTransferred = dBytesTransferred;
        pThis->dBytesRemaining = dBytesRemaining;
        if ( bStatus == USB::USB_STATUS_IMMEDREAD )
            return; // Must not call ReleaseFromISR() out of ISR
        if ( pThis->semaReceived.ReleaseFromISR( 1, isTaskWokenByPostInUsbIrq ) )
        {
            isTaskWokenByPostInUsbIrq = pdTRUE;
            }
        }
void USBRCVR::Initialize (void) [inline]
Definition at line 220 of file sam7xpud.hpp.
References buf, bufSize, OnReceiveUSB(), USB::CCDC::Read(), TRACE_INFO, USB::USB_STATUS_ABORTED, and USB::USB_STATUS_SUCCESS.
Referenced by portTASK_FUNCTION().
    {
#ifdef TR_INFO
        taskENTER_CRITICAL ();
        TRACE_INFO( "USBRCVR: Initialize(): Size=%u\n", bufSize );
        taskEXIT_CRITICAL ();
#endif
        // Wait a bit for USB endpoint to be ready
        vTaskDelay( 100 );
        bStatus = USB::USB_STATUS_ABORTED;
        for( ;; )
        {
            taskENTER_CRITICAL ();
            int rc = sSer.Read( buf, bufSize, Callback_f( OnReceiveUSB ), this );
            taskEXIT_CRITICAL ();
            if ( rc == USB::USB_STATUS_SUCCESS )
                break;
            // USB endopoint is not ready; wait and retry
            vTaskDelay( 10 );
            }
#ifdef TR_INFO
        taskENTER_CRITICAL ();
        TRACE_INFO( "USBRCVR: Posted initial CCDC::Read\n" );
        taskEXIT_CRITICAL ();
#endif
        }
void USBRCVR::ReadMoreData (void) [inline]
Definition at line 253 of file sam7xpud.hpp.
References buf, bufSize, OnReceiveUSB(), USB::CCDC::Read(), TRACE_ERROR, USB::USB_STATUS_ABORTED, and USB::USB_STATUS_SUCCESS.
Referenced by portTASK_FUNCTION().
    {
        bStatus = USB::USB_STATUS_ABORTED;
        for( ;; )
        {
            taskENTER_CRITICAL ();
            int rc = sSer.Read( buf, bufSize, Callback_f( OnReceiveUSB ), this );
            taskEXIT_CRITICAL ();
            if ( rc == USB::USB_STATUS_SUCCESS )
                break;
            // USB endopoint is not ready; wait and retry
            TRACE_ERROR( "!R " );
            vTaskDelay( 1 );
            }
        }
void USBRCVR::Receiver (void)
Definition at line 248 of file usbTasks.cpp.
References bStatus, buf, dBytesRemaining, dBytesTransferred, XPI::DumpStatus(), XSVF_Player::Enable(), FPGA_BegRead(), FPGA_BegWrite(), FPGA_FC_Command(), FPGA_Read(), FPGA_Write(), XPI::InitializeFPGA(), XSVF_Player::LockBuffer(), XPI_OMSG_HEADER::magicLSB, XPI_OMSG_HEADER::magicMSB, null_putc(), XPI::Put(), USBXMTR::Put(), semaReceived, XPI::SetTraceMask(), sMsg, XPI_OMSG_HEADER::subtype, sysDumpStatus(), TRACE_DEBUG_M, TRACE_ERROR, tracef_open(), XPI_OMSG_HEADER::type, us1_putc(), usb_putc(), USB::USB_STATUS_IMMEDREAD, USB::USB_STATUS_SUCCESS, xSEMA::Wait(), xpi, XPI_IMSG_LOOP, XPI_MSG_MAGIC_LSB, XPI_MSG_MAGIC_MSB, XPI_OMSG_FC_CMD, XPI_OMSG_FPGA_INIT, XPI_OMSG_LOG_CFG, XPI_OMSG_LOOP, XPI_OMSG_NULL, XPI_OMSG_QUERY, XPI_OMSG_SC_DATA, XPI_OMSG_XSVF_DATA, XPI_OMSG_XSVF_START, XPI_R_P1_BOARD_POS, XPI_W_PAGE_ADDR, and xsvf.
Referenced by portTASK_FUNCTION().
{
    // Check whether read callback has returned already found in FIFO. If not
    // then we should wait for read callback to complete.
    //
    if ( bStatus != USB::USB_STATUS_IMMEDREAD )
    {
        // Wait callback to receive data
        //
        do ; while( ! semaReceived.Wait( 1, 1000 ) );
        // Check CCDC::Read() callback status
        //
        if ( bStatus != USB::USB_STATUS_SUCCESS )
        {
#ifdef TR_ERROR
            taskENTER_CRITICAL ();
            TRACE_ERROR( "USBRCVR: Transfer error\n" );
            taskEXIT_CRITICAL ();
#endif
            return;
            }
        }
#ifdef TR_DEBUG_M
    taskENTER_CRITICAL ();
    TRACE_DEBUG_M( "USBRCVR: Got %6u, %5u; RC = %d\n",
            dBytesTransferred, dBytesRemaining, bStatus );
    taskEXIT_CRITICAL ();
#endif
    if ( dBytesTransferred == 0 )
        return;
    int dataLen = dBytesTransferred - sizeof( XPI_OMSG_HEADER );
    // Loopback XPI_OMSG messages without proper header
    //
    if ( dataLen < 0
        || sMsg.magicMSB != XPI_MSG_MAGIC_MSB
        || sMsg.magicLSB != XPI_MSG_MAGIC_LSB
        )
    {
        if ( sMsg.magicMSB == '?' )
            xpi.DumpStatus ();
        else
            usbOut.Put( buf, dBytesTransferred, 1000 );
        return;
        }
    // Process XPI_OMSG depending on message type
    //
    switch( sMsg.type )
    {
        //-------------------------------------------------------------------------------
        case XPI_OMSG_NULL:
            break;
        //-------------------------------------------------------------------------------
        case XPI_OMSG_LOOP:
        {
            if ( sMsg.subtype != 0 )
            {
                // Simulate FPGA I/O
                //
                for ( int i = 0; i <= dataLen / 32; i++ )
                {
                    taskENTER_CRITICAL ();
                    FPGA_BegWrite ();
                    FPGA_Write( XPI_W_PAGE_ADDR, 1 ); // Page 1
                    FPGA_BegRead ();
                    for ( int j = 0; j < 64; j++ )
                        (void) FPGA_Read( XPI_R_P1_BOARD_POS );
                    taskEXIT_CRITICAL ();
                    }
                }
            // Loopback packet to usbOut.
            //
            sMsg.type    = XPI_IMSG_LOOP;
            sMsg.subtype = 0;
            usbOut.Put( buf, dBytesTransferred, 1000 );
            }
            break;
        //-------------------------------------------------------------------------------
        case XPI_OMSG_XSVF_START:
        {
            // Get XSVF parameters
            //
            bool traceLevel = dataLen >= 1 ? sMsg.data[ 0 ] : 0;
            bool parseOnly  = dataLen >= 2 ? sMsg.data[ 1 ] : false;
            // Configure std output for XSVF trace (default is null device)
            //
            if ( dataLen >= 3 && sMsg.data[ 2 ] == 2 )
            {
                tracef_open( 1, us1_putc, /*LF2CRLF=*/ true, /*TimeStamp=*/ true );
                }
            else if ( dataLen >= 3 && sMsg.data[ 2 ] == 1 )
            {
                tracef_open( 1, usb_putc, /*LF2CRLF=*/ false, /*TimeStamp=*/ false );
                }
            else
            {
                tracef_open( 1, null_putc, /*LF2CRLF=*/ false, /*TimeStamp=*/ false );
                }
            // Enable (start) XSVF player
            //
            xsvf.Enable( traceLevel, parseOnly );
            }
            break;
        //-------------------------------------------------------------------------------
        case XPI_OMSG_XSVF_DATA:
        {
            if ( dataLen > 0 )
            {
                xsvf.LockBuffer( sMsg.data, dataLen );
                }
            }
            break;
        //-------------------------------------------------------------------------------
        case XPI_OMSG_FPGA_INIT:
        {
            bool coldStart    = dataLen >= 1 ? sMsg.data[ 0 ] : false;
            bool forcePassive = dataLen >= 2 ? sMsg.data[ 1 ] : false;
            xpi.InitializeFPGA( coldStart, forcePassive );
            }
            break;
        //-------------------------------------------------------------------------------
        case XPI_OMSG_QUERY:
        {
            if ( sMsg.subtype == 0x01 )
                xpi.DumpStatus ();
            else
                sysDumpStatus ();
            }
            break;
        //-------------------------------------------------------------------------------
        case XPI_OMSG_LOG_CFG:
        {
            xpi.SetTraceMask( dataLen >= 1 ? sMsg.data[ 0 ] : 0 );
            }
            break;
        //-------------------------------------------------------------------------------
        case XPI_OMSG_SC_DATA:
        {
            xpi.Put( sMsg.data, dataLen, 100 );
            }
            break;
        //-------------------------------------------------------------------------------
        case XPI_OMSG_FC_CMD:
        {
            if ( dataLen >= 2 ) // Addr with D1 and D0
            {
                int card = sMsg.data[ 0 ] & 0x3F;
                FPGA_FC_Command( ( card << 2 ) | ( sMsg.data[ 1 ] & 0x03 )  );
                vTaskDelay( 2 );
                }
            else if ( dataLen >= 1 ) // Only Addr
            {
                int card = sMsg.data[ 0 ] & 0x3F;
                // Turn off and reset the board
                //
                FPGA_FC_Command( ( card << 2 ) | 0x00 );
                vTaskDelay( 2 );
                // Turn on the board
                //
                FPGA_FC_Command( ( card << 2 ) | 0x01 );
                vTaskDelay( 2 );
                // Is the board installed?
                //
                if ( FPGA_FC_Command( ( card << 2 ) | 0x03 ) )
                {
                    vTaskDelay( 2 );
                    // Is the board turned on and installed?
                    //
                    FPGA_FC_Command( ( card << 2 ) | 0x02 );
                    }
                vTaskDelay( 2 );
                }
            }
            break;
        //-------------------------------------------------------------------------------
        default:
            // TODO: issue warning "unknown XPI_OMSG"
            break;
        }
    }
static USBRCVR::portTASK_FUNCTION (MainTask , pvParameters) [static]
Member Data Documentation
uint USBRCVR::bufSize [private]
Definition at line 168 of file sam7xpud.hpp.
Referenced by Initialize(), ReadMoreData(), and USBRCVR().
uchar USBRCVR::buf[USB_RCVR_BUF_SIZE]
Definition at line 171 of file sam7xpud.hpp.
Referenced by Initialize(), ReadMoreData(), and Receiver().
uchar USBRCVR::data[0]
Definition at line 175 of file sam7xpud.hpp.
struct { ... } ::XPI_OMSG_HEADER USBRCVR::sMsg
Referenced by Receiver().
union { ... } [private]
volatile int USBRCVR::bStatus [private]
Definition at line 180 of file sam7xpud.hpp.
Referenced by OnReceiveUSB(), and Receiver().
volatile uint USBRCVR::dBytesTransferred [private]
Definition at line 181 of file sam7xpud.hpp.
Referenced by OnReceiveUSB(), and Receiver().
volatile uint USBRCVR::dBytesRemaining [private]
Definition at line 182 of file sam7xpud.hpp.
Referenced by OnReceiveUSB(), and Receiver().
xSEMA USBRCVR::semaReceived [private]
Definition at line 186 of file sam7xpud.hpp.
Referenced by OnReceiveUSB(), and Receiver().
The documentation for this class was generated from the following files:
src/inc/sam7xpud.hpp
src/usbTasks.cpp