XPU-DSAM7S: USB::CCDC Class Reference
USB::CCDC Class Reference
CDC class driver structure.
#include <usbCDC.hpp>
Public Member Functions
CCDC (CUsbDriver *usbDriver, CBoard *board, CEventSink *eventSink)
Initializes a CDC serial driver.
void RequestHandler (void)
SETUP request handler for an Abstract Control Model device.
EnumStandardReturnValue Read (void *pBuffer, uint dLength, Callback_f fCallback, void *pArgument)
Reads data from the Data OUT endpoint.
EnumStandardReturnValue Write (const void *pBuffer, uint dLength, Callback_f fCallback=0, void *pArgument=0, const void *pBufferLowerBound=0, const void *pBufferUpperBound=0)
Sends data through the Data IN endpoint.
Public Attributes
S_cdc_line_coding sLineCoding
bool isCarrierActivated
Indicates if the device's carrier is activated.
bool isPresentDTE
Indicates if the terminal is present.
Private Types
enum { NUM_ENDPOINTS = 4 }
List of endpoints (including endpoint 0) used by the device.
Static Private Member Functions
static void OnSetLineCoding (CCDC *pThis)
Sets asynchronous line-character formatting properties.
Private Attributes
CEndpoint EndpointList [NUM_ENDPOINTS]
Detailed Description
CDC class driver structure.
Definition at line 345 of file usbCDC.hpp.
Member Enumeration Documentation
anonymous enum [private]
List of endpoints (including endpoint 0) used by the device.
Enumerator:
NUM_ENDPOINTS
Definition at line 350 of file usbCDC.hpp.
{ NUM_ENDPOINTS = 4 };
Constructor & Destructor Documentation
CCDC::CCDC (CUsbDriver * usbDriver, CBoard * board, CEventSink * eventSink)
Initializes a CDC serial driver.
This method sets the standard descriptors of the device and the default CDC configuration.
Parameters:
usbDriver Pointer to the CUsbDriver instance to use
eventSink Pointer to the CEventSink driver instance to use
This method sets the standard descriptors of the device and the default CDC configuration.
Parameters:
usbDriver USB driver instance that servers this object
board Hardware board abstraction instance
eventSink Event sink isntance that handles this object
Definition at line 352 of file usbCDC.cpp.
References USB::S_cdc_line_coding::bCharFormat, USB::S_cdc_line_coding::bDataBits, USB::S_cdc_line_coding::bParityType, USB::S_cdc_line_coding::dwDTERate, EndpointList, USB::CEndpoint::Init(), isCarrierActivated, isPresentDTE, NUM_ENDPOINTS, USB::CSTD::pDescriptors, USB::CSTD::pDriver, USB::CUsbDriver::SetEndpointList(), sLineCoding, and TRACE_INFO.
    : CSTD( usbDriver, board, eventSink )
{
    TRACE_INFO( "CCDC %08x, Driver=%08x\n", uint( this ), pDriver );
    // Initialize the list of endpoints
    //
    EndpointList[ 0 ].Init( 1 ); // Endpoint 0 (Control endpoint 0) with Single bank
    EndpointList[ 1 ].Init( 2 ); // Endpoint 1 (Data out endpoint) with Dual bank
    EndpointList[ 2 ].Init( 2 ); // Endpoint 2 (Data in endpoint) with Dual bank
    EndpointList[ 3 ].Init( 1 ); // Endpoint 3 (Notification endpoint) with Single bank
    // Announce our endpoints to usb device driver
    //
    pDriver->SetEndpointList( EndpointList, NUM_ENDPOINTS );
    // Initialize standard class attributes
    //
    pDescriptors = &sDescriptors;
    // Initialize Line Coding ACM attributes
    //
    sLineCoding.dwDTERate   = 0;
    sLineCoding.bCharFormat = 0;
    sLineCoding.bParityType = 0;
    sLineCoding.bDataBits   = 0;
    // Initialize Carrier ACM attributes
    //
    isCarrierActivated = false;
    isPresentDTE       = false;
}
Member Function Documentation
void CCDC::OnSetLineCoding (CCDC * pThis) [static, private]
Sets asynchronous line-character formatting properties.
This function is used as a callback when receiving the data part of a SET_LINE_CODING request.
See also:
usbcdc11.pdf - Section 6.2.12
This function is used as a callback when receiving the data part of a SET_LINE_CODING request.
See also:
usbcdc11.pdf - Section 6.2.12
Definition at line 257 of file usbCDC.cpp.
References USB::S_cdc_line_coding::bCharFormat, USB::S_cdc_line_coding::bDataBits, USB::S_cdc_line_coding::bParityType, USB::S_cdc_line_coding::dwDTERate, USB::CSTD::pDriver, USB::CUsbDriver::SendZLP0(), sLineCoding, and TRACE_INFO.
Referenced by RequestHandler().
{
    pThis->pDriver->SendZLP0 ();
    TRACE_INFO
    (
        "SetLineCoding(%d,%d,%d,%d)\n",
        pThis->sLineCoding.dwDTERate,
        pThis->sLineCoding.bCharFormat,
        pThis->sLineCoding.bParityType,
        pThis->sLineCoding.bDataBits
        );
}
void CCDC::RequestHandler (void) [virtual]
SETUP request handler for an Abstract Control Model device.
See also:
usbcdc11.pdf - Section 6.2
Reimplemented from USB::CSTD.
Definition at line 279 of file usbCDC.cpp.
References USB::S_usb_request::bRequest, USB::CDC_ACTIVATE_CARRIER, USB::CDC_DTE_PRESENT, USB::CDC_GET_LINE_CODING, USB::CDC_SET_CONTROL_LINE_STATE, USB::CDC_SET_LINE_CODING, USB::CUsbDriver::GetSetup(), isCarrierActivated, isPresentDTE, ISSET, OnSetLineCoding(), USB::CSTD::pDriver, USB::CUsbDriver::Read(), USB::CSTD::RequestHandler(), USB::CUsbDriver::SendZLP0(), sLineCoding, TRACE_DEBUG_M, TRACE_INFO, USB::CUsbDriver::Write(), and USB::S_usb_request::wValue.
Referenced by anonymous_namespace{usbCallbacks.cpp}::CCallbacks::OnNewRequest().
{
    S_usb_request* pSetup = pDriver->GetSetup ();
    TRACE_DEBUG_M( "NewReq " );
    // Handle the request
    //
    switch( pSetup->bRequest )
    {
        //-----------------------
        case CDC_SET_LINE_CODING:
        //-----------------------
            TRACE_DEBUG_M( "sLineCoding " );
            // Start the read operation with ACM_SetLineCoding as the callback
            pDriver->Read
            (
                 0, // endpoint
                 (void*) &(sLineCoding), // data
                 sizeof(S_cdc_line_coding), // data len
                 Callback_f( OnSetLineCoding ), this // callback
                 );
            break;
        //-----------------------
        case CDC_GET_LINE_CODING:
        //-----------------------
            TRACE_DEBUG_M( "gLineCoding " );
            // Sends the currently configured line coding to the host
            // \see usbcdc11.pdf - Section 6.2.13
            //
            pDriver->Write( 0, &sLineCoding,  sizeof( S_cdc_line_coding ) );
            break;
        //------------------------------
        case CDC_SET_CONTROL_LINE_STATE:
        //------------------------------
            TRACE_DEBUG_M( "sControlLineState " );
            // Sets the state of control line parameters.
            // \see usbcdc11.pdf - Section 6.2.14
            //
            isCarrierActivated = ISSET( pSetup->wValue, CDC_ACTIVATE_CARRIER );
            isPresentDTE = ISSET( pSetup->wValue, CDC_DTE_PRESENT );
            TRACE_INFO( "SetControlLineState(DTE=%d,DCD=%d)\n",
                        isPresentDTE, isCarrierActivated );
            pDriver->SendZLP0 ();
            break;
        //------
        default:
        //------
            // Forward request to standard request handler
            //
            CSTD::RequestHandler ();
            break;
    }
}
EnumStandardReturnValue USB::CCDC::Read (void * pBuffer, uint dLength, Callback_f fCallback, void * pArgument) [inline]
Reads data from the Data OUT endpoint.
Parameters:
pBuffer Buffer in which to store the received data
dLength Length of data buffer
fCallback Optional callback function
pArgument Optional parameter for the callback function
Returns:
SER_STATUS_SUCCESS if transfer has started successfully; SER_STATUS_LOCKED if endpoint is currently in use; SER_STATUS_ERROR if transfer cannot be started.
Definition at line 403 of file usbCDC.hpp.
References USB::CSTD::pDriver, USB::CUsbDriver::Read(), and USB::SER_EPT_DATA_OUT.
Referenced by USBRCVR::Initialize(), and USBRCVR::ReadMoreData().
    {
        return pDriver->Read( SER_EPT_DATA_OUT, pBuffer,
                              dLength, fCallback, pArgument );
    }
EnumStandardReturnValue USB::CCDC::Write (const void * pBuffer, uint dLength, Callback_f fCallback = 0, void * pArgument = 0, const void * pBufferLowerBound = 0, const void * pBufferUpperBound = 0) [inline]
Sends data through the Data IN endpoint.
Parameters:
pBuffer Buffer holding the data to transmit
dLength Length of data buffer
fCallback Optional callback function
pBufferLowerBound Lower bound of the circular buffer
pBufferUpperBound Upper bound of the circular buffer
pArgument Optional parameter for the callback function
Returns:
SER_STATUS_SUCCESS if transfer has started successfully; SER_STATUS_LOCKED if endpoint is currently in use; SER_STATUS_ERROR if transfer cannot be started.
Definition at line 424 of file usbCDC.hpp.
References USB::CSTD::pDriver, USB::SER_EPT_DATA_IN, and USB::CUsbDriver::Write().
Referenced by USBXMTR::Transmitter().
    {
        return pDriver->Write( SER_EPT_DATA_IN, pBuffer, dLength,
                               fCallback, pArgument,
                               pBufferLowerBound, pBufferUpperBound
                               );
    }
Member Data Documentation
CEndpoint USB::CCDC::EndpointList[NUM_ENDPOINTS] [private]
Definition at line 351 of file usbCDC.hpp.
Referenced by CCDC().
S_cdc_line_coding USB::CCDC::sLineCoding
Contains line coding i.e. data rate, data bit count, stop bit and parity information
Definition at line 354 of file usbCDC.hpp.
Referenced by CCDC(), OnSetLineCoding(), and RequestHandler().
bool USB::CCDC::isCarrierActivated
Indicates if the device's carrier is activated.
Definition at line 356 of file usbCDC.hpp.
Referenced by CCDC(), and RequestHandler().
bool USB::CCDC::isPresentDTE
Indicates if the terminal is present.
Definition at line 357 of file usbCDC.hpp.
Referenced by CCDC(), and RequestHandler().
The documentation for this class was generated from the following files:
src/inc/usbCDC.hpp
src/usb/usbCDC.cpp