XPU-DSAM7S: XSVF_Class Class Reference
XSVF_Class Class Reference
Public Types
enum XSVF_RC {
XSVF_ERROR_NONE = 0, XSVF_ERROR_UNKNOWN = 1, XSVF_ERROR_TDOMISMATCH = 2, XSVF_ERROR_MAXRETRIES = 3,
XSVF_ERROR_ILLEGALCMD = 4, XSVF_ERROR_ILLEGALSTATE = 5, XSVF_ERROR_DATAOVERFLOW = 6, XSVF_ERROR_ENDOFFILE = 7,
XSVF_ERROR_LAST = 8
}
Public Member Functions
XSVF_Class (void)
void Initialize (int traceLevel, bool parseOnly)
int Run (void)
Private Types
enum XSVF_COMMAND {
XCOMPLETE = 0, XTDOMASK = 1, XSIR = 2, XSDR = 3,
XRUNTEST = 4, XCMDRESERVED5 = 5, XCMDRESERVED6 = 6, XREPEAT = 7,
XSDRSIZE = 8, XSDRTDO = 9, XSETSDRMASKS = 10, XSDRINC = 11,
XSDRB = 12, XSDRC = 13, XSDRE = 14, XSDRTDOB = 15,
XSDRTDOC = 16, XSDRTDOE = 17, XSTATE = 18, XENDIR = 19,
XENDDR = 20, XSIR2 = 21, XCOMMENT = 22, XWAIT = 23,
XLASTCMD = 24
}
enum XSVF_XENDXR { XENDXR_RUNTEST = 0, XENDXR_PAUSE = 1 }
enum XSVF_TAPSTATE {
XTAPSTATE_RESET = 0x00, XTAPSTATE_RUNTEST = 0x01, XTAPSTATE_SELECTDR = 0x02, XTAPSTATE_CAPTUREDR = 0x03,
XTAPSTATE_SHIFTDR = 0x04, XTAPSTATE_EXIT1DR = 0x05, XTAPSTATE_PAUSEDR = 0x06, XTAPSTATE_EXIT2DR = 0x07,
XTAPSTATE_UPDATEDR = 0x08, XTAPSTATE_IRSTATES = 0x09, XTAPSTATE_SELECTIR = 0x09, XTAPSTATE_CAPTUREIR = 0x0A,
XTAPSTATE_SHIFTIR = 0x0B, XTAPSTATE_EXIT1IR = 0x0C, XTAPSTATE_PAUSEIR = 0x0D, XTAPSTATE_EXIT2IR = 0x0E,
XTAPSTATE_UPDATEIR = 0x0F, XTAPSTATE_FIRST = 0x00, XTAPSTATE_LAST = 0x0F
}
Private Member Functions
void GotoTapState (XSVF_TAPSTATE ucTargetState)
void ShiftOnly (long lNumBits, bool bTdoCaptured, bool bExitShift)
void Shift (XSVF_TAPSTATE ucStartState, long lNumBits, XSVF_TAPSTATE ucEndState, long runTestTime, bool captureTDO=false, int maxRepeat=0)
void BasicXSDRTDO (XSVF_TAPSTATE ucEndState, long runTestTime=0, bool captureTDO=false, int maxRepeat=0)
void DoSDRMasking (void)
void Do_ILLEGALCMD (void)
void Do_XCOMPLETE (void)
void Do_XTDOMASK (void)
void Do_XSIR (void)
void Do_XSIR2 (void)
void Do_XSDR (void)
void Do_XRUNTEST (void)
void Do_XREPEAT (void)
void Do_XSDRSIZE (void)
void Do_XSDRTDO (void)
void Do_XSETSDRMASKS (void)
void Do_XSDRINC (void)
void Do_XSDRBCE (void)
void Do_XSDRTDOBCE (void)
void Do_XSTATE (void)
void Do_XENDXR (void)
void Do_XCOMMENT (void)
void Do_XWAIT (void)
Static Private Member Functions
static int GetAsNumBytes (long lNumBits)
static void TmsTransition (int sTms)
Private Attributes
int mTraceLevel
bool mParseOnly
bool mComplete
int mCommand
long mCommandCount
int mErrorCode
XSVF_TAPSTATE mTapState
XSVF_TAPSTATE mTapStateEndIR
XSVF_TAPSTATE mTapStateEndDR
int mMaxRepeat
long mRunTestTime
long mShiftLengthBits
int mShiftLengthBytes
OctetArray lvTdi
OctetArray lvTdoExpected
OctetArray lvTdoCaptured
OctetArray lvTdoMask
OctetArray lvAddressMask
OctetArray lvDataMask
OctetArray lvNextData
Static Private Attributes
static const char * pzCommandName []
static const char * pzTapState []
static const char * pzErrorName []
Detailed Description
Definition at line 250 of file xsvfPlayer.cpp.
Member Enumeration Documentation
enum XSVF_Class::XSVF_COMMAND [private]
Enumerator:
XCOMPLETE
XTDOMASK
XSIR
XSDR
XRUNTEST
XCMDRESERVED5
XCMDRESERVED6
XREPEAT
XSDRSIZE
XSDRTDO
XSETSDRMASKS
XSDRINC
XSDRB
XSDRC
XSDRE
XSDRTDOB
XSDRTDOC
XSDRTDOE
XSTATE
XENDIR
XENDDR
XSIR2
XCOMMENT
XWAIT
XLASTCMD
Definition at line 267 of file xsvfPlayer.cpp.
    {
        XCOMPLETE      =  0,
        XTDOMASK       =  1,
        XSIR           =  2,
        XSDR           =  3,
        XRUNTEST       =  4,
        XCMDRESERVED5  =  5,
        XCMDRESERVED6  =  6,
        XREPEAT        =  7,
        XSDRSIZE       =  8,
        XSDRTDO        =  9,
        XSETSDRMASKS   =  10,
        XSDRINC        =  11,
        XSDRB          =  12,
        XSDRC          =  13,
        XSDRE          =  14,
        XSDRTDOB       =  15,
        XSDRTDOC       =  16,
        XSDRTDOE       =  17,
        XSTATE         =  18,
        XENDIR         =  19,
        XENDDR         =  20,
        XSIR2          =  21,
        XCOMMENT       =  22,
        XWAIT          =  23,
        XLASTCMD       =  24,
        };
enum XSVF_Class::XSVF_XENDXR [private]
Enumerator:
XENDXR_RUNTEST
XENDXR_PAUSE
Definition at line 296 of file xsvfPlayer.cpp.
    {
        XENDXR_RUNTEST =  0,            // parameter for XENDIR/DR
        XENDXR_PAUSE   =  1             // parameter for XENDIR/DR
        };
enum XSVF_Class::XSVF_TAPSTATE [private]
Enumerator:
XTAPSTATE_RESET
XTAPSTATE_RUNTEST
XTAPSTATE_SELECTDR
XTAPSTATE_CAPTUREDR
XTAPSTATE_SHIFTDR
XTAPSTATE_EXIT1DR
XTAPSTATE_PAUSEDR
XTAPSTATE_EXIT2DR
XTAPSTATE_UPDATEDR
XTAPSTATE_IRSTATES
XTAPSTATE_SELECTIR
XTAPSTATE_CAPTUREIR
XTAPSTATE_SHIFTIR
XTAPSTATE_EXIT1IR
XTAPSTATE_PAUSEIR
XTAPSTATE_EXIT2IR
XTAPSTATE_UPDATEIR
XTAPSTATE_FIRST
XTAPSTATE_LAST
Definition at line 302 of file xsvfPlayer.cpp.
    {
        XTAPSTATE_RESET     = 0x00,
        XTAPSTATE_RUNTEST   = 0x01,     // a.k.a. IDLE
        XTAPSTATE_SELECTDR  = 0x02,
        XTAPSTATE_CAPTUREDR = 0x03,
        XTAPSTATE_SHIFTDR   = 0x04,
        XTAPSTATE_EXIT1DR   = 0x05,
        XTAPSTATE_PAUSEDR   = 0x06,
        XTAPSTATE_EXIT2DR   = 0x07,
        XTAPSTATE_UPDATEDR  = 0x08,
        XTAPSTATE_IRSTATES  = 0x09,     // All IR states begin here
        XTAPSTATE_SELECTIR  = 0x09,
        XTAPSTATE_CAPTUREIR = 0x0A,
        XTAPSTATE_SHIFTIR   = 0x0B,
        XTAPSTATE_EXIT1IR   = 0x0C,
        XTAPSTATE_PAUSEIR   = 0x0D,
        XTAPSTATE_EXIT2IR   = 0x0E,
        XTAPSTATE_UPDATEIR  = 0x0F,
        ///////////////////////////
        XTAPSTATE_FIRST     = 0x00,
        XTAPSTATE_LAST      = 0x0F
        };
enum XSVF_Class::XSVF_RC
Enumerator:
XSVF_ERROR_NONE
XSVF_ERROR_UNKNOWN
XSVF_ERROR_TDOMISMATCH
XSVF_ERROR_MAXRETRIES
XSVF_ERROR_ILLEGALCMD
XSVF_ERROR_ILLEGALSTATE
XSVF_ERROR_DATAOVERFLOW
XSVF_ERROR_ENDOFFILE
XSVF_ERROR_LAST
Definition at line 523 of file xsvfPlayer.cpp.
    {
        XSVF_ERROR_NONE         = 0,
        XSVF_ERROR_UNKNOWN      = 1,
        XSVF_ERROR_TDOMISMATCH  = 2,
        XSVF_ERROR_MAXRETRIES   = 3,  // TDO mismatch after max retries
        XSVF_ERROR_ILLEGALCMD   = 4,
        XSVF_ERROR_ILLEGALSTATE = 5,
        XSVF_ERROR_DATAOVERFLOW = 6,  // Data > OctetArray::MAX_LEN buffer size
        XSVF_ERROR_ENDOFFILE    = 7,  // Premature end of file
        XSVF_ERROR_LAST         = 8
        };
Constructor & Destructor Documentation
XSVF_Class::XSVF_Class (void)
Definition at line 1738 of file xsvfPlayer.cpp.
References mTraceLevel, TRACE_DBG, and TRACE_XSVF.
{
#ifdef TRACE_XSVF
    mTraceLevel = TRACE_XSVF;
#endif
    TRACE_DBG( 1, "XSVF_Class: sizeof() = %d bytes\n", sizeof( XSVF_Class ) );
    }
Member Function Documentation
static int XSVF_Class::GetAsNumBytes (long lNumBits) [inline, static, private]
Definition at line 376 of file xsvfPlayer.cpp.
Referenced by Do_XSDRINC(), Do_XSDRSIZE(), Do_XSIR(), and Do_XSIR2().
    {
        return int( ( lNumBits + 7L ) / 8L );
        }
static void XSVF_Class::TmsTransition (int sTms) [inline, static, private]
Definition at line 389 of file xsvfPlayer.cpp.
References SetTCK(), and SetTMS().
    {
        SetTMS( sTms );
        SetTCK( 0 );
        SetTCK( 1 );
        }
void XSVF_Class::GotoTapState (XSVF_TAPSTATE ucTargetState) [private]
Definition at line 640 of file xsvfPlayer.cpp.
References SetTCK(), and TRACE_DBG.
Referenced by Do_XSTATE(), Do_XWAIT(), Initialize(), and Run().
{
    mErrorCode = XSVF_ERROR_NONE;
    if ( ucTargetState == XTAPSTATE_RESET )
    {
        // If RESET, always perform TMS reset sequence to reset/sync TAPs
        //
        TmsTransition( 1 );
        for ( int i = 0; i < 5; ++i )
        {
            SetTCK( 0 );
            SetTCK( 1 );
            }
        mTapState = XTAPSTATE_RESET;
        TRACE_DBG( 3, "      TMS Reset Sequence -> Test-Logic-Reset\n" );
        TRACE_DBG( 3, "      TAP State    = %s\n", pzTapState[ mTapState ] );
        }
    else if ( ucTargetState != mTapState
         && ( ( ucTargetState == XTAPSTATE_EXIT2DR && mTapState != XTAPSTATE_PAUSEDR )
           || ( ucTargetState == XTAPSTATE_EXIT2IR && mTapState != XTAPSTATE_PAUSEIR ) )
        )
    {
        // Trap illegal TAP state path specification
        //
        mErrorCode = XSVF_ERROR_ILLEGALSTATE;
        }
    else
    {
        if ( ucTargetState == mTapState )
        {
            // Already in target state. Do nothing except when in DRPAUSE
            // or in IRPAUSE to comply with SVF standard
            //
            if ( ucTargetState == XTAPSTATE_PAUSEDR )
            {
                TmsTransition( 1 );
                mTapState = XTAPSTATE_EXIT2DR;
                TRACE_DBG( 3, "      TAP State    = %s\n", pzTapState[ mTapState ] );
                }
            else if ( ucTargetState == XTAPSTATE_PAUSEIR )
            {
                TmsTransition( 1 );
                mTapState = XTAPSTATE_EXIT2IR;
                TRACE_DBG( 3, "      TAP State    = %s\n", pzTapState[ mTapState ] );
                }
            }
        // Perform TAP state transitions to get to the target state
        //
        while ( ucTargetState != mTapState )
        {
            switch ( mTapState )
            {
                case XTAPSTATE_RESET:
                    TmsTransition( 0 );
                    mTapState = XTAPSTATE_RUNTEST;
                    break;
                case XTAPSTATE_RUNTEST:
                    TmsTransition( 1 );
                    mTapState = XTAPSTATE_SELECTDR;
                    break;
                case XTAPSTATE_SELECTDR:
                    if ( ucTargetState >= XTAPSTATE_IRSTATES )
                    {
                        TmsTransition( 1 );
                        mTapState = XTAPSTATE_SELECTIR;
                        }
                    else
                    {
                        TmsTransition( 0 );
                        mTapState = XTAPSTATE_CAPTUREDR;
                        }
                    break;
                case XTAPSTATE_CAPTUREDR:
                    if ( ucTargetState == XTAPSTATE_SHIFTDR )
                    {
                        TmsTransition( 0 );
                        mTapState = XTAPSTATE_SHIFTDR;
                        }
                    else
                    {
                        TmsTransition( 1 );
                        mTapState = XTAPSTATE_EXIT1DR;
                        }
                    break;
                case XTAPSTATE_SHIFTDR:
                    TmsTransition( 1 );
                    mTapState = XTAPSTATE_EXIT1DR;
                    break;
                case XTAPSTATE_EXIT1DR:
                    if ( ucTargetState == XTAPSTATE_PAUSEDR )
                    {
                        TmsTransition( 0 );
                        mTapState = XTAPSTATE_PAUSEDR;
                        }
                    else
                    {
                        TmsTransition( 1 );
                        mTapState = XTAPSTATE_UPDATEDR;
                        }
                    break;
                case XTAPSTATE_PAUSEDR:
                    TmsTransition( 1 );
                    mTapState = XTAPSTATE_EXIT2DR;
                    break;
                case XTAPSTATE_EXIT2DR:
                    if ( ucTargetState == XTAPSTATE_SHIFTDR )
                    {
                        TmsTransition( 0 );
                        mTapState = XTAPSTATE_SHIFTDR;
                        }
                    else
                    {
                        TmsTransition( 1 );
                        mTapState = XTAPSTATE_UPDATEDR;
                        }
                    break;
                case XTAPSTATE_UPDATEDR:
                    if ( ucTargetState == XTAPSTATE_RUNTEST )
                    {
                        TmsTransition( 0 );
                        mTapState = XTAPSTATE_RUNTEST;
                        }
                    else
                    {
                        TmsTransition( 1 );
                        mTapState = XTAPSTATE_SELECTDR;
                        }
                    break;
                case XTAPSTATE_SELECTIR:
                    TmsTransition( 0 );
                    mTapState = XTAPSTATE_CAPTUREIR;
                    break;
                case XTAPSTATE_CAPTUREIR:
                    if ( ucTargetState == XTAPSTATE_SHIFTIR )
                    {
                        TmsTransition( 0 );
                        mTapState = XTAPSTATE_SHIFTIR;
                        }
                    else
                    {
                        TmsTransition( 1 );
                        mTapState = XTAPSTATE_EXIT1IR;
                        }
                    break;
                case XTAPSTATE_SHIFTIR:
                    TmsTransition( 1 );
                    mTapState = XTAPSTATE_EXIT1IR;
                    break;
                case XTAPSTATE_EXIT1IR:
                    if ( ucTargetState == XTAPSTATE_PAUSEIR )
                    {
                        TmsTransition( 0 );
                        mTapState = XTAPSTATE_PAUSEIR;
                        }
                    else
                    {
                        TmsTransition( 1 );
                        mTapState = XTAPSTATE_UPDATEIR;
                        }
                    break;
                case XTAPSTATE_PAUSEIR:
                    TmsTransition( 1 );
                    mTapState = XTAPSTATE_EXIT2IR;
                    break;
                case XTAPSTATE_EXIT2IR:
                    if ( ucTargetState == XTAPSTATE_SHIFTIR )
                    {
                        TmsTransition( 0 );
                        mTapState = XTAPSTATE_SHIFTIR;
                        }
                    else
                    {
                        TmsTransition( 1 );
                        mTapState = XTAPSTATE_UPDATEIR;
                        }
                    break;
                case XTAPSTATE_UPDATEIR:
                    if ( ucTargetState == XTAPSTATE_RUNTEST )
                    {
                        TmsTransition( 0 );
                        mTapState = XTAPSTATE_RUNTEST;
                        }
                    else
                    {
                        TmsTransition( 1 );
                        mTapState = XTAPSTATE_SELECTDR;
                        }
                    break;
                default:
                    mErrorCode = XSVF_ERROR_ILLEGALSTATE;
                    mTapState = ucTargetState;    // Exit while loop
                    break;
                }
            TRACE_DBG( 3, "      TAP State    = %s\n", pzTapState[ mTapState ] );
            }
        }
    }
void XSVF_Class::ShiftOnly (long lNumBits, bool bTdoCaptured, bool bExitShift) [private]
Definition at line 873 of file xsvfPlayer.cpp.
References GetTDO(), SetTCK(), SetTDI(), and SetTMS().
{
    // assert( ( ( lNumBits + 7 ) / 8 ) == lvTdi.len );
    // Initialize TDO storage len == TDI len
    //
    unsigned char* pucTdo = 0;
    if ( bTdoCaptured )
    {
        lvTdoCaptured.len = lvTdi.len;
        pucTdo            = lvTdoCaptured.val + lvTdi.len;
        }
    // Shift LSB first: val[N-1] == LSB, val[0] == MSB
    //
    unsigned char* pucTdi = lvTdi.val + lvTdi.len;
    while ( lNumBits )
    {
        // Process on a byte-basis
        //
        int ucTdiByte = *(--pucTdi);
        int ucTdoByte = 0;
        for ( int i = 0; lNumBits && i < 8; ++i )
        {
            --lNumBits;
            if ( bExitShift && ! lNumBits )
            {
                // Exit Shift-DR state
                //
                SetTMS( 1 );
                }
            // Set the new TDI value
            //
            SetTDI( ucTdiByte & 1 );
            ucTdiByte >>= 1;
            // Set TCK low
            //
            SetTCK( 0 );
            // Save the TDO value
            //
            if ( pucTdo )
            {
                ucTdoByte |= ( GetTDO () << i );
                }
            // Set TCK high
            //
            SetTCK( 1 );
            }
        // Save the TDO byte value
        //
        if ( pucTdo )
        {
            *(--pucTdo) = ucTdoByte;
            }
        }
    }
void XSVF_Class::Shift (XSVF_TAPSTATE ucStartState, long lNumBits, XSVF_TAPSTATE ucEndState, long runTestTime, bool captureTDO = false, int maxRepeat = 0) [private]
Definition at line 953 of file xsvfPlayer.cpp.
References TRACE_ARR, TRACE_DBG, and uSleep().
Referenced by BasicXSDRTDO(), Do_XSDR(), Do_XSDRINC(), Do_XSIR(), and Do_XSIR2().
                                                         : Shift-DR or Shift-IR
    long          lNumBits,       // number of bits to shift
    XSVF_TAPSTATE ucEndState,     // state in which to end the shift
    long          runTestTime,    // amount of time to wait after the shift
    bool          captureTDO,     // capture TDO
    int           maxRepeat       // Maximum number of retries on TDO mismatch
    )
{
    mErrorCode = XSVF_ERROR_NONE;
    if ( ! lNumBits )
    {
        // Compatibility with XSVF2.00
        // XSDR 0 means: "no shift, but wait in run test"
        //
        if ( runTestTime )
        {
            // Wait for prespecified XRUNTEST time
            //
            GotoTapState( XTAPSTATE_RUNTEST );
            TRACE_DBG( 3, "      Wait         = %ld usec\n", runTestTime );
            if ( ! mParseOnly )
            {
                uSleep( runTestTime );
                }
            }
        return;
        }
    TRACE_DBG( 3, "      Shift Length = %ld\n", lNumBits );
    TRACE_DBG( 4, "      TDI          = " );
    TRACE_ARR( 4, &lvTdi );
    TRACE_DBG( 4, "\n");
    if ( captureTDO )
    {
        TRACE_DBG( 4, "      TDO Expected = " );
        TRACE_ARR( 4, &lvTdoExpected );
        TRACE_DBG( 4, "\n" );
        }
    bool bMismatch = false;
    int retry = 0;
    do
    {
        bool bExitShift = ucStartState != ucEndState;
        // Goto Shift-DR or Shift-IR
        //
        GotoTapState( ucStartState );
        // Shift TDI and optionally capture TDO
        //
        if ( ! mParseOnly )
        {
            ShiftOnly( lNumBits, captureTDO, bExitShift );
            // Compare TDO data to expected TDO data
            //
            if ( captureTDO )
            {
                bMismatch = ! lvTdoCaptured.IsEqual( &lvTdoExpected, &lvTdoMask );
                }
            }
        if ( bExitShift )
        {
            // Update TAP state:  Shift->Exit
            //
            switch( mTapState )
            {
                case XTAPSTATE_SHIFTDR:
                    mTapState = XTAPSTATE_EXIT1DR;
                    break;
                case XTAPSTATE_SHIFTIR:
                    mTapState = XTAPSTATE_EXIT1IR;
                    break;
                default:
                    mErrorCode = XSVF_ERROR_ILLEGALSTATE;
                    return;
                }
            TRACE_DBG( 3, "      TAP State    = %s\n", pzTapState[ mTapState ] );
            if ( bMismatch && runTestTime && retry < maxRepeat )
            {
                TRACE_DBG( 4, "      TDO Mismatch\n" );
                TRACE_DBG( 4, "      TDO Captured = " );
                TRACE_ARR( 4, &lvTdoCaptured );
                TRACE_DBG( 4, "\n" );
                TRACE_DBG( 4, "      TDO Expected = " );
                TRACE_ARR( 4, &lvTdoExpected );
                TRACE_DBG( 4, "\n" );
                TRACE_DBG( 4, "      TDO Mask     = " );
                TRACE_ARR( 4, &lvTdoMask );
                TRACE_DBG( 4, "\n" );
                // Do exception handling retry - ShiftDR only
                //
                GotoTapState( XTAPSTATE_PAUSEDR );
                // Shift 1 extra bit
                //
                GotoTapState( XTAPSTATE_SHIFTDR );
                // Increment RUNTEST time by an additional 25%
                //
                runTestTime += ( runTestTime >> 2 );
                }
            else
            {
                // Do normal exit from Shift-XR
                //
                GotoTapState( ucEndState );
                }
            if ( runTestTime )
            {
                // Wait for prespecified XRUNTEST time
                //
                GotoTapState( XTAPSTATE_RUNTEST );
                TRACE_DBG( 3, "      Wait         = %ld usec\n", runTestTime );
                if ( ! mParseOnly )
                {
                    uSleep( runTestTime );
                    }
                }
            if ( bMismatch && retry < maxRepeat )
            {
                TRACE_DBG( 3, "----> RETRY        # %d\n", retry + 1 );
                }
            }
        } while( bMismatch && retry++ < maxRepeat );
    if ( bMismatch )
    {
        if ( maxRepeat && retry > maxRepeat )
            mErrorCode = XSVF_ERROR_MAXRETRIES;
        else
            mErrorCode = XSVF_ERROR_TDOMISMATCH;
        }
    }
void XSVF_Class::BasicXSDRTDO (XSVF_TAPSTATE ucEndState, long runTestTime = 0, bool captureTDO = false, int maxRepeat = 0) [inline, private]
Definition at line 456 of file xsvfPlayer.cpp.
References lvTdi, lvTdoExpected, mErrorCode, mShiftLengthBits, mShiftLengthBytes, OctetArray::ReadXSVF(), Shift(), XSVF_ERROR_ENDOFFILE, and XTAPSTATE_SHIFTDR.
Referenced by Do_XSDRBCE(), Do_XSDRTDO(), and Do_XSDRTDOBCE().
    {
        if ( ! lvTdi.ReadXSVF( mShiftLengthBytes ) )
        {
            mErrorCode = XSVF_ERROR_ENDOFFILE;
            return;
            }
        if ( captureTDO )
        {
            if ( ! lvTdoExpected.ReadXSVF( mShiftLengthBytes ) )
            {
                mErrorCode = XSVF_ERROR_ENDOFFILE;
                return;
                }
            }
        Shift
        (
            XTAPSTATE_SHIFTDR, mShiftLengthBits, ucEndState, runTestTime,
            captureTDO, maxRepeat
            );
        }
void XSVF_Class::DoSDRMasking (void) [private]
Definition at line 1107 of file xsvfPlayer.cpp.
References OctetArray::Add(), OctetArray::len, lvAddressMask, lvDataMask, lvNextData, lvTdi, and OctetArray::val.
Referenced by Do_XSDRINC().
{
    // Add the address Mask to dataVal and return as a new dataVal
    //
    lvTdi.Add( lvAddressMask );
    int ucNextData = 0;
    int ucNextMask = 0;
    int sNextData  = lvNextData.len;
    for ( int i = lvDataMask.len - 1; i >= 0; --i )
    {
        // Go through data mask in reverse order looking for mask (1) bits
        //
        int ucDataMask = lvDataMask.val[ i ];
        if ( ucDataMask )
        {
            // Retrieve the corresponding TDI byte value
            //
            int ucTdi = lvTdi.val[ i ];
            // For each bit in the data mask byte, look for 1's
            //
            int ucTdiMask = 1;
            while ( ucDataMask )
            {
                if ( ucDataMask & 1 )
                {
                    if ( ! ucNextMask )
                    {
                        // Get the next data byte
                        //
                        ucNextData = lvNextData.val[ --sNextData ];
                        ucNextMask = 1;
                        }
                    // Set or clear the data bit according to the next data
                    //
                    if ( ucNextData & ucNextMask )
                    {
                        ucTdi |= ucTdiMask; // Set bit
                        }
                    else
                    {
                        ucTdi &= ~ucTdiMask; // Clear bit
                        }
                    // Update the next data
                    //
                    ucNextMask  <<= 1;
                    }
                ucTdiMask  <<= 1;
                ucDataMask >>= 1;
                }
            // Update the TDI value
            //
            lvTdi.val[ i ] = ucTdi;
            }
        }
    }
void XSVF_Class::Do_ILLEGALCMD (void) [private]
Definition at line 1180 of file xsvfPlayer.cpp.
References mErrorCode, and XSVF_ERROR_ILLEGALCMD.
Referenced by Run().
{
    mErrorCode = XSVF_ERROR_ILLEGALCMD;
    }
void XSVF_Class::Do_XCOMPLETE (void) [private]
Definition at line 1190 of file xsvfPlayer.cpp.
References mComplete, mErrorCode, and XSVF_ERROR_NONE.
Referenced by Run().
{
    mComplete = true;
    mErrorCode = XSVF_ERROR_NONE;
    }
void XSVF_Class::Do_XTDOMASK (void) [private]
Definition at line 1201 of file xsvfPlayer.cpp.
References lvTdoMask, mErrorCode, mShiftLengthBytes, OctetArray::ReadXSVF(), TRACE_ARR, TRACE_DBG, XSVF_ERROR_ENDOFFILE, and XSVF_ERROR_NONE.
Referenced by Run().
{
    if ( ! lvTdoMask.ReadXSVF( mShiftLengthBytes ) )
    {
        mErrorCode = XSVF_ERROR_ENDOFFILE;
        return;
        }
    TRACE_DBG( 4, "      TDO Mask     = ");
    TRACE_ARR( 4, &lvTdoMask );
    TRACE_DBG( 4, "\n");
    mErrorCode = XSVF_ERROR_NONE;
    }
void XSVF_Class::Do_XSIR (void) [private]
Definition at line 1223 of file xsvfPlayer.cpp.
References GetAsNumBytes(), lvTdi, OctetArray::MAX_LEN, mErrorCode, mRunTestTime, mTapStateEndIR, OctetArray::ReadXSVF(), ReadXSVF(), Shift(), TRACE_DBG, XSVF_ERROR_DATAOVERFLOW, XSVF_ERROR_ENDOFFILE, and XTAPSTATE_SHIFTIR.
Referenced by Run().
{
    // Get the shift length and store
    //
    int ucShiftIrBits = ReadXSVF ();
    if ( ucShiftIrBits < 0 )
    {
        mErrorCode = XSVF_ERROR_ENDOFFILE;
        return;
        }
    int sShiftIrBytes = GetAsNumBytes( ucShiftIrBits );
    if ( sShiftIrBytes < 0 )
    {
        mErrorCode = XSVF_ERROR_ENDOFFILE;
        return;
        }
    TRACE_DBG( 3, "      IR Length    = %d\n", ucShiftIrBits );
    if ( sShiftIrBytes > OctetArray::MAX_LEN )
    {
        mErrorCode = XSVF_ERROR_DATAOVERFLOW;
        return;
        }
    // Get and store instruction to shift in
    //
    if ( ! lvTdi.ReadXSVF( GetAsNumBytes( ucShiftIrBits ) ) )
    {
        mErrorCode = XSVF_ERROR_ENDOFFILE;
        return;
        }
    // Shift the data
    //
    Shift( XTAPSTATE_SHIFTIR, ucShiftIrBits, mTapStateEndIR, mRunTestTime );
    }
void XSVF_Class::Do_XSIR2 (void) [private]
Definition at line 1269 of file xsvfPlayer.cpp.
References GetAsNumBytes(), OctetArray::GetValue(), lvTdi, OctetArray::MAX_LEN, mErrorCode, mRunTestTime, mTapStateEndIR, OctetArray::ReadXSVF(), Shift(), TRACE_DBG, XSVF_ERROR_DATAOVERFLOW, XSVF_ERROR_ENDOFFILE, and XTAPSTATE_SHIFTIR.
Referenced by Run().
{
    // Get the shift length and store
    //
    if ( ! lvTdi.ReadXSVF( 2 ) )
    {
        mErrorCode = XSVF_ERROR_ENDOFFILE;
        return;
        }
    long lShiftIrBits  = lvTdi.GetValue ();
    int sShiftIrBytes  = GetAsNumBytes( lShiftIrBits );
    TRACE_DBG( 3, "      IR Length    = %ld\n", lShiftIrBits);
    if ( sShiftIrBytes > OctetArray::MAX_LEN )
    {
        mErrorCode  = XSVF_ERROR_DATAOVERFLOW;
        }
    else
    {
        // Get and store instruction to shift in
        //
        if ( ! lvTdi.ReadXSVF( GetAsNumBytes( lShiftIrBits ) ) )
        {
            mErrorCode = XSVF_ERROR_ENDOFFILE;
            return;
            }
        // Shift the data
        //
        Shift( XTAPSTATE_SHIFTIR, lShiftIrBits, mTapStateEndIR, mRunTestTime );
        }
    }
void XSVF_Class::Do_XSDR (void) [private]
Definition at line 1312 of file xsvfPlayer.cpp.
References lvTdi, mErrorCode, mMaxRepeat, mRunTestTime, mShiftLengthBits, mShiftLengthBytes, mTapStateEndDR, OctetArray::ReadXSVF(), Shift(), XSVF_ERROR_ENDOFFILE, and XTAPSTATE_SHIFTDR.
Referenced by Run().
{
    if ( ! lvTdi.ReadXSVF( mShiftLengthBytes ) )
    {
        mErrorCode = XSVF_ERROR_ENDOFFILE;
        return;
        }
    // Use TDOExpected from last XSDRTDO instruction
    //
    Shift
    (
        XTAPSTATE_SHIFTDR, mShiftLengthBits, mTapStateEndDR, mRunTestTime,
        /*captureTDO*/true, mMaxRepeat
        );
    }
void XSVF_Class::Do_XRUNTEST (void) [private]
Definition at line 1334 of file xsvfPlayer.cpp.
References OctetArray::GetValue(), lvTdi, mErrorCode, mRunTestTime, OctetArray::ReadXSVF(), TRACE_DBG, XSVF_ERROR_ENDOFFILE, and XSVF_ERROR_NONE.
Referenced by Run().
{
    if ( ! lvTdi.ReadXSVF( 4 ) )
    {
        mErrorCode = XSVF_ERROR_ENDOFFILE;
        return;
        }
    mRunTestTime = lvTdi.GetValue ();
    TRACE_DBG( 3, "      Test Time    = %ld usec\n", mRunTestTime );
    mErrorCode = XSVF_ERROR_NONE;
    }
void XSVF_Class::Do_XREPEAT (void) [private]
Definition at line 1354 of file xsvfPlayer.cpp.
References mErrorCode, mMaxRepeat, ReadXSVF(), TRACE_DBG, XSVF_ERROR_ENDOFFILE, and XSVF_ERROR_NONE.
Referenced by Run().
{
    mMaxRepeat = ReadXSVF ();
    if ( mMaxRepeat < 0 )
    {
        mErrorCode = XSVF_ERROR_ENDOFFILE;
        return;
        }
    TRACE_DBG( 3, "      Max Repeat   = %d\n", mMaxRepeat );
    mErrorCode = XSVF_ERROR_NONE;
    }
void XSVF_Class::Do_XSDRSIZE (void) [private]
Definition at line 1373 of file xsvfPlayer.cpp.
References GetAsNumBytes(), OctetArray::GetValue(), lvTdi, OctetArray::MAX_LEN, mErrorCode, mShiftLengthBits, mShiftLengthBytes, OctetArray::ReadXSVF(), TRACE_DBG, XSVF_ERROR_DATAOVERFLOW, XSVF_ERROR_ENDOFFILE, and XSVF_ERROR_NONE.
Referenced by Run().
{
    mErrorCode  = XSVF_ERROR_NONE;
    if ( ! lvTdi.ReadXSVF( 4 ) )
    {
        mErrorCode = XSVF_ERROR_ENDOFFILE;
        return;
        }
    mShiftLengthBits  = lvTdi.GetValue ();
    mShiftLengthBytes = GetAsNumBytes( mShiftLengthBits );
    TRACE_DBG( 3, "      DR Size      = %ld\n", mShiftLengthBits );
    if ( mShiftLengthBytes > OctetArray::MAX_LEN )
    {
        mErrorCode = XSVF_ERROR_DATAOVERFLOW;
        }
    }
void XSVF_Class::Do_XSDRTDO (void) [private]
Definition at line 1401 of file xsvfPlayer.cpp.
References BasicXSDRTDO(), mMaxRepeat, mRunTestTime, and mTapStateEndDR.
Referenced by Run().
{
    BasicXSDRTDO( mTapStateEndDR, mRunTestTime, /*captureTDO=*/ true, mMaxRepeat );
    }
void XSVF_Class::Do_XSETSDRMASKS (void) [private]
Definition at line 1414 of file xsvfPlayer.cpp.
References lvAddressMask, lvDataMask, mErrorCode, mShiftLengthBytes, OctetArray::ReadXSVF(), TRACE_ARR, TRACE_DBG, XSVF_ERROR_ENDOFFILE, and XSVF_ERROR_NONE.
Referenced by Run().
{
    // Read the addressMask
    //
    if ( ! lvAddressMask.ReadXSVF( mShiftLengthBytes ) )
    {
        mErrorCode = XSVF_ERROR_ENDOFFILE;
        return;
        }
    // Read the dataMask
    //
    if ( ! lvDataMask.ReadXSVF( mShiftLengthBytes ) )
    {
        mErrorCode = XSVF_ERROR_ENDOFFILE;
        return;
        }
    TRACE_DBG( 4, "       Addr Mask   = " );
    TRACE_ARR( 4, &lvAddressMask );
    TRACE_DBG( 4, "\n" );
    TRACE_DBG( 4, "       Data Mask   = " );
    TRACE_ARR( 4, &lvDataMask );
    TRACE_DBG( 4, "\n" );
    mErrorCode = XSVF_ERROR_NONE;
    }
void XSVF_Class::Do_XSDRINC (void) [private]
Definition at line 1456 of file xsvfPlayer.cpp.
References DoSDRMasking(), GetAsNumBytes(), OctetArray::len, lvDataMask, lvNextData, lvTdi, mErrorCode, mMaxRepeat, mRunTestTime, mShiftLengthBits, mShiftLengthBytes, mTapStateEndDR, ReadXSVF(), OctetArray::ReadXSVF(), Shift(), OctetArray::val, XSVF_ERROR_ENDOFFILE, and XTAPSTATE_SHIFTDR.
Referenced by Run().
{
    if ( ! lvTdi.ReadXSVF( mShiftLengthBytes ) )
    {
        mErrorCode = XSVF_ERROR_ENDOFFILE;
        return;
        }
    Shift
    (
        XTAPSTATE_SHIFTDR, mShiftLengthBits, mTapStateEndDR, mRunTestTime,
        /*captureTDO=*/true, mMaxRepeat
        );
    if ( ! mErrorCode )
    {
        // Calculate number of data mask bits
        //
        int iDataMaskLen = 0;
        for ( int i = 0; i < lvDataMask.len; ++i )
        {
            for( int ucDataMask  = lvDataMask.val[ i ]; ucDataMask; ucDataMask >>= 1 )
            {
                iDataMaskLen += ( ucDataMask & 1 );
                }
            }
        // Get the number of data pieces, i.e. number of times to shift
        //
        int ucNumTimes = ReadXSVF ();
        if ( ucNumTimes < 0 )
        {
            mErrorCode = XSVF_ERROR_ENDOFFILE;
            return;
            }
        // For numTimes, get data, fix TDI, and shift
        //
        for ( int i = 0; ! mErrorCode && i < ucNumTimes; ++i )
        {
            if ( ! lvNextData.ReadXSVF( GetAsNumBytes( iDataMaskLen ) ) )
            {
                mErrorCode = XSVF_ERROR_ENDOFFILE;
                return;
                }
            DoSDRMasking ();
            Shift
            (
                XTAPSTATE_SHIFTDR, mShiftLengthBits, mTapStateEndDR, mRunTestTime,
                /*captureTDO=*/ true, mMaxRepeat
                );
            }
        }
    }
void XSVF_Class::Do_XSDRBCE (void) [private]
Definition at line 1522 of file xsvfPlayer.cpp.
References BasicXSDRTDO(), mCommand, mTapStateEndDR, XSDRE, and XTAPSTATE_SHIFTDR.
Referenced by Run().
{
    BasicXSDRTDO( mCommand == XSDRE ? mTapStateEndDR : XTAPSTATE_SHIFTDR );
    }
void XSVF_Class::Do_XSDRTDOBCE (void) [private]
Definition at line 1536 of file xsvfPlayer.cpp.
References BasicXSDRTDO(), mCommand, mTapStateEndDR, XSDRTDOE, and XTAPSTATE_SHIFTDR.
Referenced by Run().
{
    BasicXSDRTDO( mCommand == XSDRTDOE ? mTapStateEndDR : XTAPSTATE_SHIFTDR );
    }
void XSVF_Class::Do_XSTATE (void) [private]
Definition at line 1547 of file xsvfPlayer.cpp.
References GotoTapState(), mErrorCode, ReadXSVF(), XSVF_ERROR_ENDOFFILE, XSVF_ERROR_ILLEGALSTATE, and XTAPSTATE_LAST.
Referenced by Run().
{
    int ucNextState = ReadXSVF ();
    if ( ucNextState < 0 )
    {
        mErrorCode = XSVF_ERROR_ENDOFFILE;
        return;
        }
    if ( ucNextState < XTAPSTATE_FIRST || ucNextState > XTAPSTATE_LAST )
    {
        mErrorCode = XSVF_ERROR_ILLEGALSTATE;
        return;
        }
    GotoTapState( XSVF_TAPSTATE( ucNextState ) );
    }
void XSVF_Class::Do_XENDXR (void) [private]
Definition at line 1572 of file xsvfPlayer.cpp.
References mCommand, mErrorCode, mTapStateEndDR, mTapStateEndIR, pzTapState, ReadXSVF(), TRACE_DBG, XENDIR, XENDXR_PAUSE, XENDXR_RUNTEST, XSVF_ERROR_ENDOFFILE, XSVF_ERROR_ILLEGALSTATE, XSVF_ERROR_NONE, XTAPSTATE_PAUSEDR, XTAPSTATE_PAUSEIR, and XTAPSTATE_RUNTEST.
Referenced by Run().
{
    mErrorCode  = XSVF_ERROR_NONE;
    int ucEndState = ReadXSVF ();
    if ( ucEndState < 0 )
    {
        mErrorCode = XSVF_ERROR_ENDOFFILE;
        return;
        }
    if ( ucEndState != XENDXR_RUNTEST && ucEndState != XENDXR_PAUSE )
    {
        mErrorCode = XSVF_ERROR_ILLEGALSTATE;
        }
    else
    {
        if ( mCommand == XENDIR )
        {
            if ( ucEndState == XENDXR_RUNTEST )
            {
                mTapStateEndIR = XTAPSTATE_RUNTEST;
                }
            else
            {
                mTapStateEndIR = XTAPSTATE_PAUSEIR;
                }
            TRACE_DBG( 3, "      End IR State = %s\n", pzTapState[ mTapStateEndIR ] );
            }
        else // XENDDR
        {
            if ( ucEndState == XENDXR_RUNTEST )
            {
                mTapStateEndDR = XTAPSTATE_RUNTEST;
                }
            else
            {
                mTapStateEndDR = XTAPSTATE_PAUSEDR;
                }
            TRACE_DBG( 3, "      End DR State = %s\n", pzTapState[ mTapStateEndDR ] );
            }
        }
    }
void XSVF_Class::Do_XCOMMENT (void) [private]
Definition at line 1624 of file xsvfPlayer.cpp.
References mErrorCode, ReadXSVF(), TRACE_DBG, XSVF_ERROR_ENDOFFILE, and XSVF_ERROR_NONE.
Referenced by Run().
{
    // Read through the comment to the end '\0' and display message.
    //
    TRACE_DBG( 1, "      " );
    for( ;; )
    {
        int ucText = ReadXSVF ();
        if ( ucText < 0 )
        {
            mErrorCode = XSVF_ERROR_ENDOFFILE;
            return;
            }
        if ( ucText == 0 )
        {
            TRACE_DBG( 1, "\n" );
            break;
            }
        else
        {
            TRACE_DBG( 1, "%c", ucText );
            }
        }
    mErrorCode = XSVF_ERROR_NONE;
    }
void XSVF_Class::Do_XWAIT (void) [private]
Definition at line 1660 of file xsvfPlayer.cpp.
References OctetArray::GetValue(), GotoTapState(), lvTdi, mErrorCode, mParseOnly, mTapState, pzTapState, OctetArray::ReadXSVF(), TRACE_DBG, uSleep(), OctetArray::val, XSVF_ERROR_ENDOFFILE, XSVF_ERROR_ILLEGALSTATE, XSVF_ERROR_NONE, and XTAPSTATE_LAST.
Referenced by Run().
{
    // Get Parameters
    // <wait_state>
    //
    if ( ! lvTdi.ReadXSVF( 1 ) )
    {
        mErrorCode = XSVF_ERROR_ENDOFFILE;
        return;
        }
    int ucWaitState = lvTdi.val[0];
    if ( ucWaitState < XTAPSTATE_FIRST || ucWaitState > XTAPSTATE_LAST )
    {
        mErrorCode = XSVF_ERROR_ILLEGALSTATE;
        return;
        }
    // <end_state>
    //
    if ( ! lvTdi.ReadXSVF( 1 ) )
    {
        mErrorCode = XSVF_ERROR_ENDOFFILE;
        return;
        }
    int ucEndState = lvTdi.val[0];
    if ( ucEndState < XTAPSTATE_FIRST || ucEndState > XTAPSTATE_LAST )
    {
        mErrorCode = XSVF_ERROR_ILLEGALSTATE;
        return;
        }
    // <wait_time>
    //
    if ( ! lvTdi.ReadXSVF( 4 ) )
    {
        mErrorCode = XSVF_ERROR_ENDOFFILE;
        return;
        }
    long lWaitTime = lvTdi.GetValue ();
    TRACE_DBG( 3, "      Wait / State = %s, Time = %ld usec\n",
               pzTapState[ ucWaitState ], lWaitTime );
    // If not already in <wait_state>, go to <wait_state>
    //
    if ( mTapState != ucWaitState )
    {
        GotoTapState( XSVF_TAPSTATE( ucWaitState ) );
        }
    // Wait for <wait_time> microseconds
    //
    if ( ! mParseOnly )
    {
        uSleep( lWaitTime );
        }
    // If not already in <end_state>, go to <end_state>
    //
    if ( mTapState != ucEndState )
    {
        GotoTapState( XSVF_TAPSTATE( ucEndState ) );
        }
    mErrorCode = XSVF_ERROR_NONE;
    }
void XSVF_Class::Initialize (int traceLevel, bool parseOnly)
Definition at line 1747 of file xsvfPlayer.cpp.
References GotoTapState(), OctetArray::len, lvAddressMask, lvDataMask, lvNextData, lvTdi, lvTdoCaptured, lvTdoExpected, lvTdoMask, mCommand, mCommandCount, mComplete, mErrorCode, mMaxRepeat, mParseOnly, mRunTestTime, mShiftLengthBits, mShiftLengthBytes, mTapState, mTapStateEndDR, mTapStateEndIR, mTraceLevel, TRACE_DBG, XCOMPLETE, XSVF_ERROR_NONE, XTAPSTATE_RESET, and XTAPSTATE_RUNTEST.
Referenced by xsvfExecute().
{
    mTraceLevel       = traceLevel;
    mParseOnly        = parseOnly;
    TRACE_DBG( 1, "\nXSVF_Class: Initialize: Verbose=%d%s\n",
                  mTraceLevel, mParseOnly ? ", Parse Only" : "" );
    mComplete         = false;
    mCommand          = XCOMPLETE;
    mCommandCount     = 0;
    mErrorCode        = XSVF_ERROR_NONE;
    mTapState         = XTAPSTATE_RESET;
    mTapStateEndIR    = XTAPSTATE_RUNTEST;
    mTapStateEndDR    = XTAPSTATE_RUNTEST;
    mMaxRepeat        = 0;
    mRunTestTime      = 0L;
    mShiftLengthBits  = 0L;
    mShiftLengthBytes = 0;
    lvTdi.len         = 0;
    lvTdoExpected.len = 0;
    lvTdoCaptured.len = 0;
    lvTdoMask.len     = 0;
    lvAddressMask.len = 0;
    lvDataMask.len    = 0;
    lvNextData.len    = 0;
    // Initialize the TAPs
    //
    GotoTapState( XTAPSTATE_RESET );
    }
int XSVF_Class::Run (void)
Definition at line 1798 of file xsvfPlayer.cpp.
References Do_ILLEGALCMD(), Do_XCOMMENT(), Do_XCOMPLETE(), Do_XENDXR(), Do_XREPEAT(), Do_XRUNTEST(), Do_XSDR(), Do_XSDRBCE(), Do_XSDRINC(), Do_XSDRSIZE(), Do_XSDRTDO(), Do_XSDRTDOBCE(), Do_XSETSDRMASKS(), Do_XSIR(), Do_XSIR2(), Do_XSTATE(), Do_XTDOMASK(), Do_XWAIT(), GotoTapState(), lvTdoCaptured, lvTdoExpected, lvTdoMask, mCommand, mCommandCount, mComplete, mErrorCode, pzCommandName, pzErrorName, ReadXSVF(), TRACE_ARR, TRACE_DBG, XCMDRESERVED5, XCMDRESERVED6, XCOMMENT, XCOMPLETE, XENDDR, XENDIR, XLASTCMD, XREPEAT, XRUNTEST, XSDR, XSDRB, XSDRC, XSDRE, XSDRINC, XSDRSIZE, XSDRTDO, XSDRTDOB, XSDRTDOC, XSDRTDOE, XSETSDRMASKS, XSIR, XSIR2, XSTATE, XSVF_ERROR_ENDOFFILE, XSVF_ERROR_ILLEGALCMD, XSVF_ERROR_LAST, XSVF_ERROR_MAXRETRIES, XSVF_ERROR_TDOMISMATCH, XSVF_ERROR_UNKNOWN, XTAPSTATE_RESET, XTDOMASK, and XWAIT.
Referenced by xsvfExecute().
{
    // Process the XSVF commands
    //
    while( ! mErrorCode && ! mComplete )
    {
        // Read 1 byte for the instruction
        //
        mCommand = ReadXSVF ();
        if ( mCommand < 0 )
        {
            mErrorCode = XSVF_ERROR_ENDOFFILE;
            break;
            }
        if ( mCommand >= XLASTCMD )
        {
            mErrorCode = XSVF_ERROR_ILLEGALCMD;
            break;
            }
        ++mCommandCount;
        TRACE_DBG( 4, "\n" );
        TRACE_DBG( 2, "%04ld: %s\n", mCommandCount, pzCommandName[ mCommand ] );
        // Execute the command. Func sets error code.
        //
        switch( mCommand )
        {
            case XCOMPLETE      : Do_XCOMPLETE   (); break;
            case XTDOMASK       : Do_XTDOMASK    (); break;
            case XSIR           : Do_XSIR        (); break;
            case XSDR           : Do_XSDR        (); break;
            case XRUNTEST       : Do_XRUNTEST    (); break;
            case XCMDRESERVED5  : Do_ILLEGALCMD  (); break;
            case XCMDRESERVED6  : Do_ILLEGALCMD  (); break;
            case XREPEAT        : Do_XREPEAT     (); break;
            case XSDRSIZE       : Do_XSDRSIZE    (); break;
            case XSDRTDO        : Do_XSDRTDO     (); break;
            case XSETSDRMASKS   : Do_XSETSDRMASKS(); break;
            case XSDRINC        : Do_XSDRINC     (); break;
            case XSDRB          : Do_XSDRBCE     (); break;
            case XSDRC          : Do_XSDRBCE     (); break;
            case XSDRE          : Do_XSDRBCE     (); break;
            case XSDRTDOB       : Do_XSDRTDOBCE  (); break;
            case XSDRTDOC       : Do_XSDRTDOBCE  (); break;
            case XSDRTDOE       : Do_XSDRTDOBCE  (); break;
            case XSTATE         : Do_XSTATE      (); break;
            case XENDIR         : Do_XENDXR      (); break;
            case XENDDR         : Do_XENDXR      (); break;
            case XSIR2          : Do_XSIR2       (); break;
            case XCOMMENT       : Do_XCOMMENT    (); break;
            case XWAIT          : Do_XWAIT       (); break;
            default             : Do_ILLEGALCMD  (); break;
        }
    }
    if ( mErrorCode )
    {
        TRACE_DBG( 0, "\nERROR: %s; Near XSVF ASCII File Line #%ld\n",
            pzErrorName[ mErrorCode < XSVF_ERROR_LAST ? mErrorCode : XSVF_ERROR_UNKNOWN ],
            mCommandCount
            );
        if ( mErrorCode == XSVF_ERROR_ILLEGALCMD )
        {
            TRACE_DBG( 0,
                "Encountered unsupported command 0x%02X (%s)\n",
                mCommand,
                mCommand >= 0 && mCommand < XLASTCMD
                    ? pzCommandName[ mCommand ] : "Unknown"
                );
            }
        else if ( mErrorCode == XSVF_ERROR_MAXRETRIES
               || mErrorCode == XSVF_ERROR_TDOMISMATCH )
        {
            TRACE_DBG( 0, "TDO Captured = " );
            TRACE_ARR( 0, &lvTdoCaptured );
            TRACE_DBG( 0, "\n" );
            TRACE_DBG( 0, "TDO Expected = " );
            TRACE_ARR( 0, &lvTdoExpected );
            TRACE_DBG( 0, "\n" );
            TRACE_DBG( 0, "TDO Mask     = " );
            TRACE_ARR( 0, &lvTdoMask );
            TRACE_DBG( 0, "\n" );
            }
        // Initialize the TAPs
        //
        TRACE_DBG( 3, "\n" );
        int rc = mErrorCode; // Remember error code
        GotoTapState( XTAPSTATE_RESET );
        mErrorCode = rc; // Restore error code
        }
    else
    {
        TRACE_DBG( 0, "\nSUCCESS: Completed XSVF execution (%ld commands).\n",
                      mCommandCount );
        }
    TRACE_DBG( 0, "\n" );
    return mErrorCode;
    }
Member Data Documentation
int XSVF_Class::mTraceLevel [private]
Definition at line 257 of file xsvfPlayer.cpp.
Referenced by Initialize(), and XSVF_Class().
const char * XSVF_Class::pzCommandName [static, private]
Initial value:
{
    "XCOMPLETE",
    "XTDOMASK",
    "XSIR",
    "XSDR",
    "XRUNTEST",
    "Reserved5",
    "Reserved6",
    "XREPEAT",
    "XSDRSIZE",
    "XSDRTDO",
    "XSETSDRMASKS",
    "XSDRINC",
    "XSDRB",
    "XSDRC",
    "XSDRE",
    "XSDRTDOB",
    "XSDRTDOC",
    "XSDRTDOE",
    "XSTATE",
    "XENDIR",
    "XENDDR",
    "XSIR2",
    "XCOMMENT",
    "XWAIT"
    }
Definition at line 258 of file xsvfPlayer.cpp.
Referenced by Run().
const char * XSVF_Class::pzTapState [static, private]
Initial value:
{
    "RESET",
    "RUNTEST/IDLE",
    "DRSELECT",
    "DRCAPTURE",
    "DRSHIFT",
    "DREXIT1",
    "DRPAUSE",
    "DREXIT2",
    "DRUPDATE",
    "IRSELECT",
    "IRCAPTURE",
    "IRSHIFT",
    "IREXIT1",
    "IRPAUSE",
    "IREXIT2",
    "IRUPDATE"
    }
Definition at line 259 of file xsvfPlayer.cpp.
Referenced by Do_XENDXR(), and Do_XWAIT().
const char * XSVF_Class::pzErrorName [static, private]
Initial value:
{
    "No error",
    "Unknown",
    "TDO mismatch",
    "TDO mismatch and exceeded max retries",
    "Unsupported XSVF command",
    "Illegal state specification",
    "Data overflows allocated MAX_LEN buffer size",
    "Premature end of XSVF data"
    }
Definition at line 260 of file xsvfPlayer.cpp.
Referenced by Run().
bool XSVF_Class::mParseOnly [private]
Definition at line 330 of file xsvfPlayer.cpp.
Referenced by Do_XWAIT(), and Initialize().
bool XSVF_Class::mComplete [private]
Definition at line 331 of file xsvfPlayer.cpp.
Referenced by Do_XCOMPLETE(), Initialize(), and Run().
int XSVF_Class::mCommand [private]
Definition at line 332 of file xsvfPlayer.cpp.
Referenced by Do_XENDXR(), Do_XSDRBCE(), Do_XSDRTDOBCE(), Initialize(), and Run().
long XSVF_Class::mCommandCount [private]
Definition at line 333 of file xsvfPlayer.cpp.
Referenced by Initialize(), and Run().
int XSVF_Class::mErrorCode [private]
Definition at line 334 of file xsvfPlayer.cpp.
Referenced by BasicXSDRTDO(), Do_ILLEGALCMD(), Do_XCOMMENT(), Do_XCOMPLETE(), Do_XENDXR(), Do_XREPEAT(), Do_XRUNTEST(), Do_XSDR(), Do_XSDRINC(), Do_XSDRSIZE(), Do_XSETSDRMASKS(), Do_XSIR(), Do_XSIR2(), Do_XSTATE(), Do_XTDOMASK(), Do_XWAIT(), Initialize(), and Run().
XSVF_TAPSTATE XSVF_Class::mTapState [private]
Definition at line 338 of file xsvfPlayer.cpp.
Referenced by Do_XWAIT(), and Initialize().
XSVF_TAPSTATE XSVF_Class::mTapStateEndIR [private]
Definition at line 339 of file xsvfPlayer.cpp.
Referenced by Do_XENDXR(), Do_XSIR(), Do_XSIR2(), and Initialize().
XSVF_TAPSTATE XSVF_Class::mTapStateEndDR [private]
Definition at line 340 of file xsvfPlayer.cpp.
Referenced by Do_XENDXR(), Do_XSDR(), Do_XSDRBCE(), Do_XSDRINC(), Do_XSDRTDO(), Do_XSDRTDOBCE(), and Initialize().
int XSVF_Class::mMaxRepeat [private]
Definition at line 344 of file xsvfPlayer.cpp.
Referenced by Do_XREPEAT(), Do_XSDR(), Do_XSDRINC(), Do_XSDRTDO(), and Initialize().
long XSVF_Class::mRunTestTime [private]
Definition at line 345 of file xsvfPlayer.cpp.
Referenced by Do_XRUNTEST(), Do_XSDR(), Do_XSDRINC(), Do_XSDRTDO(), Do_XSIR(), Do_XSIR2(), and Initialize().
long XSVF_Class::mShiftLengthBits [private]
Definition at line 349 of file xsvfPlayer.cpp.
Referenced by BasicXSDRTDO(), Do_XSDR(), Do_XSDRINC(), Do_XSDRSIZE(), and Initialize().
int XSVF_Class::mShiftLengthBytes [private]
Definition at line 350 of file xsvfPlayer.cpp.
Referenced by BasicXSDRTDO(), Do_XSDR(), Do_XSDRINC(), Do_XSDRSIZE(), Do_XSETSDRMASKS(), Do_XTDOMASK(), and Initialize().
OctetArray XSVF_Class::lvTdi [private]
Definition at line 354 of file xsvfPlayer.cpp.
Referenced by BasicXSDRTDO(), Do_XRUNTEST(), Do_XSDR(), Do_XSDRINC(), Do_XSDRSIZE(), Do_XSIR(), Do_XSIR2(), Do_XWAIT(), DoSDRMasking(), and Initialize().
OctetArray XSVF_Class::lvTdoExpected [private]
Definition at line 355 of file xsvfPlayer.cpp.
Referenced by BasicXSDRTDO(), Initialize(), and Run().
OctetArray XSVF_Class::lvTdoCaptured [private]
Definition at line 356 of file xsvfPlayer.cpp.
Referenced by Initialize(), and Run().
OctetArray XSVF_Class::lvTdoMask [private]
Definition at line 357 of file xsvfPlayer.cpp.
Referenced by Do_XTDOMASK(), Initialize(), and Run().
OctetArray XSVF_Class::lvAddressMask [private]
Definition at line 361 of file xsvfPlayer.cpp.
Referenced by Do_XSETSDRMASKS(), DoSDRMasking(), and Initialize().
OctetArray XSVF_Class::lvDataMask [private]
Definition at line 362 of file xsvfPlayer.cpp.
Referenced by Do_XSDRINC(), Do_XSETSDRMASKS(), DoSDRMasking(), and Initialize().
OctetArray XSVF_Class::lvNextData [private]
Definition at line 363 of file xsvfPlayer.cpp.
Referenced by Do_XSDRINC(), DoSDRMasking(), and Initialize().
The documentation for this class was generated from the following file:
src/fpga/xsvfPlayer.cpp