XPU-DSAM7S: src/inc/fpga.hpp File Reference
fpga.hpp File Reference
Defines
#define FPGA_JTAG_TCK AT91C_PIO_PA1
#define FPGA_JTAG_TMS AT91C_PIO_PA2
#define FPGA_JTAG_TDI AT91C_PIO_PA3
#define FPGA_JTAG_TDO AT91C_PIO_PA23
#define FPGA_RESET AT91C_PIO_PA7
#define FPGA_A0 AT91C_PIO_PA24
#define FPGA_A1 AT91C_PIO_PA25
#define FPGA_A2 AT91C_PIO_PA26
#define FPGA_RDn AT91C_PIO_PA27
#define FPGA_WRn AT91C_PIO_PA28
#define FPGA_INTn AT91C_PIO_PA20
#define FPGA_D0 AT91C_PIO_PA8
#define FPGA_D1 AT91C_PIO_PA9
#define FPGA_D2 AT91C_PIO_PA10
#define FPGA_D3 AT91C_PIO_PA11
#define FPGA_D4 AT91C_PIO_PA12
#define FPGA_D5 AT91C_PIO_PA13
#define FPGA_D6 AT91C_PIO_PA14
#define FPGA_D7 AT91C_PIO_PA15
#define FPGA_DATA
#define FPGA_ADDR (FPGA_A0 | FPGA_A1 | FPGA_A2)
Enumerations
enum {
XPI_R_INT_REQUEST = 0, XPI_R_P0_SC_CTX = 1, XPI_R_P0_SC_CRX = 2, XPI_R_P0_SC_EIRQ = 3,
XPI_R_P0_FC_FDFA = 4, XPI_R_P0_FC_SENSE = 5, XPI_R_P0_FC_STATUS = 6, XPI_R_P0_GLB_STATUS = 7,
XPI_R_P1_IRQ_ENABLE = 1, XPI_R_P1_MAGIC_LSB = 4, XPI_R_P1_MAGIC_MSB = 5, XPI_R_P1_BOARD_POS = 7,
XPI_R_P2_PCM_ACK = 0, XPI_R_P2_PCM_R0 = 4, XPI_R_P2_PCM_R1 = 5, XPI_R_P2_PCM_T0 = 6,
XPI_R_P2_PCM_T1 = 7
}
enum {
XPI_W_PAGE_ADDR = 0, XPI_W_P0_IRQ_ENABLE = 1, XPI_W_P0_IRQ_DISABLE = 2, XPI_W_P0_LED_SET = 3,
XPI_W_P0_LED_CLEAR = 4, XPI_W_P0_FC_CONTROL = 5, XPI_W_P0_GLB_CONTROL = 7, XPI_W_P1_SC_CTX_DATA = 1,
XPI_W_P1_SC_CTX_INCFIFO = 2, XPI_W_P2_PCM_R0 = 4, XPI_W_P2_PCM_R1 = 5, XPI_W_P2_PCM_T0 = 6,
XPI_W_P2_PCM_T1 = 7
}
enum {
XPI_IRQ_CTXE = 0x20, XPI_IRQ_PCM = 0x10, XPI_IRQ_EIRQ = 0x08, XPI_IRQ_CRX = 0x04,
XPI_IRQ_CTX = 0x02, XPI_IRQ_FC = 0x01, XPI_LED_R = 0x04, XPI_LED_Y = 0x02,
XPI_LED_G = 0x01, XPI_FC_SENSE = 0x08, XPI_FC_FCE = 0x04, XPI_FC_FCD = 0x02,
XPI_FC_FCC = 0x01, XPI_GLB_MCPU = 0x01, XPI_GLB_EIRQ = 0x02, XPI_GLB_MCTX_BUSY = 0x04
}
Functions
static void FPGA_BegWrite (void)
static void FPGA_BegRead (void)
static void FPGA_Write (uint addr, uint data)
static uint FPGA_Read (uint addr)
static void FPGA_SetReset (bool reset=true)
static bool FPGA_IsReset (void)
static void FPGA_PulseReset (void)
bool FPGA_FC_Command (uint cmd)
Define Documentation
#define FPGA_A0 AT91C_PIO_PA24
Definition at line 18 of file fpga.hpp.
#define FPGA_A1 AT91C_PIO_PA25
Definition at line 19 of file fpga.hpp.
#define FPGA_A2 AT91C_PIO_PA26
Definition at line 20 of file fpga.hpp.
#define FPGA_ADDR (FPGA_A0 | FPGA_A1 | FPGA_A2)
Definition at line 39 of file fpga.hpp.
Referenced by DEV_Init1().
#define FPGA_D0 AT91C_PIO_PA8
Definition at line 26 of file fpga.hpp.
#define FPGA_D1 AT91C_PIO_PA9
Definition at line 27 of file fpga.hpp.
#define FPGA_D2 AT91C_PIO_PA10
Definition at line 28 of file fpga.hpp.
#define FPGA_D3 AT91C_PIO_PA11
Definition at line 29 of file fpga.hpp.
#define FPGA_D4 AT91C_PIO_PA12
Definition at line 30 of file fpga.hpp.
#define FPGA_D5 AT91C_PIO_PA13
Definition at line 31 of file fpga.hpp.
#define FPGA_D6 AT91C_PIO_PA14
Definition at line 32 of file fpga.hpp.
#define FPGA_D7 AT91C_PIO_PA15
Definition at line 33 of file fpga.hpp.
#define FPGA_DATA
Value:
(FPGA_D0 | FPGA_D1 | FPGA_D2 | FPGA_D3 \
    | FPGA_D4 | FPGA_D5 | FPGA_D6 | FPGA_D7 )
Definition at line 35 of file fpga.hpp.
Referenced by DEV_Init1(), FPGA_BegRead(), and FPGA_BegWrite().
#define FPGA_INTn AT91C_PIO_PA20
Definition at line 24 of file fpga.hpp.
Referenced by DEV_Init1().
#define FPGA_JTAG_TCK AT91C_PIO_PA1
Definition at line 10 of file fpga.hpp.
Referenced by DEV_Init1(), and SetTCK().
#define FPGA_JTAG_TDI AT91C_PIO_PA3
Definition at line 12 of file fpga.hpp.
Referenced by DEV_Init1(), and SetTDI().
#define FPGA_JTAG_TDO AT91C_PIO_PA23
Definition at line 13 of file fpga.hpp.
Referenced by DEV_Init1(), and GetTDO().
#define FPGA_JTAG_TMS AT91C_PIO_PA2
Definition at line 11 of file fpga.hpp.
Referenced by DEV_Init1(), and SetTMS().
#define FPGA_RDn AT91C_PIO_PA27
Definition at line 21 of file fpga.hpp.
Referenced by DEV_Init1(), FPGA_Read(), and FPGA_Write().
#define FPGA_RESET AT91C_PIO_PA7
Definition at line 17 of file fpga.hpp.
Referenced by DEV_Init1(), FPGA_IsReset(), FPGA_PulseReset(), and FPGA_SetReset().
#define FPGA_WRn AT91C_PIO_PA28
Definition at line 22 of file fpga.hpp.
Referenced by DEV_Init1(), FPGA_Read(), and FPGA_Write().
Enumeration Type Documentation
anonymous enum
Enumerator:
XPI_R_INT_REQUEST
XPI_R_P0_SC_CTX
XPI_R_P0_SC_CRX
XPI_R_P0_SC_EIRQ
XPI_R_P0_FC_FDFA
XPI_R_P0_FC_SENSE
XPI_R_P0_FC_STATUS
XPI_R_P0_GLB_STATUS
XPI_R_P1_IRQ_ENABLE
XPI_R_P1_MAGIC_LSB
XPI_R_P1_MAGIC_MSB
XPI_R_P1_BOARD_POS
XPI_R_P2_PCM_ACK
XPI_R_P2_PCM_R0
XPI_R_P2_PCM_R1
XPI_R_P2_PCM_T0
XPI_R_P2_PCM_T1
Definition at line 43 of file fpga.hpp.
{
    // Page independent
    XPI_R_INT_REQUEST          = 0, // D5..0: CTXE, PCM, EIRQ, CRX, CTX, FC
    // Page 0
    XPI_R_P0_SC_CTX            = 1, // D7..0= CTX data
    XPI_R_P0_SC_CRX            = 2, // D7..0= CRX data
    XPI_R_P0_SC_EIRQ           = 3, // D0= EIRQ
    XPI_R_P0_FC_FDFA           = 4, // D5= FCA5 .. D2= FCA0, D1= FCD1, D0= FCD0
    XPI_R_P0_FC_SENSE          = 5, // D0= SENSE
    XPI_R_P0_FC_STATUS         = 6, // D3= SENSE, D2= FCE, D1= FCD, D0= FCC
    XPI_R_P0_GLB_STATUS        = 7, // D1= EIRQ, D0= MCPU
    // Page 1
    XPI_R_P1_IRQ_ENABLE        = 1, // D5..0= CTXE, PCM, EIRQ, CRX, CTX, FC
    XPI_R_P1_MAGIC_LSB         = 4, // D7..0= '10101010' (0xAA)
    XPI_R_P1_MAGIC_MSB         = 5, // D7..0= '00010001' (0x11)
    XPI_R_P1_BOARD_POS         = 7, // D5..0= KA5..0
    // Page 2
    XPI_R_P2_PCM_ACK           = 0, // Dummy read (data should be ignored)
    XPI_R_P2_PCM_R0            = 4, // D7..0= PCM data
    XPI_R_P2_PCM_R1            = 5, // D7..0= PCM data
    XPI_R_P2_PCM_T0            = 6, // D7..0= PCM data
    XPI_R_P2_PCM_T1            = 7  // D7..0= PCM data
    };
anonymous enum
Enumerator:
XPI_W_PAGE_ADDR
XPI_W_P0_IRQ_ENABLE
XPI_W_P0_IRQ_DISABLE
XPI_W_P0_LED_SET
XPI_W_P0_LED_CLEAR
XPI_W_P0_FC_CONTROL
XPI_W_P0_GLB_CONTROL
XPI_W_P1_SC_CTX_DATA
XPI_W_P1_SC_CTX_INCFIFO
XPI_W_P2_PCM_R0
XPI_W_P2_PCM_R1
XPI_W_P2_PCM_T0
XPI_W_P2_PCM_T1
Definition at line 69 of file fpga.hpp.
{
    // Page independent
    XPI_W_PAGE_ADDR            = 0, // D1..0= A4..3
    // Page 0
    XPI_W_P0_IRQ_ENABLE        = 1, // D5..0= CTXE, PCM, EIRQ, CRX, CTX, FC
    XPI_W_P0_IRQ_DISABLE       = 2, // D5..0= CTXE, PCM, EIRQ, CRX, CTX, FC
    XPI_W_P0_LED_SET           = 3, // D2= LED_R, D1= LED_Y, D0= LED_G
    XPI_W_P0_LED_CLEAR         = 4, // D2= LED_R, D1= LED_Y, D0= LED_G
    XPI_W_P0_FC_CONTROL        = 5, // D2= FCE, D1= FCD, D0= FCC
    XPI_W_P0_GLB_CONTROL       = 7, // D0= MCPU
    // Page 1
    XPI_W_P1_SC_CTX_DATA       = 1, // D7..0= CTX data
    XPI_W_P1_SC_CTX_INCFIFO    = 2, // D7..0= ignored; inc FIFO & enable CTXE
    // Page 2
    XPI_W_P2_PCM_R0            = 4, // D5..0= PCM time slot
    XPI_W_P2_PCM_R1            = 5, // D5..0= PCM time slot
    XPI_W_P2_PCM_T0            = 6, // D5..0= PCM time slot
    XPI_W_P2_PCM_T1            = 7  // D5..0= PCM time slot
    };
anonymous enum
Enumerator:
XPI_IRQ_CTXE
XPI_IRQ_PCM
XPI_IRQ_EIRQ
XPI_IRQ_CRX
XPI_IRQ_CTX
XPI_IRQ_FC
XPI_LED_R
XPI_LED_Y
XPI_LED_G
XPI_FC_SENSE
XPI_FC_FCE
XPI_FC_FCD
XPI_FC_FCC
XPI_GLB_MCPU
XPI_GLB_EIRQ
XPI_GLB_MCTX_BUSY
Definition at line 91 of file fpga.hpp.
{
    XPI_IRQ_CTXE        = 0x20, // CTX empty
    XPI_IRQ_PCM         = 0x10, // PCM frame sync
    XPI_IRQ_EIRQ        = 0x08, // EIRQ changed event
    XPI_IRQ_CRX         = 0x04, // CRX data received event
    XPI_IRQ_CTX         = 0x02, // CTX data received event
    XPI_IRQ_FC          = 0x01, // FC data received event
    XPI_LED_R           = 0x04, // Red LED
    XPI_LED_Y           = 0x02, // Yellow LED
    XPI_LED_G           = 0x01, // Green LED
    XPI_FC_SENSE        = 0x08, // SENSE bit
    XPI_FC_FCE          = 0x04, // FCE bit
    XPI_FC_FCD          = 0x02, // FCD bit
    XPI_FC_FCC          = 0x01, // FCC bit
    XPI_GLB_MCPU        = 0x01, // MCPU bit
    XPI_GLB_EIRQ        = 0x02, // EIRQ bit
    XPI_GLB_MCTX_BUSY   = 0x04, // MCTX_BUSY bit
    };
Function Documentation
static void FPGA_BegRead (void) [inline, static]
Definition at line 119 of file fpga.hpp.
References FPGA_DATA.
Referenced by FPGA_FC_Command(), XPI::InitializeFPGA(), XPI::On_CRX(), XPI::On_CTX(), XPI::On_CTXE(), XPI::On_EIRQ(), XPI::On_FC(), XPI::On_Timer(), XPI::PollNextBoard(), portTASK_FUNCTION(), USBRCVR::Receiver(), and XPI::StartTransmissionIfIdle().
{
    AT91F_PIO_OutputDisable( AT91C_BASE_PIOA, FPGA_DATA );
    }
static void FPGA_BegWrite (void) [inline, static]
Definition at line 114 of file fpga.hpp.
References FPGA_DATA.
Referenced by FPGA_FC_Command(), XPI::InitializeFPGA(), XPI::On_CRX(), XPI::On_CTX(), XPI::On_CTXE(), XPI::On_EIRQ(), XPI::On_FC(), XPI::On_Timer(), XPI::PollNextBoard(), portTASK_FUNCTION(), USBRCVR::Receiver(), and XPI::StartTransmissionIfIdle().
{
    AT91F_PIO_OutputEnable( AT91C_BASE_PIOA, FPGA_DATA );
    }
bool FPGA_FC_Command (uint cmd)
Definition at line 51 of file fpga.cpp.
References FPGA_BegRead(), FPGA_BegWrite(), FPGA_Read(), FPGA_Write(), XPI_FC_FCC, XPI_FC_FCD, XPI_FC_FCE, XPI_FC_SENSE, XPI_R_P0_FC_STATUS, XPI_W_P0_FC_CONTROL, and XPI_W_PAGE_ADDR.
Referenced by USBRCVR::Receiver(), and XPI::ResetFPGA().
{
    uchar FCD[ 8 ];
    for ( int i = 0; i < 8; i ++ )
    {
        FCD[ i ] = ( cmd & 0x80 ) ? XPI_FC_FCD : 0;
        cmd <<= 1;
        }
    taskENTER_CRITICAL ();
    FPGA_BegWrite ();
    FPGA_Write( XPI_W_PAGE_ADDR, 0 ); // Page 0
    FPGA_Write( XPI_W_P0_FC_CONTROL, 0x00 ); // FCC, FCD, FCE = 0
    for ( int i = 0; i < 8; i++ )
    {
        FPGA_Write( XPI_W_P0_FC_CONTROL, FCD[ i ] ); // FCD with FCC = 0
        FCD[ i ] |= XPI_FC_FCC;
        FPGA_Write( XPI_W_P0_FC_CONTROL, FCD[ i ] ); // FCD with FCC = 1
        }
    FPGA_Write( XPI_W_P0_FC_CONTROL, XPI_FC_FCE ); // FCE = 1, FCC = 0
    FPGA_BegRead ();
    cmd = FPGA_Read( XPI_R_P0_FC_STATUS );
    FPGA_BegWrite ();
    FPGA_Write( XPI_W_P0_FC_CONTROL, 0x00 ); // FCE = 0
    taskEXIT_CRITICAL ();
    return ( cmd & XPI_FC_SENSE ) != 0; // Return SENSE
    }
static bool FPGA_IsReset (void) [inline, static]
Definition at line 158 of file fpga.hpp.
References FPGA_RESET, and ISSET.
Referenced by XPI::InitializeFPGA().
{
    return ISSET( AT91F_PIO_GetInput( AT91C_BASE_PIOA ), FPGA_RESET );
    }
static void FPGA_PulseReset (void) [inline, static]
Definition at line 163 of file fpga.hpp.
References FPGA_RESET.
Referenced by XPI::InitializeFPGA().
{
    AT91F_PIO_SetOutput( AT91C_BASE_PIOA, FPGA_RESET );
    asm volatile( "NOP" );
    AT91F_PIO_ClearOutput( AT91C_BASE_PIOA, FPGA_RESET );
    }
static uint FPGA_Read (uint addr) [inline, static]
Definition at line 135 of file fpga.hpp.
References FPGA_RDn, and FPGA_WRn.
Referenced by FPGA_FC_Command(), XPI::InitializeFPGA(), XPI::On_CRX(), XPI::On_CTX(), XPI::On_EIRQ(), XPI::On_FC(), portTASK_FUNCTION(), and USBRCVR::Receiver().
{
    AT91F_PIO_ForceOutput( AT91C_BASE_PIOA,
        FPGA_WRn | ( ( addr & 0x7 ) << 24 )
        );
    asm volatile( "NOP" );
    uint data = ( AT91F_PIO_GetInput( AT91C_BASE_PIOA ) >> 8 ) & 0xFF;
    AT91F_PIO_SetOutput( AT91C_BASE_PIOA, FPGA_RDn );
    return data;
    }
static void FPGA_SetReset (bool reset = true) [inline, static]
Definition at line 150 of file fpga.hpp.
References FPGA_RESET.
Referenced by XPI::InitializeFPGA(), and XPI::ResetFPGA().
{
    if ( reset )
        AT91F_PIO_SetOutput( AT91C_BASE_PIOA, FPGA_RESET );
    else
        AT91F_PIO_ClearOutput( AT91C_BASE_PIOA, FPGA_RESET );
    }
static void FPGA_Write (uint addr, uint data) [inline, static]
Definition at line 124 of file fpga.hpp.
References FPGA_RDn, and FPGA_WRn.
Referenced by FPGA_FC_Command(), XPI::InitializeFPGA(), XPI::On_CRX(), XPI::On_CTX(), XPI::On_CTXE(), XPI::On_EIRQ(), XPI::On_FC(), XPI::On_Timer(), XPI::PollNextBoard(), portTASK_FUNCTION(), USBRCVR::Receiver(), and XPI::StartTransmissionIfIdle().
{
    AT91F_PIO_ForceOutput( AT91C_BASE_PIOA,
        FPGA_RDn | ( ( addr & 0x7 ) << 24 ) | ( ( data & 0xFF ) << 8 )
        );
    asm volatile( "NOP" );
    AT91F_PIO_SetOutput( AT91C_BASE_PIOA, FPGA_WRn );
    }