XPU-DSAM7S: src/sam7xpud.cpp File Reference
sam7xpud.cpp File Reference
#include "sam7xpud.hpp"
Functions
portTASK_FUNCTION (MainTimer_Task, pvParameters)
portTASK_FUNCTION (FPGA_IrqTasklet, pvParameters)
void us1_putc (int ch)
void null_putc (int ch)
void usb_putc (int ch)
int main (void)
void ShowStackFreeSpace (xTaskHandle task)
void sysDumpStatus (void)
Variables
static xTaskHandle t1
static xTaskHandle t2
static xTaskHandle t3
static xTaskHandle t4
static xTaskHandle t5
static xTaskHandle t6
Function Documentation
int main (void)
Definition at line 77 of file sam7xpud.cpp.
References t1, t2, t3, t4, t5, t6, and TRACE_INFO.
{
    ////////////////////////////////////////////////////////////////////////////////
    // When using the JTAG debugger the hardware is not always initialised to
    // the correct default state.  This line just ensures that this does not
    // cause all interrupts to be masked at the start
    //
    AT91F_AIC_AcknowledgeIt( AT91C_BASE_AIC );
    ////////////////////////////////////////////////////////////////////////////////
    // Create tasks
    //
    xTaskCreate
    (
        XSVF_Player::MainTask, (const signed portCHAR* const) "XSVF",
        256, NULL, tskIDLE_PRIORITY + 2, &t1
        );
    xTaskCreate
    (
        FPGA_IrqTasklet, (const signed portCHAR* const) "FPGA",
        256, NULL, tskIDLE_PRIORITY + 3, &t2
        );
    xTaskCreate
    (
        XPI::MainTask, (const signed portCHAR* const) "XPI",
        256, NULL, tskIDLE_PRIORITY + 3, &t3
        );
    xTaskCreate
    (
        MainTimer_Task, (const signed portCHAR* const) "LEDT",
        128, NULL, tskIDLE_PRIORITY + 4, &t4
        );
    xTaskCreate
    (
        USBRCVR::MainTask, (const signed portCHAR* const) "USBR",
        256, NULL, tskIDLE_PRIORITY + 5, &t5
        );
    // Initialize transmitter
    xTaskCreate
    (
        USBXMTR::MainTask, (const signed portCHAR* const) "USBT",
        192, NULL, tskIDLE_PRIORITY + 6, &t6
        );
    TRACE_INFO( "--------------------------\n" );
    TRACE_INFO( "Starting FreeRTOS...\n" );
    //-----------------------------------------------------------------------------------
    // Start the scheduler.
    // NOTE: Tasks run in system mode and the scheduler runs in Supervisor mode.
    // The processor MUST be in supervisor mode when vTaskStartScheduler is called.
    //-----------------------------------------------------------------------------------
    vTaskStartScheduler ();
    // We should never get here as control is now taken by the scheduler.
    //
    return 0;
    }
void null_putc (int ch)
Definition at line 36 of file sam7xpud.cpp.
Referenced by USBRCVR::Receiver().
{
    };
portTASK_FUNCTION (FPGA_IrqTasklet , pvParameters)
Definition at line 163 of file fpga.cpp.
References FPGA_BegRead(), FPGA_BegWrite(), FPGA_Read(), FPGA_Write(), XPI::GetNextTimeout(), ISCLEARED, ISR_Wrapper_FPGA(), ISSET, XPI::On_CRX(), XPI::On_CTX(), XPI::On_CTXE(), XPI::On_EIRQ(), XPI::On_FC(), XPI::On_Timer(), PUSHBUTTON1, XPI::ResetFPGA(), XPI::StartTransmissionIfIdle(), TRACE_INFO, tracef(), xSEMA::Wait(), xpi, XPI_IRQ_CRX, XPI_IRQ_CTX, XPI_IRQ_CTXE, XPI_IRQ_EIRQ, XPI_IRQ_FC, XPI_IRQ_PCM, XPI_R_INT_REQUEST, XPI_R_P2_PCM_ACK, and XPI_W_PAGE_ADDR.
{
    (void) pvParameters; // The parameters are not used.
    taskENTER_CRITICAL();
    TRACE_INFO( "%XPI Main Task\n" );
    // Configure FPGA interrupt. Interrupt will be later enabled when entering
    // FPGA communication mode.
    //
    AT91F_PMC_EnablePeriphClock
    (
        AT91C_BASE_PMC, // PIO controller base address
        uint( 1 ) << AT91C_ID_IRQ0
        );
    AT91F_AIC_ConfigureIt
    (
        AT91C_BASE_AIC,
        AT91C_ID_IRQ0,
        AT91C_AIC_PRIOR_HIGHEST,
        AT91C_AIC_SRCTYPE_EXT_LOW_LEVEL,
        ISR_Wrapper_FPGA
        );
    taskEXIT_CRITICAL();
    uint oldState = AT91F_PIO_GetInput( AT91C_BASE_PIOA );
    for( ;; )
    {
        // Calculate elapsed time and decrement timer
        //
        xpi.On_Timer (); // Decrement timer
        if ( ! fpgaEvent.Wait( 1, xpi.GetNextTimeout () ) )
        {
            // Calculate elapsed time and decrement timer
            //
            xpi.On_Timer ();
            // Post xpi.Goto(IDLE) handler
            //
            xpi.StartTransmissionIfIdle ();
            // Check PUSHBUTTON1
            //
            uint newState =  AT91F_PIO_GetInput( AT91C_BASE_PIOA );
            if ( ISSET( oldState, PUSHBUTTON1 ) && ISCLEARED( newState, PUSHBUTTON1 ) )
            {
                }
            oldState = newState;
            continue;
            }
        int irq_count = 10000; // protection from IRQ flood
        while( --irq_count >= 0 )
        {
            // Post xpi.Goto(IDLE) handler
            //
            xpi.StartTransmissionIfIdle ();
            // Set Page 0 and IRQ status bitmap
            //
            taskENTER_CRITICAL ();
            FPGA_BegWrite ();
            FPGA_Write( XPI_W_PAGE_ADDR, 0 ); // Page 0
            FPGA_BegRead ();
            uint irq_list = FPGA_Read( XPI_R_INT_REQUEST );
            taskEXIT_CRITICAL ();
            if ( ! irq_list )
                break;
            if ( irq_list & XPI_IRQ_CTXE ) // CTXE FIFO
            {
                xpi.On_CTXE ();
                }
            if ( irq_list & XPI_IRQ_CTX ) // CTX FIFO
            {
                xpi.On_CTX ();
                }
            if ( irq_list & XPI_IRQ_CRX ) // CRX FIFO
            {
                xpi.On_CRX ();
                }
            if ( irq_list & XPI_IRQ_EIRQ ) // EIRQ FIFO
            {
                xpi.On_EIRQ ();
                }
            if ( irq_list & XPI_IRQ_FC ) // FC FIFO
            {
                xpi.On_FC ();
                }
            if ( irq_list & XPI_IRQ_PCM ) // PCM FIFO
            {
                taskENTER_CRITICAL ();
                FPGA_BegWrite ();
                FPGA_Write( XPI_W_PAGE_ADDR, 2 ); // Page 2
                FPGA_BegRead ();
                // Collect 160 samples and send them as a packet to host.
                // At the same time read-in RPCM data from the last RPCM packet.
                // int octet = FPGA_Read( XPI_R_P2_PCM_R1 );
                // Acknowledge interrupt
                FPGA_Read( XPI_R_P2_PCM_ACK );
                taskEXIT_CRITICAL ();
                }
            }
        // Check IRQ flood
        //
        if ( irq_count < 0 )
        {
            taskENTER_CRITICAL ();
            tracef( 2, "SEVERE ERROR: Too many interrupts\n" );
            taskEXIT_CRITICAL ();
            xpi.ResetFPGA ();
            }
        else
        {
            // Enable FPGA interrupt
            //
            AT91F_AIC_EnableIt( AT91C_BASE_AIC, AT91C_ID_IRQ0 );
            }
        }
    }
portTASK_FUNCTION (MainTimer_Task , pvParameters)
Definition at line 67 of file timerTasks.cpp.
References AT91C_MASTER_CLOCK, Calc_CPU_Usage_Every1s(), FPGA_BegRead(), FPGA_BegWrite(), FPGA_Write(), XPI::IsFpgaOK(), ISR_Wrapper_Timer0(), LED_PIO, LED_POWER, TRACE_INFO, xpi, XPI_LED_G, XPI_W_P0_LED_CLEAR, XPI_W_P0_LED_SET, and XPI_W_PAGE_ADDR.
{
    (void) pvParameters; // The parameters are not used.
    taskENTER_CRITICAL ();
    TRACE_INFO( "Main Timer task\n" );
    ////////////////////////////////////////////////////////////////////////////////
    // Configure Timer 0: 1 ms precision
    //
    AT91F_TC0_CfgPMC ();
    AT91C_BASE_TC0->TC_CMR = AT91C_TC_WAVE | AT91C_TC_WAVESEL_UP_AUTO;
    AT91C_BASE_TC0->TC_IER = AT91C_TC_CPCS;
    AT91F_AIC_ConfigureIt
    (
        AT91C_BASE_AIC,
        AT91C_ID_TC0,
        AT91C_AIC_PRIOR_LOWEST,
        0,
        ISR_Wrapper_Timer0
        );
    AT91F_AIC_EnableIt( AT91C_BASE_AIC, AT91C_ID_TC0 );
    AT91C_BASE_TC0->TC_RC = ( AT91C_MASTER_CLOCK / 2 ) / 1000;
    AT91C_BASE_TC0->TC_CCR = AT91C_TC_CLKEN;
    AT91C_BASE_TC0->TC_CCR = AT91C_TC_SWTRG;
    taskEXIT_CRITICAL ();
    vTaskDelay( 1 ); // Allow ISR_Timer0 to work at least 1 tick
    ////////////////////////////////////////////////////////////////////////////////
    // We need to initialize xLastFlashTime prior to the first call to vTaskDelayUntil ()
    //
    portTickType tLastFlashTime = xTaskGetTickCount ();
    // Loop exactly every 1000 ms
    //
    for(;;)
    {
        static bool once_only = true;
        // Delay for 900 ms the flash period then turn the LED on
        vTaskDelayUntil( &tLastFlashTime, 900 / portTICK_RATE_MS );
        if ( once_only )
        AT91F_PIO_ClearOutput( LED_PIO, LED_POWER ); //LED on
        if ( once_only ) once_only = false;
        if ( xpi.IsFpgaOK () )
        {
            // Set green LED and clear yellow and red LED
            //
            taskENTER_CRITICAL ();
            FPGA_BegWrite ();
            FPGA_Write( XPI_W_PAGE_ADDR, 0 ); // Page 0
            FPGA_Write( XPI_W_P0_LED_CLEAR, XPI_LED_G );
            FPGA_BegRead ();
            taskEXIT_CRITICAL ();
            }
        // Delay for 100 ms the flash period then turn the LED off
        vTaskDelayUntil( &tLastFlashTime, 100 / portTICK_RATE_MS );
        // AT91F_PIO_SetOutput( LED_PIO, LED_POWER ); // LED off
        if ( xpi.IsFpgaOK () )
        {
            // Set green LED and clear yellow and red LED
            //
            taskENTER_CRITICAL ();
            FPGA_BegWrite ();
            FPGA_Write( XPI_W_PAGE_ADDR, 0 ); // Page 0
            FPGA_Write( XPI_W_P0_LED_SET, XPI_LED_G );
            FPGA_BegRead ();
            taskEXIT_CRITICAL ();
            }
        // Snapshot of the CPU usage
        Calc_CPU_Usage_Every1s ();
        }
    }
void ShowStackFreeSpace (xTaskHandle task)
Definition at line 145 of file sam7xpud.cpp.
References tracef().
Referenced by sysDumpStatus().
{
    // Keep this structure synchronized with FreeRTOS's tskTCB
    struct TCB
    {
        volatile portSTACK_TYPE *pxTopOfStack;
        xListItem               xGenericListItem;
        xListItem               xEventListItem;
        unsigned portBASE_TYPE  uxPriority;
        portSTACK_TYPE          *pxStack;
        signed portCHAR         pcTaskName[ configMAX_TASK_NAME_LEN ];
    };
    TCB* pTask = (TCB*)task;
    uchar* pucStackByte = (uchar*)pTask->pxStack;
    uint usCount = 0;
    while( *pucStackByte == 0xa5 )
    {
        pucStackByte++;
        usCount++;
        }
    usCount /= sizeof( portSTACK_TYPE );
    tracef( 2, "Task [%-4s]: Stack %3u\n", pTask->pcTaskName, usCount );
    }
void sysDumpStatus (void)
Definition at line 176 of file sam7xpud.cpp.
References cpu_usage, ShowStackFreeSpace(), t1, t2, t3, t4, t5, t6, tracef(), and vPortGetMaxHeap().
Referenced by USBRCVR::Receiver().
{
    tracef( 2, "CPU %3d.%d%%, ", cpu_usage / 10, cpu_usage % 10 );
    tracef( 2, "Heap %d of %d\n", vPortGetMaxHeap (), configTOTAL_HEAP_SIZE );
    ShowStackFreeSpace( t1 );
    ShowStackFreeSpace( t2 );
    ShowStackFreeSpace( t3 );
    ShowStackFreeSpace( t4 );
    ShowStackFreeSpace( t5 );
    ShowStackFreeSpace( t6 );
    }
void us1_putc (int ch)
Definition at line 25 of file sam7xpud.cpp.
Referenced by DEV_Init2(), and USBRCVR::Receiver().
{
    do ; while( ! AT91F_US_TxReady( (AT91PS_USART)AT91C_BASE_US1) );
    AT91F_US_PutChar( (AT91PS_USART)AT91C_BASE_US1, ch );
    };
void usb_putc (int ch)
Definition at line 44 of file sam7xpud.cpp.
References ATTR_PACKED, dTimerTick, USBXMTR::Put(), usbOut, XPI_IMSG_LOG, XPI_MSG_MAGIC_LSB, and XPI_MSG_MAGIC_MSB.
Referenced by DEV_Init2(), and USBRCVR::Receiver().
{
    // Note: The implementation is NOT THREAD safe and assumes
    // to be used only from single thread (in this case xsvf main task).
    //
    static struct ATTR_PACKED : public XPI_IMSG_HEADER
    {
        uchar data[ 128 ];
        } sMsg;
    static volatile size_t dataLen = 0;
    if ( ch != '\n' )
    {
        sMsg.data[ dataLen++ ] = ch;
        }
    if ( ch == '\n' || dataLen >= sizeof( sMsg.data ) )
    {
        sMsg.magicMSB  = XPI_MSG_MAGIC_MSB;
        sMsg.magicLSB  = XPI_MSG_MAGIC_LSB;
        sMsg.type      = XPI_IMSG_LOG;
        sMsg.subtype   = 0;
        sMsg.timeStamp = dTimerTick;
        usbOut.Put( &sMsg, sizeof( XPI_IMSG_HEADER) + dataLen, 1000 );
        dataLen = 0;
        }
    };
Variable Documentation
xTaskHandle t1 [static]
Definition at line 19 of file sam7xpud.cpp.
Referenced by main(), and sysDumpStatus().
xTaskHandle t2 [static]
Definition at line 19 of file sam7xpud.cpp.
Referenced by main(), and sysDumpStatus().
xTaskHandle t3 [static]
Definition at line 19 of file sam7xpud.cpp.
Referenced by main(), and sysDumpStatus().
xTaskHandle t4 [static]
Definition at line 19 of file sam7xpud.cpp.
Referenced by main(), and sysDumpStatus().
xTaskHandle t5 [static]
Definition at line 19 of file sam7xpud.cpp.
Referenced by main(), and sysDumpStatus().
xTaskHandle t6 [static]
Definition at line 19 of file sam7xpud.cpp.
Referenced by main(), and sysDumpStatus().