XPU-DSAM7S: OctetArray Struct Reference
OctetArray Struct Reference
Public Types
enum { MAX_LEN = 128 }
Public Member Functions
long GetValue (void)
bool IsEqual (OctetArray *plvVal, OctetArray *plvMask)
bool ReadXSVF (int numBytes)
void Add (OctetArray &addendum)
Public Attributes
int len
unsigned char val [MAX_LEN+1]
Detailed Description
Definition at line 94 of file xsvfPlayer.cpp.
Member Enumeration Documentation
anonymous enum
Enumerator:
MAX_LEN
Definition at line 96 of file xsvfPlayer.cpp.
    {
        MAX_LEN = 128    // MAX_LEN = ceil( max( XSDRSIZE ) / 8 )
        //-------------------------------------------------------------------------------
        // This MAX_LEN defines the maximum length (in bytes) of predefined
        // buffers in which the XSVF player stores the current shift data.
        // This length must be greater than the longest shift length (in bytes)
        // in the XSVF files that will be processed.
        //
        // How to find the "shift length" in bits?
        // Look at the ASCII version of the XSVF (generated with the -a option
        // for the SVF2XSVF translator) and search for the XSDRSIZE command
        // with the biggest parameter. XSDRSIZE is equivalent to the SVF's
        // SDR length plus the lengths of applicable HDR and TDR commands.
        // Remember that the MAX_LEN is defined in bytes. Therefore, the
        // minimum MAX_LEN = ceil( max( XSDRSIZE ) / 8 );
        //
        // The following MAX_LEN values have been tested and provide relatively
        // good margin for the corresponding devices:
        //
        //  DEVICE        MAX_LEN   Resulting Max Shift Length (in bits)
        //  ---------     -------   ----------------------------------------------
        //  XC9500/XL/XV       32     256
        //
        //  CoolRunner/II     256    2048  - actual max 1 device = 1035 bits
        //
        //  FPGA              128    1024  - svf2xsvf -rlen 1024
        //
        //  XC18V00/XCF00    1100    8800  - no blank check performed (default)
        //                                 - actual max 1 device = 8192 bits verify
        //                                 - max 1 device = 4096 bits program-only
        //                   2500   20000  - required for blank check
        //                                 - blank check max 1 device = 16384 bits
        //-------------------------------------------------------------------------------
        };
Member Function Documentation
long OctetArray::GetValue (void) [inline]
Definition at line 143 of file xsvfPlayer.cpp.
References len, and val.
Referenced by XSVF_Class::Do_XRUNTEST(), XSVF_Class::Do_XSDRSIZE(), XSVF_Class::Do_XSIR2(), and XSVF_Class::Do_XWAIT().
    {
        long lValue  = 0; // result to hold the accumulated result
        for ( int i = 0; i < len ; ++i )
        {
            lValue <<= 8;        // shift the accumulated result
            lValue |= val[ i];   // get the last byte first
            }
        return lValue;
        }
bool OctetArray::IsEqual (OctetArray * plvVal, OctetArray * plvMask) [inline]
Definition at line 161 of file xsvfPlayer.cpp.
References len, and val.
    {
        // Start at least significant bit and compare bytes
        //
        for ( int i = len - 1; i >= 0; i-- )
        {
            int val1 = val[ i ];
            int val2 = plvVal->val[ i ];
            if ( plvMask )
            {
                int mask = plvMask->val[ i ];
                val1 &= mask;
                val2 &= mask;
                }
            if ( val1 != val2 )
                return false;
            }
        return true;
        }
bool OctetArray::ReadXSVF (int numBytes) [inline]
Definition at line 190 of file xsvfPlayer.cpp.
References len, and val.
Referenced by XSVF_Class::BasicXSDRTDO(), XSVF_Class::Do_XRUNTEST(), XSVF_Class::Do_XSDR(), XSVF_Class::Do_XSDRINC(), XSVF_Class::Do_XSDRSIZE(), XSVF_Class::Do_XSETSDRMASKS(), XSVF_Class::Do_XSIR(), XSVF_Class::Do_XSIR2(), XSVF_Class::Do_XTDOMASK(), and XSVF_Class::Do_XWAIT().
    {
        len = numBytes;
        for ( int i = 0; i < numBytes; i++ )
        {
            int ch = ::ReadXSVF ();
            if ( ch < 0 )
                return false;
            val[ i ] = ch;
            }
        return true;
        }
void OctetArray::Add (OctetArray & addendum) [inline]
Definition at line 210 of file xsvfPlayer.cpp.
References len, and val.
Referenced by XSVF_Class::DoSDRMasking().
    {
        int carry = 0;
        // Start at least significant bit and add bytes
        //
        for ( int i = len - 1; i >= 0; i-- )
        {
            // Add the two bytes plus carry from previous addition
            int sum = val[ i ] + addendum.val[ i ] + carry;
            // Set the i'th byte of the result
            val[ i ] = sum & 0xFF;
            // Set up carry for next byte
            carry = sum >> 8;
            }
        }
Member Data Documentation
int OctetArray::len
Definition at line 136 of file xsvfPlayer.cpp.
Referenced by Add(), XSVF_Class::Do_XSDRINC(), XSVF_Class::DoSDRMasking(), GetValue(), XSVF_Class::Initialize(), IsEqual(), and ReadXSVF().
unsigned char OctetArray::val[MAX_LEN+1]
Definition at line 137 of file xsvfPlayer.cpp.
Referenced by Add(), XSVF_Class::Do_XSDRINC(), XSVF_Class::Do_XWAIT(), XSVF_Class::DoSDRMasking(), GetValue(), IsEqual(), and ReadXSVF().
The documentation for this struct was generated from the following file:
src/fpga/xsvfPlayer.cpp