XPU-DSAM7S: src/usbTasks.cpp File Reference
usbTasks.cpp File Reference
#include "sam7xpud.hpp"
#include <string.h>
Functions
void ISR_USB (void)
portTASK_FUNCTION (USBXMTR::MainTask, pvParameters)
portTASK_FUNCTION (USBRCVR::MainTask, pvParameters)
Variables
USBXMTR usbOut
USBRCVR usbIn
volatile portBASE_TYPE isTaskWokenByPostInUsbIrq = pdFALSE
Function Documentation
void ISR_USB (void)
Definition at line 18 of file usbTasks.cpp.
References USB::CSTD::EventHandler(), isTaskWokenByPostInUsbIrq, and sSer.
Referenced by ISR_Wrapper_USB().
{
    isTaskWokenByPostInUsbIrq = pdFALSE;
    // USB_Handler may also call callbacks established by SER_Read()/SER_Write()
    //
    sSer.EventHandler ();
    AT91F_AIC_AcknowledgeIt( AT91C_BASE_AIC );
    // If an event caused a task to unblock then we call "Yield from ISR" to ensure
    // that the unblocked task is the task that executes when the interrupt completes
    // if the unblocked task has a priority higher than the interrupted task.
    //
    if( isTaskWokenByPostInUsbIrq )
        portYIELD_FROM_ISR();
    }
portTASK_FUNCTION (USBRCVR::MainTask , pvParameters)
Definition at line 206 of file usbTasks.cpp.
References USB::CSTD::Connect(), USB::CSTD::Init(), USBRCVR::Initialize(), USB::CSTD::IsPowered(), USBRCVR::ReadMoreData(), USBRCVR::Receiver(), sSer, and TRACE_INFO.
{
    (void) pvParameters; // The parameters are not used.
#ifdef TR_INFO
    taskENTER_CRITICAL();
    TRACE_INFO( "USBRCVR: Main Task\n" );
    taskEXIT_CRITICAL();
#endif
    // Initialize the USB CDC driver
    sSer.Init ();
#ifdef TR_INFO
    taskENTER_CRITICAL();
    TRACE_INFO( "Connecting USB... \n" );
    taskEXIT_CRITICAL();
#endif
    // Wait for the device to be powered before connecting it
    while ( ! sSer.IsPowered () )
        vTaskDelay( 1 );
    // Connect
    sSer.Connect ();
#ifdef TR_INFO
    taskENTER_CRITICAL();
    TRACE_INFO( "USB Connected\n" );
    taskEXIT_CRITICAL();
#endif
    // Initialize receiver (start receiving data)
    usbIn.Initialize ();
    for(;;)
    {
        usbIn.Receiver ();
        usbIn.ReadMoreData ();
        }
    }
portTASK_FUNCTION (USBXMTR::MainTask , pvParameters)
Definition at line 40 of file usbTasks.cpp.
References USBXMTR::Initialize(), TRACE_INFO, and USBXMTR::Transmitter().
{
    (void) pvParameters; // The parameters are not used.
#ifdef TR_INFO
    taskENTER_CRITICAL ();
    TRACE_INFO( "USBXMTR: Main Task\n" );
    taskEXIT_CRITICAL ();
#endif
    usbOut.Initialize ();
    for(;;)
    {
        usbOut.Transmitter ();
        }
    }
Variable Documentation
volatile portBASE_TYPE isTaskWokenByPostInUsbIrq = pdFALSE
Definition at line 16 of file usbTasks.cpp.
Referenced by ISR_USB(), USBRCVR::OnReceiveUSB(), and USBXMTR::OnSendCompleted().
USBRCVR usbIn
Definition at line 9 of file usbTasks.cpp.
USBXMTR usbOut
Definition at line 8 of file usbTasks.cpp.
Referenced by XSVF_Player::Enable(), XPI::InitializeFPGA(), XSVF_Player::MainLoop(), XPI::On_CRX(), XPI::On_CTX(), XPI::On_EIRQ(), XPI::On_FC(), XPI::Put(), XPI::ResetFPGA(), XPI::Transmitter(), and usb_putc().