XPU-DSAM7S: src/fpga/xsvfTask.cpp File Reference
xsvfTask.cpp File Reference
#include "sam7xpud.hpp"
#include "xsvfPort.hpp"
Functions
portTASK_FUNCTION (XSVF_Player::MainTask, pvParameters)
void uSleep (long microsec)
Variables
XSVF_Player xsvf
Function Documentation
portTASK_FUNCTION (XSVF_Player::MainTask , pvParameters)
Definition at line 22 of file xsvfTask.cpp.
References XSVF_Player::MainLoop().
{
    (void) pvParameters;
    for(;;)
    {
        xsvf.MainLoop ();
        }
    }
void uSleep (long microsec)
Definition at line 164 of file xsvfTask.cpp.
References SetTCK().
Referenced by XSVF_Class::Do_XWAIT(), and XSVF_Class::Shift().
{
    // Note: Manually adjusted (with oscilloscope) to give 1 us per while loop
    // with 50% duty cycle of TCK on AT91SAM7S256 with flash wait state setting
    // AT91C_MC_FWS_1FWS: 2 cycles for Read, 3 for Write operations
    //
    while( microsec-- > 0)
    {
        SetTCK( 0 );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        SetTCK( 1 );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        }
    }
Variable Documentation
XSVF_Player xsvf
Definition at line 13 of file xsvfTask.cpp.
Referenced by XPI::DumpStatus(), XPI::InitializeFPGA(), ReadXSVF(), USBRCVR::Receiver(), and XPI::ResetFPGA().