XPU-DSAM7S: src/inc/xsvfPort.hpp File Reference
xsvfPort.hpp File Reference
#include "sam7xpud.hpp"
Defines
#define xsvfPrintf(...) tracef(1, __VA_ARGS__)
Functions
static int ReadXSVF (void)
static void SetTMS (int val)
static void SetTCK (int val)
static void SetTDI (int val)
static int GetTDO (void)
void uSleep (long microsec)
Define Documentation
#define xsvfPrintf (...) tracef(1, __VA_ARGS__)
Definition at line 18 of file xsvfPort.hpp.
Function Documentation
static int GetTDO (void) [inline, static]
Definition at line 54 of file xsvfPort.hpp.
References FPGA_JTAG_TDO, and ISSET.
Referenced by XSVF_Class::ShiftOnly().
{
    return ISSET( AT91F_PIO_GetInput( AT91C_BASE_PIOA ), FPGA_JTAG_TDO );
    }
static int ReadXSVF (void) [inline, static]
Definition at line 22 of file xsvfPort.hpp.
References XSVF_Player::getc(), and xsvf.
Referenced by XSVF_Class::Do_XCOMMENT(), XSVF_Class::Do_XENDXR(), XSVF_Class::Do_XREPEAT(), XSVF_Class::Do_XSDRINC(), XSVF_Class::Do_XSIR(), XSVF_Class::Do_XSTATE(), and XSVF_Class::Run().
{
    return xsvf.getc ();
    }
static void SetTCK (int val) [inline, static]
Definition at line 35 of file xsvfPort.hpp.
References FPGA_JTAG_TCK.
Referenced by XSVF_Class::GotoTapState(), XSVF_Class::ShiftOnly(), XSVF_Class::TmsTransition(), and uSleep().
{
    if ( val )
        AT91F_PIO_SetOutput( AT91C_BASE_PIOA, FPGA_JTAG_TCK );
    else
        AT91F_PIO_ClearOutput( AT91C_BASE_PIOA, FPGA_JTAG_TCK );
    asm volatile( "NOP" ); // We need this so TDO can settle before GetTDO()
    asm volatile( "NOP" );
    }
static void SetTDI (int val) [inline, static]
Definition at line 46 of file xsvfPort.hpp.
References FPGA_JTAG_TDI.
Referenced by XSVF_Class::ShiftOnly().
{
    if ( val )
        AT91F_PIO_SetOutput( AT91C_BASE_PIOA, FPGA_JTAG_TDI );
    else
        AT91F_PIO_ClearOutput( AT91C_BASE_PIOA, FPGA_JTAG_TDI );
    }
static void SetTMS (int val) [inline, static]
Definition at line 27 of file xsvfPort.hpp.
References FPGA_JTAG_TMS.
Referenced by XSVF_Class::ShiftOnly(), and XSVF_Class::TmsTransition().
{
    if ( val )
        AT91F_PIO_SetOutput( AT91C_BASE_PIOA, FPGA_JTAG_TMS );
    else
        AT91F_PIO_ClearOutput( AT91C_BASE_PIOA, FPGA_JTAG_TMS );
    }
void uSleep (long microsec)
Definition at line 164 of file xsvfTask.cpp.
References SetTCK().
Referenced by XSVF_Class::Do_XWAIT(), and XSVF_Class::Shift().
{
    // Note: Manually adjusted (with oscilloscope) to give 1 us per while loop
    // with 50% duty cycle of TCK on AT91SAM7S256 with flash wait state setting
    // AT91C_MC_FWS_1FWS: 2 cycles for Read, 3 for Write operations
    //
    while( microsec-- > 0)
    {
        SetTCK( 0 );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        SetTCK( 1 );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        asm volatile( "NOP" );
        }
    }